Repository Satellite-im/Core-PWA, pull requests merged in 2021-12, with the labels that each got.

#329 chore(build): fix build
  libraries/WebRTC/Wire.ts
  nuxt.config.js
Labels: Missing Dev Review

#328 chore(textile-store): update textile convo to have timestamps on top level
  libraries/Enums/enums.ts
  libraries/Enums/types/message-routes.ts
  store/textile/actions.ts
  store/textile/mutations.ts
  store/textile/types.ts
Labels: Missing Dev Review

#330 feat(groupbehavior): modify message grouping behavior AP-107
  utilities/Messaging.ts
Labels: Ready for QA

#334 fix(glyphs): adjust formatting and add loader
  components/tailored/messaging/enhancers/Enhancers.vue
  components/tailored/messaging/enhancers/glyphs/Glyphs.html
  components/tailored/messaging/enhancers/glyphs/item/Item.html
  components/tailored/messaging/enhancers/glyphs/item/Item.vue
  components/tailored/messaging/enhancers/glyphs/item/info/Info.html
  components/tailored/messaging/enhancers/glyphs/item/info/Info.less
  components/tailored/messaging/enhancers/glyphs/mostUsed/MostUsed.html
  components/tailored/messaging/enhancers/glyphs/mostUsed/MostUsed.less
  components/tailored/messaging/enhancers/glyphs/mostUsed/MostUsed.vue
  components/tailored/messaging/enhancers/glyphs/nav/Nav.html
  components/tailored/messaging/enhancers/glyphs/nav/Nav.less
  components/tailored/messaging/enhancers/glyphs/pack/Pack.html
  components/tailored/messaging/enhancers/glyphs/pack/Pack.less
  components/tailored/messaging/enhancers/glyphs/pack/Pack.vue
  yarn.lock
Labels: Missing Dev Review

#331 refactor(volumes): update state for system sounds, media volume to change with output volume
  components/tailored/settings/pages/audio/Audio.html
  components/tailored/settings/pages/audio/index.vue
  locales/en-US.js
  store/audio/mutations.ts
  store/audio/state.ts
  store/audio/types.ts
Labels: Missing Dev Review

#346 fix(friendErrorMessage): have correct error messages show on user adding friends
  components/tailored/friends/add/Add.html
Labels: Ready for QA

#345 AP-158 Update our data in IPFS to pull from our Pinata gateway
  config.ts
  mock/files.ts
  mock/glyphs.ts
  mock/messages.ts
Labels: Ready for QA

#465 feat(Hounddog): added hounddog library and also cleaned up some code …
  components/tailored/core/chatbar/Chatbar.vue
  layouts/chat.vue
  pages/chat/direct/_address.vue
  pages/index.vue
  plugins/local/classLoader.ts
  store/friends/actions.ts
  utilities/Hounddog.ts
Labels: Missing Dev Review

#466 Logger
  components/tailored/core/chatbar/Chatbar.vue
  components/tailored/core/chatbar/Chatbar_OLD.vue
  components/tailored/core/group/Group.vue
  components/tailored/core/servers/create/Create.vue
  components/tailored/core/user/User.vue
  components/tailored/files/topbar/Topbar.vue
  components/tailored/messaging/message/Message.vue
  config.ts
  libraries/WebRTC/WebRTC.ts
  libraries/WebRTC/Wire.ts
  plugins/local/classLoader.ts
  startup.js
  store/prerequisites/actions.ts
  store/textile/actions.ts
  store/webrtc/actions.ts
  utilities/ConsoleWarning.ts
  utilities/Hounddog.ts
  utilities/Logger.ts
Labels: Missing Dev Review

#467 fix(upload): fix upload for large files
  components/tailored/core/fileupload/FileUpload.html
  components/tailored/core/fileupload/FileUpload.less
  components/tailored/core/fileupload/FileUpload.vue
  components/tailored/files/uploader/Uploader.vue
  config.ts
Labels: Ready for QA

#472 chore: fix bulk typo
  libraries/WebRTC/WebRTC.ts
  pages/auth/register/index.vue
  pages/generic/loading/index.vue
  store/accounts/actions.ts
  store/accounts/state.ts
  store/accounts/types.ts
  store/audio/state.ts
  store/files/state.ts
  store/friends/state.ts
  store/prerequisites/state.ts
  store/search/state.ts
  store/settings/state.ts
  store/textile/state.ts
  store/ui/state.ts
  store/video/state.ts
  store/webrtc/state.ts
Labels: Missing Dev Review

#476 AP-110
  components/interactables/ButtonGroup/ButtonGroup.vue
  components/tailored/friends/add/Add.html
  components/tailored/friends/add/Add.vue
  layouts/chat.vue
Labels: Missing Dev Review, QA approved

#468 fix(chatbar): replies style and focus on reply AP-155
  components/tailored/core/chatbar/Chatbar.html
  components/tailored/core/chatbar/Chatbar.vue
  layouts/chat.vue
  plugins/thirdparty/persist.ts
Labels: Ready for QA

#470 feat(typehead): Create Reusable Typeahead Component to be used in the Import Account Component
  components/ui/TypeHead/TypeHead.html
  components/ui/TypeHead/TypeHead.less
  components/ui/TypeHead/TypeHead.vue
  pages/setup/InputAccount/InputAccount.html
  pages/setup/InputAccount/index.vue
Labels: Ready for QA

#477 feat(callduration): shows the call duration (AP-6)
  components/tailored/core/media/Media.vue
  components/tailored/core/media/heading/Heading.html
  components/tailored/core/media/heading/Heading.vue
  plugins/thirdparty/persist.ts
  store/webrtc/state.ts
  store/webrtc/types.ts
Labels: Missing Dev Review

#551 feat(contextmenu): sidebar contextmenu in the friends list updated (AP-172)
  components/tailored/core/user/User.vue
Labels: Missing Dev Review, QA approved

#535 refactor(profile locations): automatically grab users location to display in profile
  components/tailored/settings/profile/card/Card.html
  components/tailored/settings/profile/card/Card.vue
  mock/profile.ts
Labels: Missing Dev Review, QA approved

#561 chore: update cypress version
  package.json
Labels: Missing Dev Review, QA approved

#568 Chatbar should always be visible - AP-151
  components/tailored/core/chatbar/Chatbar.html
  components/tailored/core/chatbar/Chatbar.less
  components/tailored/core/chatbar/Chatbar.vue
  components/tailored/core/chatbar/controls/Controls.html
  components/tailored/core/chatbar/controls/Controls.less
  components/tailored/core/chatbar/controls/Controls.vue
  components/tailored/core/fileupload/FileUpload.html
  components/tailored/core/fileupload/FileUpload.less
  components/tailored/core/fileupload/FileUpload.vue
  components/tailored/files/controls/Controls.html
  layouts/chat.vue
Labels: Changes Requested, Missing Dev Review

#565 feat(import account): recover account from phrases you input
  components/ui/TypeHead/TypeHead.vue
  pages/setup/InputAccount/InputAccount.html
  pages/setup/InputAccount/README.md
  pages/setup/InputAccount/index.vue
  store/accounts/actions.ts
Labels: Missing Dev Review, QA approved

#583 feat(inputmultiple): allow user to paste recovery phrase into text input (AP-244)
  components/ui/TypeHead/TypeHead.vue
  pages/setup/InputAccount/InputAccount.html
  pages/setup/InputAccount/index.vue
Labels: Changes Requested, Missing Dev Review

#479 chore: improve husky rules
  package.json
Labels: Missing Dev Review, QA approved

#602 Cypress - Add Import Account test + data-cy labels + add joe's fix on nuxt config
  components/ui/TypeHead/TypeHead.html
  cypress/integration/import-account.js
  cypress/support/commands.js
  nuxt.config.js
Labels: QA approved

#624 fix: fix wrong string on emoji reaction on chat
  components/tailored/messaging/message/actions/Actions.html
Labels: Missing Dev Review, QA approved

#621 test: add more cypress tests + improvements
  cypress/integration/chat-features.js
  cypress/integration/create-account.js
  cypress/integration/import-account.js
  cypress/support/commands.js
Labels: Missing Dev Review, QA approved

#629 task: add github action for conflicts label
  .github/workflows/add-conflicts-label.yml
Labels: Missing Dev Review

#615 feat: app should remember last page, when you reload/come back to app (AP-173)
  middleware/authenticated.ts
  pages/index.vue
  store/accounts/mutations.ts
  store/accounts/state.ts
  store/accounts/types.ts
Labels: QA approved

#637 chore: fix typos
  components/interactables/Button/README.md
  components/interactables/ContextMenu/ContextMenu.vue
  components/interactables/InputGroup/InputGroup.vue
  components/interactables/QuickProfile/QuickProfile.vue
  components/tailored/core/chatbar/controls/Controls.vue
  components/tailored/core/chatbar/reply/Reply.vue
  components/tailored/core/media/Media.vue
  components/tailored/core/media/heading/Heading.vue
  components/tailored/files/controls/Controls.vue
  components/tailored/messaging/enhancers/Enhancers.vue
  components/ui/Global/Global.vue
  libraries/WebRTC/WebRTC.ts
  plugins/thirdparty/persist.ts
  startup.js
Labels: Missing Dev Review

#564 fix: fix mobile cut off phrases on import account AP-159
  pages/setup/InputAccount/InputAccount.less
  pages/setup/InputAccount/index.vue
Labels: Ready for QA

#609 feat: track emoji usage, display most frequent emojis on context menu & emoji dialog
  components/interactables/ContextMenu/ContextMenu.html
  components/interactables/ContextMenu/ContextMenu.vue
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/Enhancers.vue
  store/ui/getters.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Ready for QA

#625 fix: char counter update on emoji - [AP-169]
  components/views/chat/chatbar/footer/Footer.vue
Labels: QA approved

#649 feat(Emoji): make emoji's bigger and better
  assets/styles/base.less
  components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.less
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  config.ts
  startup.js
Labels: Changes Requested

#648 task(githubAction): add github action lint PR title
  .github/workflows/lint-PR-title.yml
Labels: Missing Dev Review

#664 fix(loading icon): messageLoading was never being set to false
  store/textile/actions.ts
Labels: Missing Dev Review, QA approved

#628 fix(ImportAccount): last typed phrase suggestions when user starts to type next phrase - AP-256
  components/ui/TypeHead/TypeHead.vue
Labels: Ready for QA

#614 fix: persist the replies when switching conversations - AP-235
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/message/reply/Reply.html
  components/views/chat/message/reply/Reply.vue
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
  types/chat/chat.ts
Labels: Ready for QA

#655 feat(Quick Profile): Implement Quick Profile
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.vue
  components/ui/Global/Global.html
  components/views/chat/group/Group.vue
  components/views/chat/message/reply/Reply.vue
  utilities/Messaging.ts
Labels: Missing Dev Review

#678 task(Cypress): add more Cypress tests
  components/ui/Version/Version.vue
  cypress/integration/chat-features.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/verify-toggles-privacy-settings.js
  cypress/integration/version-release-notes.js
  cypress/support/commands.js
Labels: Missing Dev Review

#679 task(githubAction): update regex to include test type
  .github/workflows/lint-PR-title.yml
Labels: Missing Dev Review

#677 fix(friends): friends - account id should be cleared after friend request is sent
  components/views/friends/add/Add.vue
Labels: Missing Dev Review, QA approved

#687 task(template): minor improvement on PR template
  PULL_REQUEST_TEMPLATE.md
Labels: Missing Dev Review

#691 fix(unpinStringOnFile): add correct string to render
  components/views/files/view/View.html
Labels: Missing Dev Review, QA approved

#696 task(githubAction): add github action to add labels
  .github/workflows/add-label.yml
Labels: Missing Dev Review, QA approved

#698 fix(chat): send empty message when click send icon
  config.ts
Labels: QA approved

#680 fix(refactor): refactor tracker codes
  utilities/Messaging.ts
Labels: Ready for QA

#674 fix(engTranslations): add text to translation file - AP-277
  components/interactables/Search/Result/Result.html
  components/ui/UpdateModal/UpdateModal.html
  components/views/files/aside/Aside.html
  components/views/files/controls/Controls.html
  components/views/files/upload/Upload.html
  components/views/friends/add/Add.html
  components/views/friends/quick/Quick.html
  components/views/marketplace/Marketplace.html
  components/views/marketplace/glyphs/Glyphs.html
  components/views/marketplace/glyphs/featured/Featured.html
  components/views/marketplace/glyphs/popular/Popular.html
  components/views/marketplace/glyphs/recommended/Recommended.html
  components/views/marketplace/glyphs/trending/Trending.html
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/live/Live.html
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/pinned/Pinned.html
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/wallet/accounts/Accounts.html
  components/views/wallet/balance/Balance.html
  components/views/wallet/mini/body/Body.html
  components/views/wallet/popup/Popup.html
  components/views/wallet/recent/Recent.html
  pages/files/browse/Browse.html
Labels: Ready for QA

#704 feat(importAccount): allow picking phrases with keyboard #AP-258
  components/ui/TypeHead/TypeHead.html
  components/ui/TypeHead/TypeHead.vue
  pages/setup/ImportAccount/index.vue
Labels: Missing Dev Review, QA approved

#702 fix(paste): fix 'unable to paste the text into chat'
  components/views/chat/chatbar/Chatbar.vue
Labels: Missing Dev Review, QA approved

#703 feat(images): enable multiple upload, add spinner, allow multi file types
  components/ui/Chat/Embeds/File/File.html
  components/ui/Chat/Embeds/File/File.vue
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/message/Message.html
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.less
  components/views/files/upload/Upload.vue
  components/views/files/view/View.html
  libraries/Enums/enums.ts
  libraries/Enums/types/encoding-types.ts
  libraries/Enums/types/messaging-types.ts
  libraries/Enums/types/prop-common-events.ts
  libraries/Textile/MailboxManager.ts
  libraries/Textile/encoders.ts
  store/textile/actions.ts
  store/textile/mutations.ts
  store/textile/state.ts
  store/textile/types.ts
  types/messaging.d.ts
  types/textile/mailbox.ts
Labels: Missing Dev Review, QA approved

#731 fix(createErrorsInLocales): set up errors for locales
  components/views/servers/create/Create.vue
  components/views/user/create/Create.vue
Labels: Missing Dev Review, QA approved

#732 fix(chatEdit): fix broken layout if edit a message without anyspaces
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/edit/Edit.less
  components/views/chat/message/edit/Edit.vue
Labels: Missing Dev Review, QA approved

#740 fix(chatBar): address undefined issue in chat page
  components/views/chat/chatbar/Chatbar.vue
Labels: Ready for QA

#753 chore(Hounddog): moved some call data to hounddog
  components/ui/Global/Global.html
  components/views/media/Media.html
  utilities/Hounddog.ts
Labels: Missing Dev Review

#756 chore(search): add function to search users by name
  libraries/Solana/ServerProgram/ServerProgram.ts
Labels: Missing Dev Review

#757 fix(chat): Implement input length limit for quick profile #AP-295
  components/interactables/InputGroup/InputGroup.html
  components/interactables/InputGroup/InputGroup.less
  components/interactables/InputGroup/InputGroup.vue
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.vue
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/footer/Footer.vue
  config.ts
Labels: Missing Dev Review, QA approved

#738 fix(images): fix multi upload bug
  components/views/chat/chatbar/Chatbar.vue
  components/views/files/upload/Upload.vue
  libraries/Enums/types/messaging-types.ts
  libraries/Enums/types/prop-common-events.ts
  libraries/Textile/BucketManager.ts
  store/textile/actions.ts
Labels: Missing Dev Review, QA approved

#765 chore(login): prevent shifting of login on desktop
  pages/index.vue
Labels: Missing Dev Review, QA approved

#771 fix(reply): fix invalid message payload when replying to message
  libraries/Enums/types/messaging-types.ts
Labels: Missing Dev Review

#762 feat(editChat): improve messages edit
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/footer/Footer.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/edit/Edit.less
  components/views/chat/message/edit/Edit.vue
  config.ts
  libraries/Enums/types/keybindings.ts
Labels: Missing Dev Review, missing fixing conflict

#800 Slimbar fix
  assets/styles/platforms/iOS.less
  assets/styles/themes/moonless_night.less
  components/views/navigation/sidebar/Sidebar.html
  nuxt.config.js
Labels: Missing Dev Review

#798 fix(signup): fix sign up with just spaces on username
  components/views/user/create/Create.vue
Labels: Ready for QA

#801 feat(Friends): combine friends routes
  assets/styles/platforms/iOS.less
  assets/styles/themes/moonless_night.less
  components/views/friends/add/Add.less
  mock/friends.ts
  pages/friends/list/FriendsList.html
  pages/friends/list/FriendsList.less
Labels: Missing Dev Review

#803 chore(Meters): simplify the meters code and performance
  components/ui/Meter/Meter.html
  components/ui/Meter/Meter.less
  components/ui/Meter/Meter.vue
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/Audio.less
Labels: Missing Dev Review

#751 test(jest): add jest tests
  jest.config.js
  test/Chatbar.test.ts
  test/Circle.test.ts
  test/Commands.test.ts
  test/ConsoleWarning.test.ts
  test/Crypto.spec.ts
  test/Crypto.test.ts
  test/EXIF.skip.ts
  test/Friends.test.ts
  test/IdentityManager.skip.ts
  test/Messaging.test.ts
  test/Notifications.skip.ts
  test/ReleaseNotes.test.ts
  test/ServerProgram.layout.test.ts
  test/SimpleWrap.test.ts
  test/Solana.test.ts
  test/SolanaManager.test.ts
  test/__snapshots__/Chatbar.test.ts.snap
  test/__snapshots__/Circle.test.ts.snap
  test/__snapshots__/Commands.test.ts.snap
  test/__snapshots__/ConsoleWarning.test.ts.snap
  test/__snapshots__/Friends.test.ts.snap
  test/__snapshots__/Messaging.test.ts.snap
  test/__snapshots__/SimpleWrap.test.ts.snap
  test/__snapshots__/Solana.test.ts.snap
  test/__snapshots__/io-ts.test.ts.snap
  test/__snapshots__/utils.test.ts.snap
  test/io-ts.test.ts
  test/utils.test.ts
Labels: QA approved

#802 feat(Themes): added custom flair color selector
  assets/styles/themes/moonless_night.less
  components/interactables/Select/Select.html
  components/interactables/Select/Select.less
  components/interactables/Select/Select.vue
  components/ui/Chat/Image/Image.html
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/personalize/index.vue
  layouts/chat.vue
  layouts/default.vue
  layouts/files.vue
  layouts/friends.vue
  layouts/server.vue
  nuxt.config.js
  plugins/local/style.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Changes Requested, Missing Dev Review, missing fixing conflict

#813 fix(glyph): state was removed in a PR, file was throwing error
  store/ui/state.ts
Labels: Missing Dev Review

#796 fix(activeCall): activeCall issue that moves chatbar when full screen #AP-361
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/Enhancers.vue
  components/views/media/actions/Actions.vue
  layouts/Layout.less
  layouts/chat.vue
Labels: Ready for QA

#809 fix(Themes): add additional theme support to inputs
  assets/styles/themes/moonless_night.less
  components/ui/Chat/Image/Image.html
  components/views/settings/pages/audio/Audio.html
  components/views/settings/unit/Unit.html
  components/views/settings/unit/Unit.less
  components/views/settings/unit/Unit.vue
Labels: Ready for QA

#808 fix(settingsNav): shows the page when selecting menu in settings
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.vue
Labels: QA approved

#812 feat(upload): Re-work the file/multiple file upload ui
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.less
  components/views/files/upload/Upload.vue
  components/views/files/upload/previewItem/PreviewItem.html
  components/views/files/upload/previewItem/PreviewItem.less
  components/views/files/upload/previewItem/PreviewItem.vue
Labels: Missing Dev Review

#817 feat(call): dont allow clicking icons if peer is not connected
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
  libraries/WebRTC/WebRTC.ts
  plugins/thirdparty/persist.ts
  store/webrtc/actions.ts
  store/webrtc/mutations.ts
  store/webrtc/state.ts
  store/webrtc/types.ts
Labels: Missing Dev Review

#824 test(jest): add more jest tests
  test/Chatbar.test.ts
  test/ComponentsMixinsTouchIndex.test.ts
  test/ContextMenu.test.ts
  test/EXIF.skip.ts
  test/Friends.test.ts
  test/FriendsProgram.layout.test.ts
  test/IndexUserPermissions.test.ts
  test/Logger.test.ts
  test/SearchUtil.test.ts
  test/StoreAudioActions.test.ts
  test/StoreAudioMutations.test.ts
  test/StoreAudioState.test.ts
  test/StoreChatMutations.test.ts
  test/StoreChatState.test.ts
  test/StoreDataStateMutations.test.ts
  test/StoreDataStateState.test.ts
  test/StoreFilesActions.test.ts
  test/StoreFilesMutations.test.ts
  test/StoreFilesState.test.ts
  test/StoreMediaActions.test.ts
  test/StorePreRequisitesGetters.test.ts
  test/StorePreRequisitesMutations.test.ts
  test/StorePreRequisitesState.test.ts
  test/StoreSearchMutations.test.ts
  test/StoreSearchState.test.ts
  test/StoreSettingsMutations.test.ts
  test/StoreSettingsState.test.ts
  test/StoreTextileActions.test.ts
  test/StoreVideoMutations.test.ts
  test/StoreVideoState.test.ts
  test/Utils.test.ts
  test/__snapshots__/Chatbar.test.ts.snap
  test/__snapshots__/ComponentsMixinsTouchIndex.test.ts.snap
  test/__snapshots__/Friends.test.ts.snap
  test/__snapshots__/FriendsProgram.layout.test.ts.snap
  test/__snapshots__/SearchUtil.test.ts.snap
  test/__snapshots__/StoreAudioMutations.test.ts.snap
  test/__snapshots__/StoreAudioState.test.ts.snap
  test/__snapshots__/StoreChatMutations.test.ts.snap
  test/__snapshots__/StoreChatState.test.ts.snap
  test/__snapshots__/StoreDataStateState.test.ts.snap
  test/__snapshots__/StoreFilesActions.test.ts.snap
  test/__snapshots__/StoreFilesMutations.test.ts.snap
  test/__snapshots__/StoreFilesState.test.ts.snap
  test/__snapshots__/StoreMediaActions.test.ts.snap
  test/__snapshots__/StorePreRequisitesGetters.test.ts.snap
  test/__snapshots__/StorePreRequisitesMutations.test.ts.snap
  test/__snapshots__/StorePreRequisitesState.test.ts.snap
  test/__snapshots__/StoreSearchMutations.test.ts.snap
  test/__snapshots__/StoreSearchState.test.ts.snap
  test/__snapshots__/StoreSettingsMutations.test.ts.snap
  test/__snapshots__/StoreSettingsState.test.ts.snap
  test/__snapshots__/StoreVideoMutations.test.ts.snap
  test/__snapshots__/StoreVideoState.test.ts.snap
  test/__snapshots__/Utils.test.ts.snap
Labels: Ready for QA

#836 chore(cypress): move cypress to submodule
  .gitmodules
  cypress/fixtures/images/logo.png
  cypress/integration/chat-features.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/import-account.js
  cypress/integration/verify-toggles-privacy-settings.js
  cypress/integration/version-release-notes.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: Ready for QA
