Repository Satellite-im/Core-PWA, pull requests merged in 2021-11, with the labels that each got.

#284 chore - improve grammar on locales file
  locales/en-US.js
Labels: Ready for QA

#279 refactor(Typing Indicator): AP-37 - Typing indicator component now accepts an array of user names displaying up to 3 names, when 4+ names: displays many typing, and 0: nothing
  components/tailored/core/chatbar/footer/Footer.vue
  components/ui/TypingIndicator/TypingIndicator.html
  components/ui/TypingIndicator/TypingIndicator.vue
Labels: Ready for QA

#287 fix(File): Fix style issue when open Anime image on File
  components/tailored/files/view/View.less
Labels: Ready for QA

#291 chore - fix typo
  components/tailored/core/statusbar/Statusbar.html
Labels: Ready for QA

#292 feat(Chatbar): can now paste images into chatbar
  components/tailored/core/chatbar/Chatbar.html
  components/tailored/core/chatbar/Chatbar.vue
  locales/en-US.js
Labels: missing dev review, QA tested

#283 Fix(iOSFitScreen): Fix app doesn't fit to screen SA-298
  components/tailored/core/sidebar/Sidebar.less
  components/tailored/servers/sidebar/Sidebar.html
  components/tailored/servers/sidebar/Sidebar.less
  nuxt.config.js
Labels: Ready for QA

#293 test - add jest into the project
  babel.config.js
  jest.config.js
  package.json
  test/Crypto.spec.ts
  test/Logo.spec.js
  yarn.lock
Labels: missing dev review

#295 fix(Chatbar): stops empty messages from sending
  components/tailored/core/chatbar/Chatbar.vue
Labels: QA approved

#297 Github Action - Remove labels on merged PR's
  .github/workflows/main.yml
Labels: Ready for QA

#298 Github Action - Rebase when adding a comment saying /rebase
  .github/workflows/rebase.yml
Labels: missing dev review

#303 feat(MiniWallet): Added mini wallet component
  components/interactables/QuickProfile/QuickProfile.html
  components/tailored/core/group/icon/GroupIcon.html
  components/tailored/core/user/User.html
  components/tailored/friends/friend/Friend.html
  components/tailored/wallet/mini/Mini.vue
  components/tailored/wallet/mini/body/Body.html
  components/tailored/wallet/mini/body/Body.less
  components/tailored/wallet/mini/body/Body.vue
  components/tailored/wallet/mini/nav/Nav.html
  components/tailored/wallet/mini/nav/Nav.less
  components/tailored/wallet/mini/nav/Nav.vue
  components/tailored/wallet/mini/send/Send.html
  components/tailored/wallet/mini/send/Send.less
  components/tailored/wallet/mini/send/Send.vue
  test/Crypto.spec.ts
Labels: Missing Dev Review, QA approved

#301 test - add cypress data-cy labels + update jest test
  components/tailored/core/user/create/Create.html
  cypress/integration/create-account.js
  cypress/support/commands.js
  package.json
  test/Crypto.spec.ts
  yarn.lock
Labels: Missing Dev Review, QA approved

#305 Fix(ChatCutting): fix when sending a huge message, get cut off
  components/tailored/messaging/message/Message.less
Labels: Ready for QA, Missing Dev Review

#304 fix(Archived Messages): FIxes badge used for archived messages
  components/tailored/messaging/message/Message.html
  components/tailored/messaging/message/Message.less
  components/tailored/messaging/message/Message.vue
Labels: Ready for QA, Missing Dev Review

#299 feat(user): user state component
  components/tailored/core/sidebar/status/Status.html
  components/tailored/core/statusbar/Statusbar.html
  components/tailored/core/statusbar/Statusbar.less
  components/tailored/core/user/User.html
  components/tailored/core/user/User.less
  components/tailored/friends/add/Add.vue
  components/tailored/friends/friend/Friend.html
  components/tailored/friends/friend/Friend.less
  components/tailored/messaging/group/Group.html
  components/tailored/messaging/group/Group.vue
  components/tailored/settings/pages/user/Search.vue
  components/ui/User/User.html
  components/ui/User/User.less
  components/ui/UserState/UserState.less
  components/ui/UserState/UserState.vue
  pages/friends/list/index.vue
  utilities/Messaging.ts
Labels: Missing Dev Review

#302 Fix(Login): Unlock should be persisted when store pin is enabled
  pages/auth/unlock/index.vue
  plugins/thirdparty/persist.ts
  store/accounts/mutations.ts
  store/prerequisites/mutations.ts
Labels: Ready for QA, Missing Dev Review

#310 chore - fix lint + linting files + update packages
  .eslintrc.js
  babel.config.js
  components/tailored/messaging/message/actions/Actions.vue
  components/tailored/servers/sidebar/channels/VoiceUser/VoiceUser.vue
  components/tailored/settings/pages/developer/index.vue
  components/ui/CaretDivider/CaretDivider.vue
  components/ui/ChatScroll/ChatScroll.vue
  components/ui/Global/Global.vue
  components/ui/Popups/Error/Error.vue
  components/ui/TypingIndicator/TypingIndicator.vue
  components/ui/UpdateModal/UpdateModal.vue
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/plugins/index.js
  cypress/support/commands.js
  jest.config.js
  locales/en-US.js
  package.json
  yarn.lock
Labels: Missing Dev Review

#286 fix(enhancers): Made enhancers position dependent on where you click enhancers from, if mobile, setting floating to true. hide scrollbars in chrome
  components/interactables/QuickProfile/QuickProfile.html
  components/tailored/core/chatbar/controls/Controls.vue
  components/tailored/messaging/enhancers/Enhancers.html
  components/tailored/messaging/enhancers/Enhancers.less
  components/tailored/messaging/enhancers/Enhancers.vue
  components/tailored/messaging/message/Message.vue
  components/tailored/messaging/message/actions/Actions.html
  components/tailored/messaging/message/reactions/Reactions.html
  components/tailored/messaging/message/reactions/Reactions.vue
  components/tailored/messaging/message/reply/Reply.html
  components/tailored/messaging/message/reply/Reply.vue
  layouts/chat.vue
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  yarn.lock
Labels: Changes Requested

#309 fix(Drop File): Fix 'Chat - If you copy paste a invalid image, gets stuck on scanning image'
  components/tailored/core/fileupload/FileUpload.html
  components/tailored/core/fileupload/FileUpload.less
  components/tailored/core/fileupload/FileUpload.vue
  locales/en-US.js
Labels: Missing Dev Review

#317 chore - fix yarn file
  yarn.lock
Labels: Missing Dev Review

#316 feat(commitlint): add husky commit-msg check
  .husky/commit-msg
  commitlint.config.js
Labels: Missing Dev Review

#306 fix(chat reaction): Fix 'Emoji reactions will increase if user navigates to a different page and back to chat again'
  utilities/Messaging.ts
Labels: Missing Dev Review

#300 fix(message): update timestamp message every minute
  components/tailored/messaging/group/Group.html
  components/tailored/messaging/group/Group.vue
  components/tailored/messaging/message/Message.html
  components/tailored/messaging/message/Message.vue
  config.ts
  utilities/Messaging.ts
Labels: Missing Dev Review, QA approved

#311 implements lazy loading for glyphs - AP-101
  components/tailored/marketplace/glyphs/Glyphs.vue
  components/tailored/messaging/enhancers/glyphs/Glyphs.html
  nuxt.config.js
  package.json
  plugins/thirdparty/vuetify.ts
Labels: Missing Dev Review

#308 fix - Duplicate friends are being added when page is re-rendered - AP-64
  store/friends/actions.ts
  store/friends/mutations.ts
Labels: Changes Requested, Missing Dev Review

#325 chore - rename file
  .github/workflows/remove-labels.yml
Labels: Missing Dev Review

#322 chore: update jest coverage rules + update prettier rules
  .prettierrc
  cypress/integration/create-account-negative-tests.js
  jest.config.js
  tsconfig.json
Labels: Missing Dev Review

#324 feat(webrtc): add low level abstractions for handling p2p connections and audio/video calls
  .prettierrc
  libraries/Textile/IdentityManager.ts
  libraries/Textile/encoders.ts
  libraries/WebRTC/Call.ts
  libraries/WebRTC/Emitter.ts
  libraries/WebRTC/WebRTC.ts
  libraries/WebRTC/Wire.ts
  libraries/WebRTC/encoders.ts
  libraries/WebRTC/types.ts
  p2pt.d.ts
  package.json
  tsconfig.json
  types/webrtc/User.d.ts
  yarn.lock
Labels: Missing Dev Review

#323 Chat Window Status Bar User Info - #AP-109
  components/tailored/core/statusbar/Statusbar.html
  layouts/chat.vue
  store/friends/actions.ts
Labels: Changes Requested
