Repository Satellite-im/Core-PWA, pull requests merged in 2022-06, with the labels that each got.

#3404 fix(call): change position of fullscreen call and reset fullscreen on…
  assets/styles/framework/framework.less
  layouts/Layout.less
  store/webrtc/actions.ts
Labels: QA tested

#3402 fix(files): set file values on beforeMount so user can close overlay …
  components/views/files/view/View.vue
Labels: QA tested

#3382 fix(alerts): return close button
  components/views/navigation/toolbar/alerts/alert/Alert.less
Labels: testing blocked

#3244 feat(call): add permission error alert for screen sharing
  components/views/media/actions/Actions.vue
  components/views/navigation/sidebar/controls/Controls.vue
  libraries/WebRTC/Call.ts
  libraries/WebRTC/errors/Errors.ts
  store/webrtc/actions.ts
Labels: QA tested

#3409 fix(mobile): fix coming soon tooltip not showing in friends/groups search bar
  components/views/navigation/mobile/sidebar/sidebar.vue
Labels: QA tested

#3406 fix(call): show user avatar while calling
  components/views/media/user/User.html
  components/views/media/user/User.vue
Labels: Changes Requested

#3432 fix(groups): add correct color for avatar in group chats
  components/views/chat/group/Group.html
  components/views/chat/group/Group.vue
Labels: Ready for QA

#3429 fix(chat): static timestamps, remove interval
  components/typography/HorizontalRuleText/HorizontalRuleText.vue
  components/views/chat/group/Group.html
  components/views/chat/group/Group.vue
  components/views/chat/message/reply/Item/Item.vue
Labels: QA tested

#3431 fix(groups): display color avatar in sidebar if no picture found
  components/ui/Circle/Circle.html
  components/views/group/clickable/Clickable.vue
  components/views/group/icon/GroupIcon.html
  components/views/group/icon/GroupIcon.less
  components/views/group/icon/GroupIcon.vue
Labels: Ready for QA

#3438 chore(ci): improve docker
  package.json
Labels: draft

#3446 chore(cypress): minor updates
  cypress/integration/chat-features.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-search.js
  cypress/integration/chat-text-validations.js
  cypress/integration/create-account.js
  cypress/integration/pin-unlock-validations.js
Labels: Missing Dev Review

#3435 fix(slimbar): logic to show only friends with unread messages
  components/ui/Unread/Unread.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/slimbar/Slimbar.vue
  layouts/chat.vue
  layouts/files.vue
  layouts/friends.vue
  layouts/server.vue
  store/friends/getters.ts
Labels: QA tested

#3434 fix(toolbar): quality of life improvements. remove broken code
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
  layouts/chat.vue
  types/ui/core.d.ts
  types/ui/friends.d.ts
Labels: QA tested

#3456 fix(chat): fix avatar colors for dm
  components/views/chat/group/Group.html
  components/views/chat/group/Group.vue
Labels: Ready for QA

#3436 fix(progress): change progress bar color to your selected flair
  assets/styles/base.less
  components/ui/Progress/Progress.html
  components/ui/Progress/Progress.less
  components/views/files/upload/previewItem/PreviewItem.html
  components/views/files/upload/previewItem/PreviewItem.less
  components/views/files/upload/previewItem/PreviewItem.vue
Labels: QA tested

#3465 test(cypress): add settings tests
  cypress/integration/settings-features.js
Labels: Missing Dev Review

#3460 fix(groups): members order sorted alpha
  components/views/navigation/toolbar/Toolbar.vue
  layouts/chat.vue
  store/groups/mutations.ts
Labels: Ready for QA

#3471 feat(jest): 80% coverage for store/ui/mutations
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#3470 feat(jest): 95% branch coverage for store/ui/actions
  store/ui/actions.test.ts
Labels: Missing Dev Review

#3451 chore(faucet): testing different dev faucet
  config.ts
  libraries/Solana/SolanaManager/SolanaManager.ts
Labels: Ready for QA

#3494 fix(search): scroll to top on paginate
  components/ui/Scroll/Scroll.vue
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/Result.vue
Labels: Ready for QA

#3493 fix(sidebar): count label style
  components/views/group/icon/GroupIcon.less
Labels: Ready for QA

#3473 fix(chatbar): prevent send if over limit, switch limit to be more accurate
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/footer/Footer.vue
Labels: Ready for QA

#3401 fix(groups): prevent submit if groupname too short
  assets/styles/base.less
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/interactables/Input/Input.vue
  components/typography/Error/Error.html
  components/typography/Error/Error.vue
  components/views/friends/mobile/list.vue
  components/views/friends/quick/Quick.html
  components/views/friends/quick/Quick.less
  components/views/friends/quick/Quick.vue
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/settings/pages/user/Search.less
  components/views/settings/pages/user/Search.vue
  config.ts
  locales/en-US.js
  pages/friends/list/index.vue
  pages/friends/mobile/add/index.vue
  pages/friends/mobile/block/index.vue
  pages/friends/mobile/incoming/index.vue
  store/ui/types.ts
Labels: Ready for QA

#3497 chore(bundle): remove feather icons
  components/views/chat/message/edit/Edit.vue
  package.json
Labels: Ready for QA

#3472 fix(settings): switch privacy settings loading list to array
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
Labels: testing blocked

#3467 fix(quick): show dropdown below input
  components/views/friends/quick/Quick.html
  components/views/settings/pages/user/Search.html
  components/views/settings/pages/user/Search.less
Labels: testing blocked

#3325 fix(chat): disable auto redirect from chat to friend list on first visit
  pages/chat/direct/_address.vue
  store/accounts/actions.ts
  store/friends/actions.test.ts
  store/friends/actions.ts
Labels: testing blocked

#3500 feat(jest): 100% branch coverage for store/settings/actions
  store/settings/actions.test.ts
Labels: Missing Dev Review

#3501 feat(jest): 100% coverage and branch coverage for store/groups/mutations
  store/groups/__snapshots__/mutations.test.ts.snap
  store/groups/mutations.test.ts
Labels: Missing Dev Review

#3474 refactor(sidebar): switch props to store when possible
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  layouts/chat.vue
  layouts/files.vue
  layouts/friends.vue
Labels: QA tested

#3453 fix(volume): bind output slider volume to stream volume
  components/ui/Chat/TypingIndicator/TypingIndicator.vue
  components/views/media/Media.vue
  components/views/media/user/User.html
  components/views/media/user/User.vue
  components/views/settings/pages/realms/realm/index.vue
Labels: QA tested

#3509 refactor(conversation): clean markup related to typing indicators
  components/ui/Chat/TypingIndicator/TypingIndicator.html
  components/ui/Chat/TypingIndicator/TypingIndicator.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/footer/Footer.html
  components/views/chat/chatbar/footer/Footer.vue
  components/views/chat/chatbar/footer/connected/Connected.html
  components/views/chat/chatbar/footer/connected/Connected.less
  components/views/chat/chatbar/footer/connected/Connected.vue
  locales/en-US.js
  store/conversation/getters.ts
  store/conversation/types.ts
Labels: Ready for QA

#3475 fix(store): switch accounts getters to direct store access
  pages/auth/register/index.vue
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/index.vue
  pages/index.vue
  store/accounts/getters.test.ts
  store/accounts/getters.ts
Labels: QA tested

#3508 fix(chat): fix is active call logic
  layouts/chat.vue
Labels: QA tested

#3522 chore(locals): grammer fix
  locales/en-US.js
Labels: Missing Dev Review

#3478 fix(profile): disable show user profile
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.less
  components/interactables/QuickProfile/QuickProfile.vue
  components/ui/Unread/Unread.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/user/User.vue
Labels: QA tested

#3285 feat(buckets): upgrade abstract interfaces, switch chat to use SharedBucket class
  components/ui/Chat/Embeds/File/File.html
  components/ui/Chat/Embeds/File/File.vue
  components/ui/Chat/Embeds/File/types.d.ts
  components/ui/Chat/Image/Image.vue
  components/views/chat/message/Message.vue
  components/views/files/upload/Upload.vue
  components/views/files/view/View.vue
  config.ts
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/errors/Errors.ts
  libraries/Files/interface/RFM.interface.ts
  libraries/Files/remote/abstracts/Bucket.abstract.ts
  libraries/Files/remote/abstracts/RFM.abstract.ts
  libraries/Files/remote/interface/RFM.interface.ts
  libraries/Files/remote/textile/PersonalBucket.ts
  libraries/Files/remote/textile/SharedBucket.ts
  libraries/Files/test/Bucket.test.ts
  libraries/Files/test/TextileFileSystem.test.ts
  libraries/Files/types/filesystem.ts
  libraries/Textile/BucketManager.test.ts
  libraries/Textile/BucketManager.ts
  libraries/Textile/TextileManager.ts
  libraries/Textile/__snapshots__/BucketManager.test.ts.snap
  libraries/Textile/__snapshots__/encoders.test.ts.snap
  libraries/Textile/encoders.ts
  plugins/local/classLoader.ts
  store/accounts/actions.ts
  store/textile/actions.ts
  store/textile/mutations.test.ts
Labels: temporary blocked checking something

#3526 feat(jest): 78% coverage for store/audio/actions
  store/audio/actions.test.ts
Labels: Missing Dev Review

#3527 feat(jest): 100% coverage for store/conversation/getters
  store/conversation/__snapshots__/getters.test.ts.snap
  store/conversation/getters.test.ts
Labels: Missing Dev Review

#3531 fix(comingsoon): show modal on click
  components/ui/ComingSoon/ComingSoon.html
  components/ui/ComingSoon/ComingSoon.vue
  components/views/chat/message/actions/Actions.html
  components/views/chat/message/actions/Actions.less
  components/views/chat/message/actions/Actions.vue
  components/views/navigation/toolbar/Toolbar.html
  locales/en-US.js
Labels: Ready for QA

#3516 fix(call): hide grey border around avatar
  components/views/media/user/User.html
Labels: Ready for QA

#3505 feat(createAccount): better error messages/handling on username error
  components/views/friends/quick/Quick.vue
  components/views/user/create/Create.html
  components/views/user/create/Create.vue
  config.ts
  locales/en-US.js
Labels: Ready for QA

#3511 fix(call): show avatar in incoming call
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.less
  components/views/media/incomingCall/IncomingCall.vue
Labels: Ready for QA

#3249 chore(add): integrating solana adapter and blockchainclient
  .gitmodules
  .vscode/settings.json
  components/views/friends/add/Add.vue
  libraries/BlockchainClient/BlockchainClient.ts
  libraries/BlockchainClient/adapters/EthereumAdapter/EthereumAdapter.ts
  libraries/BlockchainClient/adapters/EthereumAdapter/index.ts
  libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.ts
  libraries/BlockchainClient/adapters/SolanaAdapter/index.ts
  libraries/BlockchainClient/adapters/SolanaAdapter/utils.ts
  libraries/BlockchainClient/index.ts
  libraries/BlockchainClient/interfaces.ts
  libraries/Textile/GroupChatManager.ts
  libraries/Textile/IdentityManager.ts
  libraries/Textile/MailboxManager.ts
  libraries/Textile/UserManager.ts
  plugins/local/classLoader.ts
  store/accounts/actions.ts
  store/friends/actions.test.ts
  store/friends/actions.ts
  store/groups/actions.test.ts
  store/groups/actions.ts
  store/textile/actions.ts
  types/textile/manager.ts
Labels: QA tested

#3540 chore(cypress): skip tests
  cypress/integration/chat-pair-features.js
Labels: draft

#3286 feat(chat): implement infinite scroll for chat messages
  components/ui/Chat/InfiniteScroll/InfiniteScroll.html
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/ui/Chat/Scroll/Scroll.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
  components/views/group/aside/Aside.less
  layouts/chat.vue
  libraries/Solana/__snapshots__/Solana.test.ts.snap
  locales/en-US.js
  pages/auth/register/index.vue
  pages/chat/direct/Direct.html
  pages/chat/direct/Direct.less
  pages/chat/direct/_address.vue
  pages/chat/groups/Group.html
  pages/chat/groups/Group.less
  pages/chat/groups/_id.vue
  pages/friends/list/FriendsList.html
  store/chat/__snapshots__/state.test.ts.snap
  store/chat/actions.ts
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
  store/textile/actions.ts
  store/textile/mutations.ts
  store/textile/types.ts
  types/chat/chat.ts
Labels: QA tested

#3542 chore(lint): minor lint
  components/views/settings/pages/user/Search.html
Labels: Ready for QA

#3545 fix(toolbar): add missing user avatar src prop
  components/views/navigation/toolbar/Toolbar.html
Labels: Ready for QA

#3529 fix(layout): remove overflow hidden
  components/views/media/heading/Heading.vue
  layouts/Layout.less
Labels: Ready for QA

#3484 fix(call): add possibility to call user via context menu
  components/views/media/Media.vue
  components/views/user/User.vue
  store/conversation/actions.ts
  store/conversation/mutations.ts
Labels: QA tested

#3499 fix(call): overflow for long user name in incoming call
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.less
Labels: Ready for QA

#3506 feat(interactables): user picker component
  components/interactables/Button/Button.less
  components/interactables/Button/types.d.ts
  components/interactables/Checkbox/Checkbox.html
  components/interactables/Checkbox/Checkbox.less
  components/interactables/Checkbox/Checkbox.vue
  components/interactables/UserPicker/ListItem/ListItem.html
  components/interactables/UserPicker/ListItem/ListItem.less
  components/interactables/UserPicker/ListItem/ListItem.vue
  components/interactables/UserPicker/UserPicker.html
  components/interactables/UserPicker/UserPicker.less
  components/interactables/UserPicker/UserPicker.vue
  components/views/friends/quick/Quick.html
  components/views/friends/quick/Quick.less
  components/views/group/icon/GroupIcon.less
Labels: QA tested

#3554 feat(jest): 100% coverage for store/accounts/mutations
  store/accounts/mutations.test.ts
Labels: Missing Dev Review

#3284 refactor(scrollbar): spread new scroll component
  components/interactables/Select/Select.html
  components/ui/FloatingContainer/FloatingContainer.html
  components/ui/SimpleScroll/SimpleScroll.html
  components/ui/SimpleScroll/SimpleScroll.less
  components/ui/SimpleScroll/SimpleScroll.vue
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/Editable.vue
  components/views/chat/chatbar/commands/preview/Preview.html
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/Result.less
  components/views/chat/search/result/Result.vue
  components/views/chat/search/result/ResultGlobal.less
  components/views/files/upload/filePreview/FilePreview.html
  components/views/files/upload/filePreview/FilePreview.less
  components/views/files/upload/previewItem/PreviewItem.less
  components/views/friends/mobile/list.vue
  components/views/group/aside/Aside.html
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/server/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/toolbar/pinned/Pinned.html
  components/views/settings/modal/Modal.html
  components/views/settings/pages/user/Search.html
  components/views/user/profile/Profile.html
  layouts/Layout.less
  pages/friends/list/FriendsList.html
  pages/friends/list/FriendsList.less
  pages/friends/mobile/add/index.vue
  pages/friends/mobile/block/index.vue
  pages/friends/mobile/incoming/index.vue
  pages/message/NewMessage.html
Labels: temporary blocked checking something

#3543 chore(seedPage): added copy button to seed page
  pages/setup/phrase/Phrase.html
  pages/setup/phrase/index.vue
Labels: QA tested

#3547 fix(buckets): initialize buckets separately
  libraries/Textile/TextileManager.ts
Labels: Ready for QA

#3571 chore(comment): add comment + minor lint
  components/interactables/Checkbox/Checkbox.html
  components/interactables/Checkbox/Checkbox.less
  components/interactables/UserPicker/ListItem/ListItem.html
  components/interactables/UserPicker/ListItem/ListItem.less
  components/views/navigation/toolbar/Toolbar.html
  libraries/Files/remote/textile/PersonalBucket.ts
Labels: Ready for QA

#3569 chore(jest): add jest tests
  libraries/BlockchainClient/BlockchainClient.test.ts
  libraries/BlockchainClient/__snapshots__/BlockchainClient.test.ts.snap
  libraries/BlockchainClient/adapters/EthereumAdapter/EthereumAdapter.test.ts
  libraries/BlockchainClient/adapters/EthereumAdapter/__snapshots__/EthereumAdapter.test.ts.snap
Labels: Missing Dev Review

#3573 chore(cypress): fix cypress test
  cypress/support/commands.js
Labels: Missing Dev Review

#3528 chore(cleanup): remove unused markup
  components/views/user/User.html
  components/views/user/User.vue
  locales/en-US.js
Labels: QA tested

#3490 fix(video): fix toggle video bugs, improve video unit tests
  components/views/media/actions/Actions.vue
  components/views/navigation/sidebar/controls/Controls.vue
  libraries/WebRTC/Call.ts
  store/audio/__snapshots__/mutations.test.ts.snap
  store/audio/actions.test.ts
  store/audio/actions.ts
  store/audio/mutations.test.ts
  store/audio/mutations.ts
  store/audio/types.ts
  store/video/actions.test.ts
  store/video/actions.ts
  store/video/mutations.test.ts
  store/webrtc/actions.ts
Labels: QA tested

#3574 chore(jest): add more jest tests
  libraries/WebRTC/Emitter.test.ts
  libraries/WebRTC/Libp2p.test.ts
  libraries/WebRTC/__snapshots__/Emitter.test.ts.snap
  libraries/WebRTC/__snapshots__/Libp2p.test.ts.snap
Labels: Missing Dev Review

#3575 chore(locales): update copy
  locales/en-US.js
Labels: Missing Dev Review

#3577 chore(jest): remove not used import on test
  store/video/actions.test.ts
Labels: Missing Dev Review

#3576 chore(lint): minor lint
  components/views/navigation/sidebar/controls/Controls.vue
Labels: Missing Dev Review

#3552 feat(userpicker): add chip list
  components/interactables/Chip/Chip.vue
  components/interactables/UserPicker/UserPicker.html
  components/interactables/UserPicker/UserPicker.less
  locales/en-US.js
Labels: Ready for QA

#3596 chore(jest): update jest tests
  components/views/chat/search/SearchQuery.test.ts
  components/views/chat/search/__snapshots__/SearchQuery.test.ts.snap
  libraries/BlockchainClient/adapters/SolanaAdapter/__snapshots__/utils.test.ts.snap
  libraries/BlockchainClient/adapters/SolanaAdapter/utils.test.ts
Labels: Missing Dev Review

#3556 fix(call): show avatar placeholder on incoming call
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.less
Labels: QA tested

#3606 chore(cypress): skip test
  cypress/integration/chat-features.js
Labels: Missing Dev Review

#3608 feat(chat): add message when a user adds somebody to chat
  store/groups/actions.ts
Labels: Ready for QA

#3558 fix(call): destroy call on decline incoming call
  components/ui/Global/Global.vue
Labels: QA tested

#3616 feat(jest): 80% coverage for store/ui/mutations
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#3615 feat(jest): 100% coverage for store/ui/getters
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/getters.test.ts
Labels: Missing Dev Review

#3621 feat(jest): 100% coverage for store/chat/mutations
  store/chat/mutations.test.ts
Labels: Missing Dev Review

#3620 chore(edit): hide edit message
  components/views/chat/message/Message.vue
Labels: QA tested

#3609 fix(glyphs): prevent glyph drag
  components/views/chat/enhancers/glyphs/item/Item.html
Labels: Missing Dev Review, QA tested

#3612 fix(call): add exit call sound
  store/webrtc/actions.ts
Labels: QA tested

#3622 chore(remove): remove not needed stuff
  libraries/BlockchainClient/adapters/EthereumAdapter/EthereumAdapter.test.ts
  libraries/BlockchainClient/adapters/EthereumAdapter/EthereumAdapter.ts
  libraries/BlockchainClient/adapters/EthereumAdapter/__snapshots__/EthereumAdapter.test.ts.snap
  libraries/BlockchainClient/adapters/EthereumAdapter/index.ts
Labels: QA tested

#3614 fix(call): add end call sound on caller side
  store/webrtc/actions.ts
Labels: QA tested

#3590 fix(double-requests): removed double friends requests
  assets/styles/base.less
  assets/styles/framework/colors.less
  assets/styles/framework/glows.less
  store/friends/actions.ts
  store/friends/types.ts
Labels: QA tested

#3514 refactor(scrollbar): clearing remaining components
  assets/styles/base.less
  assets/styles/framework/colors.less
  assets/styles/framework/framework.less
  assets/styles/themes/moonless_night.less
  assets/styles/thirdparty/scrollbar.less
  components/interactables/Close/Close.less
  components/interactables/UserPicker/UserPicker.html
  components/ui/ComingSoon/ComingSoon.less
  components/ui/HorizontalRule/HorizontalRule.vue
  components/ui/Scroll/Scroll.html
  components/ui/Scroll/Scroll.less
  components/ui/Scroll/Scroll.vue
  components/ui/SimpleScroll/SimpleScroll.less
  components/ui/VerticalRule/VerticalRule.vue
  components/views/marketplace/Marketplace.html
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/slimbar/Slimbar.less
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.less
  components/views/settings/pages/info/index.vue
  package.json
Labels: Ready for QA

#3551 chore(loading): removed loading screen on chat
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/views/chat/chatbar/Chatbar.html
  layouts/chat.vue
  pages/chat/direct/Direct.html
  pages/chat/direct/_address.vue
  pages/chat/groups/Group.html
Labels: QA tested

#3610 fix(profile): simplify profile, minor refactor
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/index.vue
  components/views/settings/profile/Banner.vue
  components/views/settings/profile/Picture.vue
  components/views/settings/profile/card/Card.html
Labels: Ready for QA

#3635 fix(chat): refresh crash error
  components/views/chat/group/Group.vue
Labels: Missing Dev Review

#3626 chore(reply): removed reply button from replies
  components/views/chat/message/reply/Item/Item.html
Labels: Ready for QA, temporary blocked checking something

#3637 fix(userpicker): friend name overflow
  components/interactables/UserPicker/ListItem/ListItem.html
  components/interactables/UserPicker/ListItem/ListItem.less
Labels: Ready for QA

#3642 fix(focus-chat): fixed auto focus when entering chat
  components/views/user/User.vue
Labels: Ready for QA

#3641 fix(call): fullscreen call search results z index issue
  layouts/Layout.less
Labels: Ready for QA

#3636 fix(chat): is active call logic
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
Labels: Ready for QA

#3658 feat(toolbar): add coming soon to group search input
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  locales/en-US.js
Labels: Ready for QA

#3657 fix(select): broken select rendering
  components/interactables/Select/Select.html
  components/interactables/Select/Select.less
Labels: Ready for QA

#3588 fix(quickchat): improve quickchat/sidebar css
  assets/styles/base.less
  components/views/friends/quick/Quick.html
  components/views/friends/quick/Quick.less
  components/views/friends/quick/Quick.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.vue
Labels: Ready for QA

#3585 fix(toolbar): remove secondary create group modal
  components/views/group/create/Create.html
  components/views/group/create/Create.less
  components/views/group/create/Create.vue
  components/views/navigation/toolbar/Toolbar.html
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/state.ts
  store/ui/types.ts
Labels: depending on other PR

#3673 chore(jest): fix lint errors on SearchQuery
  components/views/chat/search/SearchQuery.test.ts
Labels: Missing Dev Review

#3639 fix(account): client side validation for user creation
  components/interactables/Input/Input.vue
  components/views/user/create/Create.html
  components/views/user/create/Create.vue
  config.ts
  locales/en-US.js
Labels: Ready for QA

#3670 fix(cta): svg overflow clipping
  components/views/callToAction/CallToAction.less
Labels: QA tested

#3684 chore(cypress): add commands locally to run tests
  package.json
Labels: Missing Dev Review

#3662 fix(mobile): bottom nav bar state
  components/views/navigation/mobile/nav/Nav.html
  components/views/navigation/mobile/nav/Nav.vue
Labels: QA tested

#3685 chore(lint): minor lint
  components/interactables/UserPicker/ListItem/ListItem.html
  cypress/integration/chat-pair-features.js
Labels: Ready for QA

#3644 fix(call): add sounds for call
  components/views/media/incomingCall/IncomingCall.vue
  store/webrtc/actions.ts
Labels: QA tested

#3703 chore(update): update locale
  locales/en-US.js
Labels: Missing Dev Review

#3557 fix(onlineStatus): update peer events handlers
  store/webrtc/actions.ts
Labels: Ready for QA

#3719 fix(quick): break word
  components/views/friends/quick/Quick.less
Labels: Ready for QA

#3727 feat(jest): 46% coverage for store/chat/actions
  store/chat/actions.test.ts
Labels: Missing Dev Review

#3729 chore(cypress): update
  cypress/integration/create-account.js
Labels: Missing Dev Review

#3710 fix(sidebar): proper color on sidebar tag
  assets/styles/base.less
  components/views/navigation/sidebar/Sidebar.less
Labels: Ready for QA

#3714 fix(chat): unknown name while loading
  components/views/chat/group/Group.vue
Labels: Ready for QA

#3721 refactor(toolbar): refactor styles and increase text overflow length w/ flex
  components/views/navigation/slimbar/Slimbar.less
  components/views/navigation/toolbar/Toolbar.less
  layouts/Layout.less
Labels: Ready for QA

#3709 fix(files): remove unfinished ui
  components/views/files/aside/Aside.vue
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
Labels: Ready for QA

#3730 chore(groups): add back click action
  components/views/group/clickable/Clickable.html
Labels: Missing Dev Review

#3735 chore(cypress): add friend test
  cypress/integration/add-friend.js
Labels: Missing Dev Review

#3668 fix(chat): is_typing indicator
  components/views/chat/chatbar/Chatbar.vue
  store/conversation/actions.test.ts
  store/conversation/actions.ts
  store/webrtc/actions.ts
Labels: Ready for QA

#3686 fix(double-requests): filtered incoming requests
  store/friends/actions.ts
Labels: QA tested

#3649 fix(state): add on:discover event
  components/views/user/User.less
  store/friends/actions.ts
  store/webrtc/actions.ts
Labels: Ready for QA

#3667 fix(groupChats): add retry to invite search in group creation
  libraries/Solana/GroupChatsProgram/GroupChatsProgram.ts
  libraries/Solana/Solana.ts
Labels: QA tested

#3726 fix(userpicker): style & overflow issues
  components/interactables/Chip/Chip.vue
  components/interactables/UserPicker/UserPicker.html
  components/interactables/UserPicker/UserPicker.less
Labels: Changes Requested

#3707 fix(download): remove unnecessary local state, fix string bug
  components/views/files/view/View.vue
Labels: QA tested

#3607 feat(groupinvite): use userpicker component
  components/interactables/UserPicker/UserPicker.vue
  components/views/group/invite/Invite.html
  components/views/group/invite/Invite.less
  components/views/group/invite/Invite.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
Labels: QA tested

#3765 feat(jest): 97% coverage for store/textile/mutations
  store/textile/mutations.test.ts
Labels: Missing Dev Review

#3755 fix(mobile): mobile nav style
  assets/styles/themes/moonless_night.less
Labels: Ready for QA

#3768 chore(jest): add test
  libraries/Textile/UserManager.test.ts
Labels: Missing Dev Review

#3769 fix(satellitecircle): remove illegible light grey color
  components/ui/SatelliteCircle/SatelliteCircle.vue
Labels: Ready for QA, QA tested

#3550 fix(chat): upload rework
  assets/styles/framework/colors.less
  components/ui/Chat/Embeds/File/types.d.ts
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.less
  components/ui/Chat/Image/Image.vue
  components/ui/Chat/Image/Overlay/Overlay.html
  components/ui/Chat/Image/Overlay/Overlay.less
  components/ui/Chat/Image/Overlay/Overlay.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/commands/preview/Preview.html
  components/views/chat/enhancers/Enhancers.vue
  components/views/files/upload/Error.vue
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.vue
  components/views/files/upload/filePreview/FilePreview.html
  components/views/files/upload/filePreview/FilePreview.less
  components/views/files/upload/filePreview/FilePreview.vue
  components/views/files/upload/preview/Preview.html
  components/views/files/upload/preview/Preview.less
  components/views/files/upload/preview/Preview.vue
  components/views/files/upload/preview/item/Item.html
  components/views/files/upload/preview/item/Item.less
  components/views/files/upload/preview/item/Item.vue
  components/views/files/upload/previewItem/PreviewItem.html
  components/views/files/upload/previewItem/PreviewItem.less
  components/views/files/upload/previewItem/PreviewItem.vue
  config.ts
  layouts/chat.vue
  libraries/Files/TextileFileSystem.ts
  libraries/Textile/__snapshots__/encoders.test.ts.snap
  libraries/Textile/encoders.ts
  locales/en-US.js
  plugins/thirdparty/persist.ts
  store/chat/__snapshots__/state.test.ts.snap
  store/chat/actions.test.ts
  store/chat/actions.ts
  store/chat/getters.test.ts
  store/chat/getters.ts
  store/chat/mutations.test.ts
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
  store/conversation/getters.ts
  store/textile/__snapshots__/state.test.ts.snap
  store/textile/actions.test.ts
  store/textile/actions.ts
  store/textile/mutations.test.ts
  store/textile/mutations.ts
  store/textile/state.ts
  store/textile/types.ts
  types/chat/chat.ts
  types/files/file.ts
  utilities/Thumbnail.ts
Labels: Ready for QA

#3774 feat(jest): 100% branch coverage for store/webrtc/mutations
  store/webrtc/mutations.test.ts
Labels: Missing Dev Review

#3776 feat(jest): 19% coverage for SharedBucket
  libraries/Files/test/Bucket.test.ts
Labels: Missing Dev Review

#3331 test(cypress): add tests for videocall pair chat
  components/interactables/Volume/Volume.html
  components/ui/Loaders/Message/Message.vue
  components/views/chat/conversation/Conversation.html
  components/views/media/Media.html
  components/views/media/actions/Actions.html
  components/views/media/actions/settings/Settings.html
  components/views/media/actions/volume/Volume.html
  components/views/media/heading/Heading.html
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/user/User.html
  components/views/navigation/sidebar/controls/Controls.html
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/support/first-user/commands.js
  cypress/support/second-user/commands.js
  layouts/chat.vue
Labels: draft

#3767 fix(conversation): offline status
  plugins/thirdparty/persist.ts
Labels: Ready for QA

#3766 fix(groupchat): fix for username of unknown users during initial load
  components/views/chat/group/Group.vue
  locales/en-US.js
Labels: Ready for QA

#3781 test(cypress): updates to chat top toolbar tests
  components/views/files/upload/preview/item/Item.html
  components/views/navigation/toolbar/Toolbar.html
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-top-toolbar.js
  cypress/support/commands.js
Labels: Missing Dev Review

#3761 fix(sendmoney): disabled button prop
  components/views/chat/chatbar/controls/Controls.html
Labels: Ready for QA

#3791 feat(jest): 97% coverage for store/textile/mutations
  store/textile/mutations.test.ts
Labels: Missing Dev Review

#3680 fix(friends): online status is hidden if not friend
  components/ui/User/State/State.vue
  components/views/friends/friend/Friend.html
  components/views/friends/friend/Friend.vue
Labels: Missing Dev Review

#3797 test(cypress): improvements to avoid failure on last test
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
Labels: Ready for QA

#3790 fix(webrtc): on call track logic
  store/webrtc/actions.ts
Labels: Ready for QA

#3787 chore(store): remove unused store
  components/ui/Chat/Scroll/Scroll.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/actions.test.ts
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  store/webrtc/actions.ts
Labels: Ready for QA

#3786 fix(select): cleanup select console errors
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/index.vue
  store/audio/types.ts
Labels: Ready for QA

#3764 fix(chatbar): change chatbar z-index depend on fullscreen media
  components/views/chat/chatbar/Chatbar.less
  layouts/Layout.less
Labels: Ready for QA

#3773 chore(vscode): default imports - non relative
  .vscode/settings.json
Labels: Ready for QA

#3795 test(cypress): fixes for chat images validations
  components/ui/Chat/Image/Image.html
  cypress/integration/chat-images-validations.js
  cypress/support/commands.js
Labels: Missing Dev Review

#3796 fix(group): remove duplicated dispatch to storeInMessage action
  store/textile/actions.ts
Labels: Ready for QA

#3759 test(store): create mock root state that will automatically keep in sync
  store/getters.test.ts
  types/store/store.ts
Labels: Ready for QA

#3805 chore(changelog): update changelog
  .github/config/changelog_config.json
Labels: Missing Dev Review

#3779 feat(logs): add logs to help monitoring webrtc activities
  store/webrtc/actions.ts
Labels: QA tested

#3803 fix(textile): set peer id correctly when switching conversations
  components/views/user/User.vue
  store/textile/actions.ts
Labels: temporary blocked checking something

#3757 fix(chat): reaction buttons style and ui
  assets/styles/base.less
  components/views/chat/message/reactions/Reactions.html
  components/views/chat/message/reactions/Reactions.less
  components/views/chat/message/reactions/Reactions.vue
  locales/en-US.js
Labels: Ready for QA

#3811 chore(cypress): minor update
  cypress/integration/create-account.js
Labels: draft

#3813 test(cypress): updates on mobiles and pair tests
  components/views/settings/modal/Modal.html
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/create-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/support/commands.js
Labels: Missing Dev Review

#3814 fix(quickchat): z index fix for quickchat modal
  assets/styles/base.less
Labels: Ready for QA

#3815 feat(jest): 92% coverage for utilities/Messaging
  utilities/Messaging.test.ts
  utilities/Messaging.ts
  utilities/__snapshots__/Messaging.test.ts.snap
Labels: Missing Dev Review
