Repository Satellite-im/Core-PWA, pull requests merged in 2022-02, with the labels that each got.

#1182 fix(unit-test): add jest-canvas-mock
  jest.config.js
  package.json
  utilities/ConsoleWarning.test.ts
Labels: Ready for QA

#1173 feat(sounds): play sounds only enabled AP-415
  components/mixins/Layouts/Layout.ts
  components/views/media/Media.vue
  components/views/media/actions/Actions.vue
  components/views/media/incomingCall/IncomingCall.vue
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/settings/pages/audio/sounds/Sounds.html
  components/views/settings/pages/audio/sounds/Sounds.vue
  libraries/SoundManager/SoundManager.ts
  store/sounds/__snapshots__/state.test.ts.snap
  store/sounds/actions.ts
  store/sounds/mutations.ts
  store/sounds/state.ts
  store/sounds/types.ts
Labels: Missing Dev Review

#1179 fix(webrtc): replace setConnectedTime with updateCreatedAt
  store/webrtc/actions.ts
  store/webrtc/mutations.test.ts
  store/webrtc/mutations.ts
Labels: QA approved

#1165 fix(ui): missing components on themes
  assets/styles/base.less
  assets/styles/themes/moonless_night.less
Labels: QA approved

#1258 chore(canvas): we do not need canvas, just canvas-mock for tests
  package.json
Labels: Missing Dev Review

#1234 fix(actions): remove more option button AP-419
  components/views/chat/message/actions/Actions.html
  components/views/chat/message/actions/Actions.vue
Labels: QA approved

#1263 chore(jest): rename files
  components/mixins/Touch/__snapshots__/index.test.ts.snap
  components/mixins/Touch/index.test.ts
  components/mixins/UserPermissions/index.test.ts
Labels: Missing Dev Review, QA approved

#1264 chore(prettier): add prettierignore file
  .prettierignore
Labels: Missing Dev Review, QA approved

#1257 fix(glyph): fix some glyphs are returning 404
  mock/glyphs.ts
Labels: QA approved

#1245 fix(call): dismiss incoming call when click deny button
  components/ui/Global/Global.vue
Labels: Changes Requested

#1276 add(jest): 100% coverage for Files/Fil.ts unit test
  libraries/Files/test/Fil.test.ts
Labels: QA approved

#1267 add(jest): 100% coverage for store/ui/getters.ts
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/getters.test.ts
Labels: QA approved

#1268 add(jest): 100% coverage for Files/Directory.ts
  libraries/Files/Directory.ts
  libraries/Files/test/Directory.test.ts
Labels: QA approved

#1266 add(jest): 100% coverage for utilities/Heic.ts
  utilities/Heic.test.ts
  utilities/__snapshots__/Heic.test.ts.snap
  utilities/assets/heic-image.heic
  utilities/assets/non-heic-image.png
Labels: QA approved

#1272 fix(settings): remove unnecessary items AP-653
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/accounts/Accounts.less
  components/views/settings/pages/accounts/index.vue
  components/views/settings/pages/network/Network.html
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
Labels: QA approved

#1283 fix(settings): fix background issue on mobile
  components/views/settings/modal/Modal.less
Labels: QA approved

#1292 chore(eslint): improve eslint
  .eslintrc.js
Labels: Missing Dev Review

#1262 feat(filesPage): rework files page ui AP-603
  assets/styles/base.less
  assets/styles/framework/breakpoints.less
  components/interactables/Tabs/Tabs.less
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/chat/enhancers/glyphs/Glyphs.less
  components/views/files/aside/Aside.less
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/controls/Controls.vue
  components/views/files/file/File.html
  components/views/files/file/File.less
  components/views/files/file/File.vue
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.less
  components/views/files/grid/Grid.html
  components/views/files/grid/Grid.less
  components/views/files/grid/Grid.vue
  components/views/files/list/List.vue
  components/views/files/topbar/Topbar.html
  components/views/files/topbar/Topbar.less
  components/views/files/topbar/Topbar.vue
  components/views/files/viewSwitcher/ViewSwitcher.html
  components/views/files/viewSwitcher/ViewSwitcher.less
  components/views/files/viewSwitcher/ViewSwitcher.vue
  components/views/user/profile/Profile.less
  layouts/Layout.less
  libraries/Enums/enums.ts
  libraries/Enums/types/filesView.ts
  locales/en-US.js
  pages/files/browse/Browse.html
  pages/files/browse/Browse.less
  pages/files/browse/index.vue
Labels: Changes Requested

#1294 fix(files): fix files list view. broken guard clause
  components/views/files/list/List.vue
Labels: Missing Dev Review

#1315 chore(jest): remove not used tests
  libraries/Textile/IdentityManager.skip.ts
  utilities/EXIF.skip.ts
  utilities/Notifications.skip.ts
Labels: Missing Dev Review

#1300 add(jest): 100% coverage for store/accounts/state.ts AP-682
  store/accounts/__snapshots__/state.test.ts.snap
  store/accounts/state.test.ts
Labels: Ready for QA

#1285 fix(fullscreen): fix ui issues when fullscreen mode
  components/views/media/Media.less
  components/views/media/user/User.html
  components/views/media/user/User.less
Labels: QA approved

#1297 add(jest): 100% coverage for store/accounts/getters.ts unit test
  store/accounts/getters.test.ts
Labels: QA approved

#1296 feat(ui): implementation of layout for locked toggle
  assets/styles/base.less
  components/interactables/Switch/Switch.html
  components/interactables/Switch/Switch.less
  components/interactables/Switch/Switch.vue
  components/views/settings/pages/privacy/Privacy.html
Labels: QA approved

#1301 fix(upload): upload same file twice second preview not showing
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.vue
Labels: QA approved

#1307 fix(ui): added custom scrollbar to chatbar
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/Editable.vue
Labels: QA approved

#1181 fix(Theme): deactivate flair dropdown until selects moonless night
  components/interactables/Select/Select.less
  components/interactables/Select/Select.vue
  components/interactables/Switch/Switch.less
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/personalize/index.vue
Labels: Ready for QA

#1316 chore(jest): improve jest config
  jest.config.js
Labels: Missing Dev Review, QA approved

#1319 chore(update): remove hoarder of commented out code
  mock/users.ts
Labels: Missing Dev Review

#1320 chore(update): remove commented out code + minor updates on comments
  components/views/files/controls/Controls.vue
  components/views/files/file/File.html
  config.ts
  store/textile/actions.ts
  store/textile/mutations.ts
  types/textile/mailbox.ts
  types/ui/friends.d.ts
  utilities/Notifications.ts
Labels: Missing Dev Review

#1269 feat(live): add active and close chat for live component AP-538
  components/views/media/actions/volume/Volume.vue
  components/views/navigation/sidebar/live/Live.html
  components/views/navigation/sidebar/live/Live.less
  components/views/navigation/sidebar/live/Live.vue
Labels: QA approved

#1270 feat(user): fix timestamp for user list AP-118
  components/views/user/User.html
  components/views/user/User.vue
Labels: QA approved

#1332 update(jest): add coverage for libraries/Files/FileSystem.ts
  libraries/Files/test/FileSystem.test.ts
Labels: QA approved

#1271 feat(user): hide the users have no any message AP-116
  components/views/user/User.html
  components/views/user/User.vue
Labels: missing fixing conflict

#1325 fix(search): fix ui issues in search result
  components/interactables/Search/Result/Result.less
Labels: QA approved

#1331 add(jest): 100% coverage for utilities/HotkeyList.ts unit test
  utilities/HotkeyList.test.ts
  utilities/__snapshots__/HotkeyList.test.ts.snap
Labels: Missing Dev Review, QA approved

#1336 chore(lint): minor lint
  package.json
Labels: Missing Dev Review, QA approved

#1342 fix(ui): update locale on settings/profile
  components/views/settings/profile/card/Card.html
  locales/en-US.js
Labels: QA approved

#1327 fix(image-cropper): update image cropper on sign up page
  components/interactables/ImageCropper/ImageCropper.vue
  config.ts
Labels: Ready for QA

#1346 fix(chatbar): fix typing indicator, minor eslint updates
  components/views/chat/chatbar/Chatbar.vue
  libraries/ui/Commands.ts
Labels: Missing Dev Review, QA approved

#1354 fix(jest): resolve/fix/supress eslint errors and warnings
  libraries/Crypto/Crypto.test.ts
  libraries/Solana/FriendsProgram/FriendsProgram.layout.test.ts
  libraries/Solana/FriendsProgram/__snapshots__/FriendsProgram.layout.test.ts.snap
  libraries/Solana/ServerProgram/ServerProgram.layout.test.ts
  utilities/Logger.test.ts
  utilities/__snapshots__/io-ts.test.ts.snap
  utilities/io-ts.test.ts
Labels: QA approved, missing fixing conflict

#1384 chore(jest): delete test
  store/settings/__snapshots__/state.test.ts.snap
  store/settings/state.test.ts
Labels: Missing Dev Review

#1387 add(jest): 100% code coverage for store/settings/state.test.ts
  store/settings/state.test.ts
Labels: QA approved

#1357 fix(ui): redirect to add friend when no friends
  pages/chat/direct/_address.vue
Labels: QA approved

#1378 add(jest): 100% code coverage for TracksManager.test.ts
  libraries/WebRTC/TracksManager.test.ts
  libraries/WebRTC/TracksManager.ts
Labels: QA approved

#1358 fix(ui): fix user code cut off on settings > personalize
  components/ui/Breadcrumbs/Breadcrumbs.less
Labels: QA approved

#1381 add(jest): 100% code coverage for settings/pages/audio/options
  components/views/settings/pages/audio/options/__snapshots__/index.test.ts.snap
  components/views/settings/pages/audio/options/index.test.ts
Labels: QA approved

#1364 fix(quick-profile): fix 'x' mark style issues on popup
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.less
Labels: QA approved

#1390 fix(TextileManager): remove duplicated initialization AP-723
  libraries/Textile/TextileManager.ts
Labels: QA approved

#1396 add(jest): 100% code coverage for Friends.test.ts unit test
  libraries/ui/Friends.test.ts
  libraries/ui/__snapshots__/Friends.test.ts.snap
Labels: QA approved

#1406 feat(settings): add clearLocalStorage action
  components/views/settings/pages/storage/Storage.html
  components/views/settings/pages/storage/index.vue
  locales/en-US.js
  store/settings/actions.ts
  store/settings/types.ts
Labels: Changes Requested

#1423 chore(lint): minor linting
  components/views/settings/pages/storage/Storage.html
  components/views/settings/profile/card/Card.html
Labels: Missing Dev Review

#1436 fix(result): modify search library response to include everything the UI will need AP-707
  components/interactables/Search/Result/Result.less
  components/interactables/Search/Result/Result.vue
  libraries/IndexedDB/index.ts
  types/ui/query.d.ts
Labels: Missing Dev Review

#1382 fix(chat): increase drop field for image upload
  components/ui/DroppableWrapper/DroppableWrapper.html
  components/ui/DroppableWrapper/DroppableWrapper.less
  components/ui/DroppableWrapper/DroppableWrapper.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/Enhancers.vue
  components/views/wallet/mini/Mini.less
  components/views/wallet/mini/Mini.vue
  layouts/chat.vue
Labels: QA approved

#1435 fix(ui): fix padding issue on importAccount page
  components/typography/NumberedWord/NumberedWord.less
  pages/setup/ImportAccount/ImportAccount.less
Labels: Missing Dev Review, QA approved

#1291 feat(groupChatManager): create a groupChat manager to create separate collections on a thread
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/conversation/Conversation.vue
  components/views/group/Group.vue
  components/views/group/aside/Aside.html
  components/views/group/aside/Aside.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  config.ts
  layouts/chat.vue
  libraries/Textile/GroupChatManager.ts
  libraries/Textile/TextileManager.ts
  libraries/Textile/schema.ts
  libraries/WebRTC/Wire.ts
  mock/groups.ts
  pages/chat/groups/Group.html
  pages/chat/groups/_id.vue
  store/textile/actions.ts
  store/textile/mutations.ts
Labels: QA approved

#1414 fix(search): fix search option issues on iOS
  components/interactables/Search/Input/Input.less
Labels: QA approved

#1450 fix(search): prevent crashing for search options
  libraries/IndexedDB/index.ts
Labels: Ready for QA

#1427 add(jest): 100% code coverage for Timezone.test.ts unit test AP-754
  utilities/Timezone.test.ts
  utilities/__snapshots__/Timezone.test.ts.snap
Labels: QA approved

#1383 chore: remove old libraries and minor ui fixes AP-308 AP-514
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/Editable.vue
  components/views/chat/chatbar/commands/preview/Preview.less
  components/views/chat/chatbar/commands/preview/Preview.vue
  components/views/chat/chatbar/reply/Reply.html
  components/views/chat/chatbar/reply/Reply.vue
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/message/Markdown.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/edit/Edit.less
  components/views/chat/message/edit/Edit.vue
  components/views/chat/message/reply/Reply.html
  components/views/chat/message/reply/Reply.vue
  components/views/marketplace/glyphs/trending/item/Item.html
  layouts/chat.vue
  libraries/ui/Chatbar.test.ts
  libraries/ui/Chatbar.ts
  libraries/ui/Markdown.ts
  libraries/ui/__snapshots__/Chatbar.test.ts.snap
  package.json
  plugins/thirdparty/persist.ts
  store/chat/__snapshots__/mutations.test.ts.snap
  store/chat/actions.ts
  store/chat/mutations.test.ts
  store/chat/mutations.ts
  store/ui/actions.ts
Labels: Ready for QA

#1420 feat(chatImageUpload): have images persist in each chat
  components/views/files/upload/Upload.vue
Labels: Ready for QA

#1459 fix(MessageGroup): fix group picture when friend is not found
  components/views/chat/group/Group.vue
Labels: Ready for QA

#1448 fix(search): fix search results ui on mobile
  components/interactables/Search/Result/Result.less
Labels: QA approved

#1434 fix(ui): fix mobile bottom padding cut off on settings modal
  components/views/settings/modal/Modal.less
Labels: QA approved

#1461 chore(update): minor updates
  components/ui/Global/Global.vue
  components/ui/UpdateModal/UpdateModal.vue
  components/views/chat/conversation/Conversation.less
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/toolbar/Toolbar.vue
  components/views/navigation/toolbar/alerts/Alerts.vue
  components/views/settings/pages/notifications/index.vue
  libraries/IndexedDB/index.ts
  libraries/Textile/BucketManager.ts
  libraries/Textile/IdentityManager.ts
  libraries/Textile/MailboxManager.ts
  libraries/Textile/encoders.test.ts
  libraries/ui/Alerts.test.ts
  pages/generic/loading/index.vue
  pages/server/chat/index.vue
  store/prerequisites/actions.ts
  store/settings/state.test.ts
  store/textile/getters.test.ts
  utilities/Heic.ts
  utilities/Notifications.ts
Labels: Ready for QA

#1472 test(jest): add Cursor.ts test
  libraries/ui/Cursor.test.ts
  libraries/ui/__snapshots__/Cursor.test.ts.snap
Labels: Missing Dev Review

#1471 add(jest): add tests BucketManager + GroupChatManager
  libraries/Textile/BucketManager.test.ts
  libraries/Textile/GroupChatManager.test.ts
  libraries/Textile/__snapshots__/BucketManager.test.ts.snap
  libraries/Textile/__snapshots__/GroupChatManager.test.ts.snap
Labels: Missing Dev Review

#1473 test(jest): remove not needed imports + minor lint
  libraries/Solana/FriendsProgram/FriendsProgram.layout.test.ts
  libraries/Solana/ServerProgram/ServerProgram.layout.test.ts
  libraries/Solana/Solana.test.ts
  libraries/SoundManager/SolanaManager.test.ts
  libraries/Textile/Utils.test.ts
  libraries/ui/Commands.test.ts
  libraries/ui/Friends.test.ts
  store/audio/actions.test.ts
  store/audio/mutations.test.ts
  store/audio/state.test.ts
  store/chat/mutations.test.ts
  store/chat/state.test.ts
  store/dataState/state.test.ts
  store/files/actions.test.ts
  store/files/mutations.test.ts
  store/files/state.test.ts
  store/media/actions.test.ts
  store/prerequisites/getters.test.ts
  store/prerequisites/mutations.test.ts
  store/prerequisites/state.test.ts
  store/search/mutations.test.ts
  store/search/state.test.ts
  store/settings/mutations.test.ts
  store/video/mutations.test.ts
  store/video/state.test.ts
  utilities/ConsoleWarning.test.ts
  utilities/Messaging.test.ts
  utilities/SimpleWrap.test.ts
  utilities/io-ts.test.ts
Labels: Missing Dev Review

#1474 test(jest): add jest test - store/ui/mutations.test.ts
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#1481 feat(jest): 100% code coverage for store/media/actions.test.ts
  store/media/actions.test.ts
Labels: Missing Dev Review

#1487 chore(typo): fix typo
  store/friends/mutations.ts
Labels: Ready for QA

#1480 feat(outgoingFriends): alpha sort to outgoing friends AP-713
  pages/friends/list/FriendsList.html
  pages/friends/list/index.vue
  types/ui/friends.d.ts
Labels: QA approved

#1330 feat(footer): connected indicator added under chatbar (AP-356)
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/footer/Footer.html
  components/views/chat/chatbar/footer/Footer.less
  components/views/chat/chatbar/footer/Footer.vue
  components/views/chat/chatbar/footer/is-connected/Connected.html
  components/views/chat/chatbar/footer/is-connected/Connected.less
  components/views/chat/chatbar/footer/is-connected/Connected.vue
  locales/en-US.js
Labels: Changes Requested

#1496 update(jest): patch lint errors and warnings
  components/interactables/Search/SearchQuery.test.ts
  libraries/Textile/BucketManager.test.ts
Labels: Missing Dev Review

#1495 fix(search): fix "x" in search bar is cutoff
  components/interactables/Search/Input/Input.less
Labels: Missing Dev Review, QA approved

#1497 feat(jest): investigate testing issue, improving arguments
  components/interactables/Search/SearchQuery.test.ts
  components/interactables/Search/__snapshots__/SearchQuery.test.ts.snap
Labels: Missing Dev Review

#1501 fix(mobile): minimize keyboard when swipe sidebar
  layouts/chat.vue
Labels: QA approved

#1507 chore(cypress): update numTestsKeptInMemory value
  cypress.json
Labels: Missing Dev Review

#1510 feat(jest): 100% coverage for libraries/ui/ReleaseNotes.ts
  libraries/ui/ReleaseNotes.test.ts
  libraries/ui/ReleaseNotes.ts
  package.json
Labels: Ready for QA

#1512 feat(jest): 100% coverage for store/files/actions.ts
  store/files/actions.test.ts
Labels: Changes Requested

#1530 fix(jest): Patch daylight saving timezone issue
  utilities/Timezone.test.ts
  utilities/__snapshots__/Timezone.test.ts.snap
Labels: Missing Dev Review, QA approved

#1523 chore(cypress): update cypress version
  package.json
Labels: Missing Dev Review

#1533 feat(jest): 100% coverage for store/textile/mutations.ts
  store/textile/mutations.test.ts
Labels: Missing Dev Review

#1539 chore(chatbar): chatbar selection and emoji insertion AP-809
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/Editable.vue
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/message/Message.less
  layouts/chat.vue
Labels: Ready for QA

#1536 chore(comingSoon): coming soon component soon to be added
  components/ui/ComingSoon/ComingSoon.html
  components/ui/ComingSoon/ComingSoon.less
  components/ui/ComingSoon/ComingSoon.vue
  components/views/chat/chatbar/controls/Controls.html
  components/views/navigation/slimbar/Slimbar.html
  components/views/settings/pages/audio/Audio.html
  locales/en-US.js
  package.json
Labels: Missing Dev Review, QA approved

#1552 chore(lint): minor lint
  components/views/friends/quick/Quick.html
  components/views/friends/quick/Quick.less
  components/views/user/User.html
Labels: Missing Dev Review

#1576 feat(jest): 100% coverage for libraries/Security/Security.ts
  libraries/Security/Security.test.ts
Labels: Missing Dev Review, QA approved

#1561 fix(chat): fix focus issue on chatbar
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/Editable.vue
Labels: Ready for QA

#1569 fix(chat): cut off hover on the coming soon
  components/ui/ComingSoon/ComingSoon.html
  components/ui/ComingSoon/ComingSoon.less
Labels: QA approved

#1573 feat(jest): 100% coverage for components/mixins/Touch
  components/mixins/Touch/__snapshots__/index.test.ts.snap
  components/mixins/Touch/index.test.ts
Labels: QA approved

#1559 fix(imageUpload): fixes uploaded images being added to the wrong chat when changing during NSFW check
  components/views/files/upload/Upload.vue
Labels: Ready for QA

#1594 feat(jest): 100% coverage for mock/tests/glyph.test.ts
  mock/tests/__snapshots__/glyphs.test.ts.snap
  mock/tests/glyphs.test.ts
Labels: Missing Dev Review, QA approved

#1578 chore(media): when a track is found, called one stops blinking
  components/views/media/Media.html
  components/views/media/Media.vue
  layouts/Layout.less
Labels: QA approved

#1595 feat(jest): 100% coverage for mock/tests/friends.test.ts
  mock/tests/__snapshots__/friends.test.ts.snap
  mock/tests/friends.test.ts
Labels: Missing Dev Review, QA approved

#1563 fix(timezone): fix timezone cut issues on mobile
  components/views/settings/profile/card/Card.less
Labels: Ready for QA

#1562 fix(dropdown): fix cursor for disabled dropdown
  assets/styles/base.less
Labels: Ready for QA

#1593 feat(jest): 54% coverage for libraries/Files/remote/textile/Bucket
  libraries/Files/test/Bucket.test.ts
Labels: Missing Dev Review, QA approved

#1603 chore(jest): minor lint
  libraries/Solana/ServerProgram/ServerProgram.test.ts
Labels: Missing Dev Review

#1535 feat(groupchatsProgram): create a class to interact with the group chat program
  config.ts
  libraries/Solana/GroupchatsProgram/GroupchatsProgram.ts
  libraries/Solana/GroupchatsProgram/GroupchatsProgram.types.ts
  nuxt.config.js
  package.json
  tsconfig.json
Labels: QA approved

#1597 fix(chat): show toast with error of permissions instead of app crash
  components/ui/Global/Global.vue
  components/views/navigation/toolbar/Toolbar.vue
  libraries/WebRTC/Call.ts
  locales/en-US.js
Labels: Ready for QA

#1604 chore(jest): delete test
  utilities/Timezone.test.ts
Labels: Missing Dev Review

#1596 feat(jest): 88% coverage for store/ui/actions.ts
  store/ui/actions.test.ts
Labels: Ready for QA

#1606 chore(update): hide scan qr friend code
  components/views/friends/add/Add.html
  components/views/friends/add/Add.vue
Labels: Ready for QA

#1607 chore(update): hide language section on profile
  components/views/settings/profile/card/Card.html
  components/views/settings/profile/card/Card.vue
Labels: Ready for QA

#1617 fix(friends): fix friends.all title issue on mobile device
  locales/en-US.js
Labels: QA approved

#1608 chore(update): hide capture mouse section
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/index.vue
Labels: Ready for QA

#1609 chore(update): hides transaction fee limit
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/accounts/index.vue
Labels: Ready for QA

#1655 chore(jest): remove test
  store/files/__snapshots__/actions.test.ts.snap
  store/files/actions.test.ts
Labels: Missing Dev Review

#1621 feat(jest): 100% coverage for mock/tests/groups.test.ts
  mock/tests/__snapshots__/groups.test.ts.snap
  mock/tests/groups.test.ts
Labels: Missing Dev Review, QA approved

#1610 chore(update): hide export storage button
  components/views/settings/pages/storage/Storage.html
  components/views/settings/pages/storage/index.vue
Labels: Ready for QA

#1613 chore(update): hide pin icon on chat
  components/views/chat/message/actions/Actions.html
  components/views/chat/message/actions/Actions.vue
Labels: QA approved

#1611 chore(update): hide mock and tweak section
  components/views/settings/Sidebar.vue
Labels: Ready for QA

#1667 fix(ui): ui issue in archived message
  components/views/chat/message/Message.less
Labels: QA approved

#1619 fix(webrtc): changed beforeUnmount regression to beforeDestroy
  components/views/media/incomingCall/IncomingCall.vue
Labels: Missing Dev Review, QA approved

#1672 chore(update): hide title subtitle profile
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/index.vue
Labels: Missing Dev Review

#1678 feat(jest): 80% coverage for store/ui/mutations
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/mutations.test.ts
Labels: QA approved

#1675 feat(jest): add back store/files/actions unit test
  store/files/__snapshots__/actions.test.ts.snap
  store/files/actions.test.ts
  store/files/actions.ts
Labels: QA approved

#1612 chore(update): hides notification section
  components/views/settings/Sidebar.vue
Labels: Missing Dev Review, QA approved

#1490 fix(sidebar): change the add button position AP-674
  assets/styles/base.less
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/slimbar/Slimbar.html
Labels: QA approved

#1684 chore(jest): fix lint error and warnings
  libraries/Crypto/Crypto.test.ts
  libraries/Solana/ServerProgram/ServerProgram.test.ts
  libraries/SoundManager/SolanaManager.test.ts
  libraries/Textile/TextileManager.test.ts
Labels: Missing Dev Review, QA approved

#1683 feat(jest): 100% coverage for mock/messages.ts
  mock/tests/__snapshots__/messages.test.ts.snap
  mock/tests/messages.test.ts
Labels: Missing Dev Review, QA approved

#1689 feat(jest): 100% coverage for store/sounds/actions
  store/sounds/__snapshots__/actions.test.ts.snap
  store/sounds/actions.test.ts
Labels: Ready for QA

#1687 feat(jest): 42% coverage for libraries/IndexedDB AP-892
  libraries/IndexedDB/index.test.ts
Labels: Missing Dev Review

#1685 chore(yarn): move mock dependencies to devDependency
  package.json
Labels: Ready for QA

#1673 feat(global): routes to user when accepting call
  components/ui/Global/Global.vue
Labels: QA approved, temporary blocked checking something

#1511 feat(user program): updated the app to use the new user program
  components/views/chat/chatbar/Chatbar.html
  components/views/files/controls/Controls.vue
  components/views/files/file/File.vue
  components/views/files/view/View.vue
  components/views/friends/add/Add.vue
  config.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/remote/textile/Bucket.ts
  libraries/Files/test/Bucket.test.ts
  libraries/Solana/FriendsProgram/FriendsProgram.ts
  libraries/Solana/UsersProgram/UsersProgram.ts
  libraries/Solana/UsersProgram/UsersProgram.types.ts
  libraries/Textile/TextileManager.ts
  middleware/authenticated.ts
  pages/auth/register/Register.html
  pages/auth/register/index.vue
  pages/auth/unlock/index.vue
  pages/generic/loading/Loading.html
  pages/generic/loading/Loading.less
  pages/generic/loading/index.vue
  pages/index.vue
  plugins/local/classLoader.ts
  plugins/thirdparty/persist.ts
  store/accounts/__snapshots__/state.test.ts.snap
  store/accounts/actions.ts
  store/accounts/mutations.ts
  store/accounts/state.ts
  store/accounts/types.ts
  store/friends/actions.ts
  store/getters.ts
  store/prerequisites/Readme.md
  store/prerequisites/__snapshots__/getters.test.ts.snap
  store/prerequisites/__snapshots__/mutations.test.ts.snap
  store/prerequisites/__snapshots__/state.test.ts.snap
  store/prerequisites/actions.test.ts
  store/prerequisites/actions.ts
  store/prerequisites/getters.test.ts
  store/prerequisites/getters.ts
  store/prerequisites/mutations.test.ts
  store/prerequisites/mutations.ts
  store/prerequisites/state.test.ts
  store/prerequisites/state.ts
  store/prerequisites/types.ts
  store/textile/actions.ts
  store/ui/actions.test.ts
  store/ui/mutations.test.ts
  store/webrtc/actions.ts
  types/store/store.ts
  types/ui/friends.d.ts
  utilities/Hounddog.test.ts
Labels: QA approved

#1697 fix(chat): when entering to 'chat/direct', fix crash
  components/views/files/upload/Upload.vue
Labels: QA approved

#1677 feat(ui): change the breadcrumbs on settings modal
  components/views/settings/Sidebar.vue
  components/views/settings/breadcrumbs/Breadcrumbs.html
  components/views/settings/breadcrumbs/Breadcrumbs.less
  components/views/settings/breadcrumbs/Breadcrumbs.vue
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.vue
  store/ui/types.ts
Labels: QA approved

#1750 feat(jest): kickstart unit test for store/textile/actions
  store/textile/actions.test.ts
Labels: Missing Dev Review

#1720 fix(emoji): fix 'clicking in and out of emoji's/glyphs will cause menu to disappear'
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
Labels: Ready for QA
