Repository Satellite-im/Core-PWA, pull requests merged in 2022-08, with the labels that each got.

#4100 fix(files): adjust layout for better ux
  components/ui/ContextMenu/ContextMenu.vue
  components/views/files/aside/Aside.html
  components/views/files/aside/List/List.html
  components/views/files/aside/List/List.less
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/controls/Controls.vue
  components/views/files/filepath/Filepath.less
  components/views/files/mobileList/mobileList.html
  components/views/files/mobileList/mobileList.less
  components/views/files/mobileList/mobileList.vue
  pages/files/Files.html
  pages/files/Files.less
  pages/files/index.vue
Labels: Missing Dev Review

#4101 feat(chat): sort sidebar items
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/List.vue
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4103 fix(images): implement checkered background for transparent images
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.less
  components/ui/Chat/Image/Overlay/Overlay.html
  components/ui/Chat/Image/Overlay/Overlay.less
  components/ui/ImageContainer/ImageContainer.vue
  components/views/chat/chatbar/upload/preview/item/Item.html
  components/views/chat/chatbar/upload/preview/item/Item.less
  components/views/files/grid/item/Item.html
  components/views/files/grid/item/Item.less
  components/views/files/grid/item/Item.vue
  components/views/files/mobileList/item/Item.html
  components/views/files/mobileList/item/Item.less
  components/views/files/view/View.html
  components/views/files/view/View.less
Labels: Changes Requested

#4107 fix(friends): improve layout styles for desktop view
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/friends/add/Add.html
  components/views/friends/add/Add.less
  components/views/friends/add/Add.vue
  pages/friends/Friends.html
  pages/friends/Friends.less
  pages/friends/index.vue
Labels: Missing Dev Review

#4105 fix(settings): improve settings modal styles, remove old swiper package
  components/interactables/AsideMenu/AsideMenu.less
  components/typography/NumberedWord/NumberedWord.less
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.less
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/info/Developer.html
  components/views/settings/pages/network/Network.html
  components/views/settings/pages/realms/Realms.html
  components/views/settings/pages/storage/Storage.html
  package.json
Labels: Missing Dev Review

#4116 fix(chat): adjust screen responsiveness for menus and modals in chat
  components/interactables/ContextMenu/ContextMenu.html
  components/ui/ContextMenu/ContextMenu.vue
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/files/mobileList/item/Item.vue
Labels: Missing Dev Review

#4111 feat(mobile): add settings mobile page with swiper functionality
  assets/styles/base.less
  components/interactables/AsideMenu/AsideMenu.html
  components/interactables/AsideMenu/AsideMenu.less
  components/interactables/AsideMenu/AsideMenu.vue
  components/interactables/AsideMenu/Readme.md
  components/interactables/QuickProfile/QuickProfile.vue
  components/ui/BackgroundCall/BackgroundCall.vue
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/views/navigation/mobile/nav/Nav.html
  components/views/navigation/slimbar/Slimbar.html
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.vue
  components/views/settings/page/Page.less
  components/views/settings/pages/keybinds/Keybinds.less
  layouts/mobile.vue
  pages/mobile/chat/_id.vue
  pages/mobile/settings/index.vue
  plugins/thirdparty/persist.ts
  store/settings/__snapshots__/mutations.test.ts.snap
  store/settings/mutations.test.ts
  store/settings/mutations.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/actions.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Missing Dev Review, iridium-dev

#4123 feat(group-manager): create manager to handle iridium user data
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/users/UsersManager.ts
  libraries/Iridium/users/types.ts
Labels: Missing Dev Review

#4127 fix(files): stop all items sharing the same file from being deleted a…
  libraries/Iridium/files/FilesManager.ts
Labels: Missing Dev Review

#4129 feat(chat): start conversation scroll at bottom
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
Labels: Missing Dev Review

#4126 feat(iridium): add member to group
  components/views/group/invite/Invite.less
  components/views/group/invite/Invite.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/groups/types.ts
  store/ui/types.ts
Labels: Missing Dev Review

#4125 fix(files): resolve duplicate id issue
  components/views/files/aside/Aside.less
  components/views/files/grid/Grid.html
  components/views/files/list/List.html
  components/views/files/mobileList/mobileList.html
  pages/files/Files.less
Labels: Missing Dev Review

#4131 feat(mobile): friends page
  components/views/friends/mobile/List.vue
  components/views/friends/mobile/ListItem.vue
  components/views/friends/mobile/RequestList.vue
  components/views/navigation/mobile/nav/Nav.html
  components/views/navigation/sidebar/list/List.vue
  locales/en-US.js
  pages/auth/register/index.vue
  pages/friends/mobile/add/index.vue
  pages/friends/mobile/block/index.vue
  pages/friends/mobile/incoming/index.vue
  pages/index.vue
  pages/mobile/chat/_id.vue
  pages/mobile/friends/index.vue
Labels: Missing Dev Review, iridium-dev

#4134 feat(chat): connect infinite scroll
  components/ui/Chat/InfiniteScroll/InfiniteScroll.html
  components/ui/Chat/InfiniteScroll/InfiniteScroll.less
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review

#4135 fix(chatbar): load draft content on mount
  components/views/chat/chatbar/Chatbar.vue
Labels: Missing Dev Review

#4137 feat(chat): render and store incoming messages
  components/views/chat/conversation/Conversation.vue
  components/views/navigation/sidebar/list/List.vue
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4144 feat(friends): build 'add friend' functionality for mobile
  components/views/friends/add/Add.html
  components/views/friends/add/Add.less
  components/views/friends/add/Add.vue
  components/views/friends/friend/Friend.less
  components/views/friends/qrSection/QrSection.vue
  components/views/friends/search/Search.vue
  locales/en-US.js
  pages/friends/Friends.html
  pages/friends/Friends.less
  pages/mobile/friends/index.vue
Labels: Missing Dev Review

#4148 refactor(types): create global type for component size and font config
  assets/styles/framework/typography.less
  components/typography/Text.vue
  types/typography.d.ts
Labels: Missing Dev Review

#4112 fix(buttons): fixed loader on friends cards
  assets/styles/base.less
  assets/styles/framework/animations.less
  components/interactables/Button/Button.html
  components/interactables/Button/Button.vue
  components/interactables/Button/README.md
  components/ui/Loaders/LoadingBar/LoadingBar.vue
  components/views/friends/friend/Friend.html
  components/views/media/actions/Actions.html
  components/views/navigation/sidebar/controls/Controls.html
Labels: Missing Dev Review, iridium-dev

#4161 feat(friends): implement accept/reject friend requests for mobile
  components/views/friends/friend/Friend.vue
  components/views/friends/mobile/ListItem.vue
Labels: Missing Dev Review, iridium-dev

#4162 fix(friends): reactivity when adding friends
  components/interactables/UserPicker/UserPicker.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
Labels: Missing Dev Review

#4164 fix(friends): remove conversation attached to friend
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
Labels: Missing Dev Review

#4146 feat(interactables): clean up input components
  assets/styles/base.less
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/interactables/Input/Input.vue
  components/interactables/Input/README.md
  components/interactables/Input/types.d.ts
  components/interactables/InputGroup/InputGroup.html
  components/interactables/InputGroup/InputGroup.less
  components/interactables/InputGroup/InputGroup.vue
  components/interactables/InputGroup/README.md
  components/interactables/InputGroup/types.d.ts
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/UserPicker/UserPicker.html
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/files/controls/Controls.html
  components/views/files/rename/Rename.html
  components/views/friends/search/Search.vue
  components/views/marketplace/searchbox/Searchbox.html
  components/views/navigation/server/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/quick/Quick.html
  components/views/servers/create/Create.html
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/developer/Info.html
  components/views/settings/pages/notifications/Notifications.html
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/profile/Profile.html
  components/views/wallet/balance/Balance.html
  components/views/wallet/mini/body/Body.html
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/index.vue
  pages/components.vue
  pages/message/NewMessage.html
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review, iridium-dev

#4170 fix(friends): request reactivity issues
  components/interactables/UserPicker/UserPicker.vue
  components/views/navigation/sidebar/Sidebar.vue
  libraries/Iridium/friends/FriendsManager.ts
  pages/friends/index.vue
Labels: Missing Dev Review

#4173 fix(message): reaction reactivity
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4172 refactor: glyph messages
  assets/styles/base.less
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/emoji/Emoji.html
  components/views/chat/enhancers/emoji/Emoji.less
  components/views/chat/enhancers/emoji/Emoji.vue
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/chat/enhancers/glyphs/Glyphs.less
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/chat/enhancers/glyphs/nav/Nav.less
  components/views/chat/enhancers/glyphs/pack/Pack.less
  components/views/chat/message/Message.html
  components/views/chat/message/actions/Actions.html
  components/views/chat/message/glyph/Glyph.html
  components/views/chat/message/glyph/Glyph.vue
  components/views/glyphs/Glyphs.html
  components/views/glyphs/Glyphs.vue
  cypress/fixtures/images/incorrect-image.png
  libraries/Iridium/chat/types.ts
  locales/en-US.js
  mock/glyphs.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Missing Dev Review

#4167 fix(groups): reactivity issue for group creation
  components/ui/GroupIcon/GroupIcon.html
  components/ui/GroupIcon/GroupIcon.less
  components/views/group/invite/Invite.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/settings/modal/Modal.vue
  libraries/Iridium/groups/GroupManager.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/state.ts
  store/ui/types.ts
Labels: Missing Dev Review

#4176 feat(friends): add tabs for desktop view
  components/interactables/Tabs/Tabs.html
  components/interactables/Tabs/Tabs.less
  components/views/friends/add/Add.html
  components/views/friends/emptyMessage/EmptyMessage.vue
  components/views/friends/nav/Nav.html
  components/views/friends/nav/Nav.less
  components/views/friends/nav/Nav.vue
  components/views/friends/qrSection/QrSection.vue
  components/views/friends/requests/Requests.vue
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/List.less
  components/views/navigation/sidebar/list/List.vue
  components/views/user/profile/Profile.html
  locales/en-US.js
  pages/friends/Friends.html
  pages/friends/Friends.less
  pages/friends/index.vue
  store/friends/__snapshots__/state.test.ts.snap
  store/friends/mutations.ts
  store/friends/state.ts
  store/friends/types.ts
  types/ui/tab.d.ts
Labels: Missing Dev Review

#4171 refactor(styles): remove bulma, add css reset
  assets/styles/base.less
  assets/styles/framework/blurs.less
  assets/styles/framework/colors.less
  assets/styles/framework/ui.less
  assets/styles/reset.css
  components/interactables/Button/Button.html
  components/interactables/Button/Button.less
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/typography/Subtitle/Subtitle.less
  components/typography/Title/Title.less
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/ui/Modal/Modal.html
  components/ui/Modal/Modal.less
  components/ui/Modal/Modal.vue
  components/views/callToAction/CallToAction.less
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.less
  components/views/files/grid/item/Item.less
  components/views/files/mobileList/item/Item.less
  components/views/navigation/sidebar/status/Status.less
  components/views/navigation/slimbar/Slimbar.less
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.less
  components/views/settings/modal/Modal.vue
  layouts/default.vue
  nuxt.config.js
  package.json
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/Unlock.less
  pages/setup/phrase/Phrase.html
  pages/setup/phrase/Phrase.less
Labels: Missing Dev Review

#4181 fix: remove nested scroll
  pages/friends/Friends.html
  pages/friends/Friends.less
Labels: Missing Dev Review

#4186 fix(modal): modal animation
  assets/styles/framework/glows.less
  components/ui/Modal/Modal.less
Labels: Missing Dev Review

#4199 chore: restored friends state logic
  components/ui/BackgroundCall/BackgroundCall.vue
  components/views/chat/chatbar/Chatbar.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/sidebar/live/Live.vue
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review

#4200 chore(jest): fix jest
  .github/workflows/run-jest-tests.yml
Labels: draft

#4202 Revert "chore: restored friends state logic"
  components/ui/BackgroundCall/BackgroundCall.vue
  components/views/chat/chatbar/Chatbar.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/sidebar/live/Live.vue
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review

#4197 fix(files): re-align table list icons
  components/views/files/list/List.less
  components/views/files/list/row/Row.less
  components/views/friends/emptyMessage/EmptyMessage.vue
Labels: Missing Dev Review

#4204 fix(styles): adjust styles that used bulma
  assets/styles/framework/ui.less
  components/interactables/SidebarToggle/SidebarToggle.vue
  components/ui/Modal/Modal.less
  components/views/callToAction/CallToAction.less
  components/views/files/aside/List/List.html
  components/views/files/aside/List/List.less
  components/views/friends/requests/Requests.vue
  components/views/friends/requests/emptyMessage/EmptyMessage.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/profile/accounts/Accounts.vue
  pages/friends/Friends.less
  pages/mobile/friends/index.vue
  pages/mobile/settings/index.vue
Labels: Missing Dev Review

#4205 refactor(interactables): button
  components/interactables/Button/Button.html
  components/interactables/Button/Button.less
  components/interactables/Button/Button.vue
  components/interactables/Button/types.d.ts
  components/interactables/ButtonGroup/ButtonGroup.less
  components/interactables/ButtonGroup/ButtonGroup.vue
  components/interactables/ImageCropper/ImageCropper.html
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/interactables/KeybindInput/KeybindInput.html
  components/ui/GlowingCursorArea/GlowingCursorArea.html
  components/ui/GlowingCursorArea/GlowingCursorArea.less
  components/ui/GlowingCursorArea/GlowingCursorArea.vue
  components/ui/Popups/ErrorNetwork/ErrorNetwork.html
  components/ui/UpdateModal/UpdateModal.html
  components/views/callToAction/CallToAction.html
  components/views/chat/enhancers/Enhancers.html
  components/views/files/aside/Aside.html
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/friends/emptyMessage/EmptyMessage.vue
  components/views/friends/friend/Friend.html
  components/views/friends/friend/Friend.less
  components/views/friends/qrSection/QrSection.vue
  components/views/glyphs/Glyphs.html
  components/views/group/invite/Invite.html
  components/views/marketplace/Marketplace.html
  components/views/marketplace/glyphs/detail/Detail.html
  components/views/marketplace/glyphs/featured/Featured.html
  components/views/marketplace/glyphs/popular/Popular.html
  components/views/marketplace/glyphs/recommended/Recommended.html
  components/views/media/actions/Actions.html
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/controls/Controls.html
  components/views/navigation/sidebar/live/Live.html
  components/views/navigation/sidebar/quick/Quick.html
  components/views/navigation/toolbar/alerts/Alerts.html
  components/views/navigation/toolbar/pinned/Pinned.html
  components/views/servers/create/Create.html
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/storage/Storage.html
  components/views/settings/profile/accounts/Item/Item.html
  components/views/user/create/Create.html
  components/views/user/profile/Profile.html
  components/views/wallet/balance/Balance.html
  components/views/wallet/mini/body/Body.html
  components/views/wallet/popup/Popup.html
  pages/auth/unlock/Unlock.html
  pages/components.vue
  pages/setup/ImportAccount/ImportAccount.html
  pages/setup/disclaimer/Disclaimer.html
  pages/setup/phrase/Phrase.html
Labels: Missing Dev Review

#4207 feat(chat): connect file upload to iridium
  components/ui/Chat/Image/Image.less
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/message/Message.html
  components/views/chat/message/attachments/Attachments.html
  components/views/chat/message/attachments/Attachments.less
  components/views/chat/message/attachments/Attachments.vue
  components/views/chat/message/attachments/Item/Item.html
  components/views/chat/message/attachments/Item/Item.less
  components/views/chat/message/attachments/Item/Item.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
Labels: Missing Dev Review

#4208 fix(styles): resolve style issues
  assets/styles/base.less
  components/interactables/Button/Button.vue
  components/interactables/DragBar/DragBar.vue
  components/interactables/Input/Input.less
  components/interactables/Select/Select.html
  components/interactables/Select/Select.less
  components/interactables/Select/Select.vue
  components/interactables/SidebarToggle/SidebarToggle.vue
  components/views/files/controls/Controls.less
  components/views/friends/add/Add.html
  components/views/friends/add/Add.vue
  pages/friends/Friends.html
  pages/friends/Friends.less
  pages/friends/index.vue
Labels: Missing Dev Review

#4270 fix(select): max-width overflow
  components/interactables/Select/Select.html
  components/interactables/Select/Select.less
Labels: Missing Dev Review

#4274 feat(jest): 100% coverage for UsersProgram.types.test.ts
  libraries/Solana/UsersProgram/UsersProgram.types.test.ts
Labels: Missing Dev Review

#4275 feat(jest): 100% coverage for GroupChatsProgram.types
  libraries/Solana/GroupChatsProgram/GroupChatsProgram.types.test.ts
Labels: Missing Dev Review

#4277 feat(jest): 17% coverage for libraries/Crypto
  libraries/Crypto/Crypto.test.ts
Labels: Missing Dev Review

#4279 feat(iridium): sync pins for messaging
  libraries/Iridium/chat/ChatManager.ts
  nuxt.config.js
Labels: Missing Dev Review

#4269 feat(files-search): add simple implementation
  assets/styles/reset.css
  components/interactables/Input/types.d.ts
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/controls/Controls.vue
  locales/en-US.js
  pages/files/index.vue
  store/files/getters.ts
  store/files/mutations.ts
  store/files/state.ts
  store/files/types.ts
Labels: Missing Dev Review, QA tested

#4276 feat(jest): 100% coverage for store/settings/getters
  store/settings/getters.test.ts
Labels: Missing Dev Review

#4268 chore(textile): removing textile from package.json
  README.md
  components/interactables/Chip/Chip.vue
  components/interactables/QuickProfile/QuickProfile.vue
  components/interactables/UserPicker/ListItem/ListItem.vue
  components/ui/Chat/Embeds/File/File.vue
  components/ui/Unread/Unread.vue
  components/views/chat/message/Message.vue
  components/views/chat/search/result/item/Item.vue
  components/views/friends/friend/Friend.vue
  components/views/media/incomingCall/IncomingCall.vue
  components/views/media/user/User.vue
  components/views/message/Friend.vue
  components/views/navigation/sidebar/status/Status.vue
  components/views/navigation/toolbar/alerts/alert/Alert.vue
  components/views/settings/pages/profile/index.vue
  components/views/user/profile/Profile.vue
  config.ts
  libraries/BlockchainClient/interfaces.ts
  libraries/Iridium/IdentityManager.ts
  linkscript.sh
  locales/en-US.js
  nuxt.config.js
  package.json
  store/accounts/actions.test.ts.disable
  store/accounts/mutations.test.ts
  store/accounts/mutations.ts
  store/friends/types.ts
  store/groups/actions.test.ts.disable
  store/groups/types.ts
  store/webrtc/actions.ts
  types/textile/mailbox.ts
  types/textile/manager.ts
  utilities/Notifications.ts
Labels: feel free to merge hogan

#4296 chore(dir): ignore dir
  jest.config.js
Labels: Missing Dev Review

#4287 chore(jest): add jest eslint
  .eslintrc
  .prettierignore
  package.json
Labels: Missing Dev Review

#4217 chore(jest): add tests
  utilities/Keybinds.test.ts
  utilities/Logger.test.ts.disable
  utilities/__snapshots__/Keybinds.test.ts.snap
Labels: Missing Dev Review

#4302 chore(jest): add Logger.test.ts
  utilities/Logger.test.ts
Labels: Missing Dev Review

#4301 chore(jest): improve jest command
  package.json
Labels: Missing Dev Review

#4308 chore(jest): add phantom test
  libraries/BlockchainClient/adapters/Phantom/PhantomAdapter.test.ts
Labels: Missing Dev Review

#4295 feat(files-search): implement advanced search options
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/interactables/Input/Input.vue
  components/interactables/Tabs/Tabs.less
  components/ui/ResultsMessage/ResultsMessage.vue
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/controls/Controls.vue
  components/views/files/controls/switch/Switch.less
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.less
  components/views/friends/requests/Requests.vue
  locales/en-US.js
  package.json
  pages/files/Files.html
  pages/files/Files.less
  pages/files/index.vue
  pages/mobile/friends/index.vue
  store/files/getters.ts
Labels: Ready for QA

#4315 fix(build): resolve root import warnings
  tsconfig.json
Labels: Missing Dev Review

#4317 fix(build): resolve minor cypress and jest conflict
  tsconfig.json
Labels: Missing Dev Review

#4319 chore(webrtc): basic webrtc reimplementation
  .gitignore
  components/ui/BackgroundCall/BackgroundCall.html
  components/ui/Global/Global.vue
  components/ui/User/State/State.less
  components/ui/User/State/State.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/actions/Actions.vue
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
  components/views/media/actions/Actions.html
  components/views/media/actions/Actions.vue
  components/views/media/heading/Heading.vue
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.less
  components/views/media/incomingCall/IncomingCall.vue
  components/views/media/user/User.html
  components/views/media/user/User.vue
  components/views/navigation/mobile/toolbar/Toolbar.html
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/navigation/sidebar/live/Live.html
  components/views/navigation/sidebar/live/Live.vue
  components/views/navigation/sidebar/status/Status.html
  components/views/navigation/toolbar/Toolbar.vue
  layouts/desktop.vue
  layouts/mobile.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/friends/types.ts
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/Iridium/webrtc/types.ts
  libraries/WebRTC/Call.ts
  libraries/WebRTC/Emitter.ts
  libraries/WebRTC/Peer.ts
  libraries/WebRTC/WebRTC.ts
  libraries/WebRTC/encoders.ts
  libraries/WebRTC/types.ts
  pages/chat/Chat.html
  pages/chat/_id.vue
  pages/index.vue
  store/accounts/actions.ts
  store/audio/actions.ts
  store/friends/getters.ts
  store/getters.test.ts
  store/getters.ts
  store/video/actions.ts
  types/store/store.ts
Labels: Missing Dev Review

#4338 fix(messages): remove extra space if no attachments present
  components/views/chat/message/Message.html
  libraries/WebRTC/__snapshots__/encoders.test.ts.snap
  store/friends/getters.test.ts.disable
Labels: Missing Dev Review

#4342 fix(chat): overflow issue with many uploaded files
  components/ui/DroppableWrapper/DroppableWrapper.less
  pages/chat/Chat.less
Labels: Missing Dev Review

#4343 fix(user-create): attach sign in button to create user form
  components/views/user/create/Create.html
Labels: Missing Dev Review

#4345 fix(user-create): fix imageCropper from incorrectly being triggered
  components/views/user/create/Create.html
  components/views/user/create/Create.vue
Labels: Missing Dev Review

#4352 fix(login): redirect on refresh
  middleware/authenticated.ts
  pages/auth/unlock/index.vue
Labels: Missing Dev Review

#4358 chore(linkscript): move iridum clone up a level, out of core
  .gitignore
  linkscript.sh
Labels: feel free to merge hogan

#4292 feat(jest): 100% coverage for Iridium/chat/types
  libraries/Iridium/chat/types.test.ts
Labels: Missing Dev Review, feel free to merge hogan

#4293 feat(jest): 91% coverage for Iridium/utils
  libraries/Iridium/utils.test.ts
Labels: Missing Dev Review, feel free to merge hogan

#4357 feat(calls): background banner
  components/ui/BackgroundCall/BackgroundCall.html
  components/ui/BackgroundCall/BackgroundCall.vue
  components/ui/Global/Global.vue
  components/views/media/Media.vue
  components/views/media/heading/Heading.vue
  components/views/media/user/User.html
  components/views/media/user/User.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/controls/Controls.html
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/navigation/toolbar/Toolbar.vue
  layouts/desktop.vue
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/Iridium/webrtc/hooks.ts
  pages/chat/_id.vue
Labels: Missing Dev Review

#4359 chore(jest): deactivate failing test
  middleware/__snapshots__/authenticated.test.ts.snap
  middleware/authenticated.test.disabled.ts
  utilities/Timezone.test.ts
Labels: Missing Dev Review, feel free to merge hogan

#4346 fix(chatbar): block send message until subscribed, css improvements
  assets/styles/framework/typography.less
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/chatbar/controls/Controls.vue
  components/views/chat/chatbar/footer/Footer.html
  components/views/chat/chatbar/footer/Footer.less
  components/views/chat/chatbar/footer/Footer.vue
  components/views/chat/chatbar/footer/connected/Connected.less
  components/views/chat/chatbar/footer/connected/Connected.vue
  components/views/chat/chatbar/upload/Error.vue
  components/views/chat/chatbar/upload/Upload.less
  components/views/chat/chatbar/upload/preview/Preview.less
  components/views/chat/chatbar/upload/preview/item/Item.less
  types/typography.d.ts
Labels: Missing Dev Review

#4351 fix(settings-profile): hide and disable unfinished elements
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.less
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/profile/accounts/Accounts.vue
  components/views/settings/profile/accounts/Item/Item.html
  components/views/settings/profile/accounts/Item/Item.less
  components/views/settings/profile/card/Card.html
  components/views/user/profile/Profile.html
  components/views/user/profile/Profile.less
  components/views/user/profile/Profile.vue
  locales/en-US.js
  pages/auth/unlock/Unlock.less
  pages/mobile/settings/index.vue
Labels: Missing Dev Review

#4355 fix(components): text/button
  assets/styles/framework/typography.less
  components/interactables/Button/Button.html
  components/interactables/Button/Button.less
  components/interactables/Button/Button.vue
  components/interactables/Chip/Chip.vue
  components/interactables/UserPicker/ListItem/ListItem.html
  components/typography/Text.vue
  components/views/chat/message/attachments/Attachments.html
Labels: Missing Dev Review

#4353 feat(iridium): connect to users manager
  components/interactables/UserPicker/UserPicker.vue
  components/views/friends/requests/Requests.vue
  components/views/friends/search/Search.vue
  components/views/media/incomingCall/IncomingCall.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/sidebar/live/Live.vue
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/profile/types.ts
  libraries/Iridium/users/UsersManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
  pages/friends/index.vue
  store/accounts/actions.ts
Labels: Missing Dev Review

#4368 fix(calls): update calls to usermanager for details
  libraries/Iridium/webrtc/hooks.ts
Labels: Missing Dev Review

#4369 fix(sidebar): remove friend context click
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/IridiumManager.ts
Labels: Missing Dev Review

#4335 feat(iridium): offline sync
  .gitignore
  libraries/Iridium/chat/ChatManager.ts
Labels: ready to merge

#4383 feat(iridium): clear synced pins on confirmed delivery
  libraries/Iridium/chat/ChatManager.ts
Labels: draft

#4377 chore(jest): update timezone test
  utilities/Timezone.test.ts
Labels: feel free to merge hogan

#4375 fix(mobile): update mobile page to use usermanager
  pages/mobile/friends/index.vue
Labels: Missing Dev Review

#4372 fix(call): style incoming call modal
  assets/styles/framework/colors.less
  components/views/files/grid/item/Item.less
  components/views/files/mobileList/item/Item.less
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.less
  components/views/navigation/sidebar/Sidebar.less
Labels: feel free to merge hogan

#4378 feat(jest): fix and improve skipped tests
  store/chat/mutations.test.ts
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
Labels: Missing Dev Review, feel free to merge hogan

#4379 feat(calls): pip component
  assets/styles/base.less
  assets/styles/framework/ui.less
  components/ui/BackgroundCall/BackgroundCall.html
  components/ui/BackgroundCall/BackgroundCall.vue
  components/ui/Global/Global.html
  components/ui/Pip/Pip.vue
  components/views/media/Media.vue
  components/views/media/previewCall/PreviewCall.html
  components/views/media/previewCall/PreviewCall.less
  components/views/media/previewCall/PreviewCall.vue
  components/views/media/user/User.less
  config.ts
  locales/en-US.js
Labels: Missing Dev Review

#4382 fix(sounds): move sounds into static folder and remove ipfs load
  config.ts
  libraries/SoundManager/SoundManager.ts
  package.json
  static/sounds/Call.m4a
  static/sounds/Deafen.m4a
  static/sounds/Mute.m4a
  static/sounds/Notification.m4a
  static/sounds/Success.m4a
  static/sounds/Undeafen.m4a
  static/sounds/Unmute.m4a
  static/sounds/Unused.m4a
Labels: Missing Dev Review

#4398 chore(build): see if this fixes the issue in solana with optional cha…
  nuxt.config.js
Labels: Missing Dev Review, missing fixing conflict

#4399 fix(comingsoon): move vif to wallet on chatbar
  components/views/chat/chatbar/controls/Controls.html
Labels: Missing Dev Review

#4370 fix(register): adjust and improve broken styling for auth pages
  components/ui/InfoButton/InfoButton.vue
  components/ui/Modal/Modal.less
  components/ui/Popups/ErrorNetwork/ErrorNetwork.html
  components/ui/Popups/ErrorNetwork/ErrorNetwork.less
  components/views/user/create/Create.html
  components/views/user/create/Create.less
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/Unlock.less
  pages/auth/unlock/index.vue
  pages/setup/ImportAccount/ImportAccount.html
  pages/setup/ImportAccount/ImportAccount.less
  pages/setup/disclaimer/Disclaimer.less
Labels: feel free to merge hogan

#4385 feat(chat): is_typing indicator
  components/ui/Chat/TypingIndicator/TypingIndicator.less
  components/ui/Chat/TypingIndicator/TypingIndicator.vue
  components/ui/Global/Global.vue
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/footer/Footer.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4390 feat(jest): 80% coverage for utilities/Logger, update jest npm script
  package.json
  utilities/Logger.test.ts
Labels: Missing Dev Review, feel free to merge hogan

#4392 feat(jest): 100% coverage for libraries/Iridium/users/types
  libraries/Iridium/users/types.test.ts
Labels: Missing Dev Review, feel free to merge hogan

#4395 fix(calls): offer/answer fix
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/Iridium/webrtc/types.ts
  libraries/WebRTC/Call.ts
  libraries/WebRTC/WebRTC.ts
  libraries/WebRTC/types.ts
Labels: Missing Dev Review

#4314 fix(files): fix rename reactivity and delete action
  components/views/files/controls/Controls.less
  libraries/Iridium/files/FilesManager.ts
  pages/files/index.vue
  store/files/getters.ts
Labels: Missing Dev Review

#4400 chore(eslint): add cypress eslint
  .eslintrc.json
  jest.config.js
  package.json
Labels: Changes Requested, draft, merge blocked

#4402 refactor(calls): improve mediaUser markup
  assets/styles/base.less
  assets/styles/framework/typography.less
  components/typography/Tag/Tag.vue
  components/typography/Text.vue
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.less
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/user/User.html
  components/views/media/user/User.less
  pages/chat/Chat.html
  pages/chat/_id.vue
  types/typography.d.ts
Labels: Missing Dev Review

#4404 feat(calls): remove background call banner
  assets/styles/base.less
  components/ui/DroppableWrapper/DroppableWrapper.vue
  components/ui/Global/Global.html
  components/views/friends/requests/Requests.vue
  layouts/chat.vue
  layouts/desktop.vue
  layouts/mobile.vue
  utilities/notNull.ts
Labels: Missing Dev Review

#4376 feat(iridium): group chat
  components/ui/GroupIcon/GroupIcon.html
  components/ui/GroupIcon/GroupIcon.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.vue
  components/views/chat/message/reactions/Reactions.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/sidebar/quick/Quick.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/profile/ProfileManager.ts
  store/accounts/actions.ts
Labels: draft

#4417 chore(jest): update test
  store/ui/getters.test.ts
Labels: Missing Dev Review

#4418 chore(jest): add test
  utilities/notNull.test.ts
Labels: Missing Dev Review

#4422 fix(toolbar): fix call button
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review

#4424 chore(temp): remove cypress
  package.json
Labels: Missing Dev Review

#4391 feat(jest): 79% coverage for IdentityManager
  libraries/Iridium/IdentityManager.test.ts
  libraries/Iridium/__snapshots__/IdentityManager.test.ts.snap
Labels: ready to merge

#4407 refactor(subtitle): swap out subtitle instances for typographyText
  assets/styles/framework/typography.less
  components/typography/Text.vue
  components/views/chat/chatbar/upload/preview/item/Item.html
  components/views/files/view/View.html
  components/views/settings/pages/realms/realm/Realm.html
  components/views/settings/pages/realms/realm/index.vue
  components/views/settings/pages/storage/Storage.html
  components/views/settings/profile/accounts/Item/Item.html
  components/views/settings/profile/card/Card.html
  components/views/wallet/popup/Popup.html
  components/views/wallet/recent/item/Item.html
  pages/allcomponents.vue
  pages/components.vue
  types/typography.d.ts
Labels: ready to merge

#4432 fix(mobile): undefined check for route param id
  components/ui/Chat/TypingIndicator/TypingIndicator.vue
  components/views/chat/chatbar/footer/Footer.vue
  components/views/files/controls/Controls.less
  components/views/navigation/mobile/toolbar/Toolbar.html
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4431 feat(media): restore the green border around MediaUser when the user …
  components/views/media/Media.less
  components/views/media/user/User.html
  components/views/media/user/User.less
  components/views/media/user/User.vue
  components/views/settings/pages/audio/index.vue
  utilities/AudioStreamUtils.ts
Labels: Missing Dev Review

#4427 feat(calls): add dragbar resize
  components/interactables/DragBar/DragBar.less
  components/views/chat/conversation/Conversation.less
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
  components/views/media/heading/Heading.less
  components/views/media/heading/Heading.vue
  plugins/thirdparty/persist.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Missing Dev Review

#4408 fix(call-actions): fixed action buttons size
  components/views/media/actions/Actions.html
  components/views/media/actions/Actions.less
  components/views/media/actions/Actions.vue
  components/views/navigation/sidebar/controls/Controls.html
  components/views/navigation/sidebar/controls/Controls.less
  components/views/navigation/sidebar/controls/Controls.vue
  libraries/Enums/types/webrtc.ts
Labels: Missing Dev Review

#4429 feat(iridium): group add member
  components/views/group/invite/Invite.vue
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4436 fix(files): mobile wrap for directory name
  components/views/files/controls/switch/Switch.less
  components/views/files/filepath/Filepath.less
  components/views/navigation/mobile/nav/Nav.less
Labels: Missing Dev Review

#4409 fix(calls): mute/unmute logic
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/WebRTC/Call.ts
Labels: feel free to merge hogan/mauro/drew/joe

#4187 fix(mute-toggle): cleared previous sounds played
  libraries/SoundManager/SoundManager.test.ts
  libraries/SoundManager/SoundManager.ts
  store/audio/actions.ts
  store/sounds/actions.test.ts
  store/sounds/actions.ts
Labels: feel free to merge hogan/mauro/drew/joe

#4443 fix(call): calling sound fix
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4439 feat(calls): add fullscreen support
  components/ui/Global/Global.vue
  components/views/media/Media.html
  components/views/media/Media.vue
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.vue
  components/views/navigation/sidebar/live/Live.html
  components/views/navigation/sidebar/live/Live.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  store/webrtc/actions.ts
Labels: ready to merge

#4425 chore(jest): update jest
  .github/workflows/run-jest-tests.yml
Labels: Changes Requested

#4435 feat(jest): update describe on tests
  libraries/BlockchainClient/BlockchainClient.test.ts
  libraries/Crypto/Crypto.test.ts
  libraries/Iridium/IdentityManager.test.ts
  libraries/Solana/UsersProgram/UsersProgram.types.test.ts
  store/meta/mutations.test.ts
  utilities/EXIF.test.ts
  utilities/Messaging.test.ts
  utilities/Thumbnail.test.ts
  utilities/__snapshots__/Messaging.test.ts.snap
  utilities/__snapshots__/Thumbnail.test.ts.snap
Labels: Missing Dev Review, feel free to merge hogan/mauro/drew/joe

#4444 fix(webrtc): streamMuted
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/WebRTC/Call.ts
Labels: Missing Dev Review

#4452 fix(chat): fix reply name while drafting
  components/views/chat/chatbar/reply/Reply.html
  components/views/chat/chatbar/reply/Reply.less
  components/views/chat/chatbar/reply/Reply.vue
Labels: Missing Dev Review

#4445 fix(webrtc): typing status indicator
  components/ui/Chat/TypingIndicator/TypingIndicator.vue
  components/views/chat/chatbar/footer/Footer.html
  components/views/chat/chatbar/footer/Footer.vue
  config.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4455 fix(calls): flip local video based on setting
  components/views/media/user/User.html
  components/views/media/user/User.vue
Labels: Missing Dev Review

#4453 fix(chat): fix replies accordion text
  components/views/chat/message/Message.html
  components/views/chat/message/replies/Replies.html
  components/views/chat/message/replies/Replies.vue
  locales/en-US.js
Labels: Missing Dev Review

#4446 feat(jest): resolve undefined snapshots
  components/mixins/Touch/__snapshots__/index.test.ts.snap
  components/mixins/Touch/index.test.ts
  components/mixins/UserPermissions/__snapshots__/index.test.ts.snap
  components/mixins/UserPermissions/index.test.ts
  store/sounds/__snapshots__/actions.test.ts.snap
  store/sounds/actions.test.ts
  store/ui/__snapshots__/types.test.ts.snap
  store/ui/types.test.ts
Labels: Missing Dev Review

#4463 fix(friends): stop input autofocus from breaking swiper animation
  components/interactables/Input/Input.vue
  components/views/friends/search/Search.vue
Labels: Missing Dev Review

#4411 fix(user): user status
  components/ui/User/State/State.vue
  components/views/chat/chatbar/footer/connected/Connected.vue
  components/views/navigation/toolbar/Toolbar.vue
  config.ts
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/friends/types.ts
  libraries/Iridium/users/UsersManager.ts
  libraries/Iridium/users/types.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review, missing fixing conflict

#4464 feat(chat): show join/leave notices messages in conversation
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  components/views/chat/message/notice/Notice.html
  components/views/chat/message/notice/Notice.less
  components/views/chat/message/notice/Notice.vue
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/users/UsersManager.ts
  locales/en-US.js
  pages/chat/Chat.html
  utilities/chat.ts
Labels: Missing Dev Review

#4467 fix(settings): use new text component in settings headings
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/audio/sounds/Sounds.html
  components/views/settings/pages/developer/Developer.html
  components/views/settings/pages/developer/index.vue
  components/views/settings/pages/info/Info.html
  components/views/settings/pages/info/index.vue
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/network/Network.html
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/realms/Realms.html
  components/views/settings/unit/Unit.html
Labels: Missing Dev Review

#4465 feat(calls): reposition call controls
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/actions/Fullscreen.vue
  components/views/media/actions/volume/Volume.html
  components/views/media/actions/volume/Volume.less
  components/views/media/actions/volume/Volume.vue
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.less
  components/views/media/heading/Heading.vue
Labels: Missing Dev Review

#4461 fix(friends): send user to correct screen when "Add Friend" is pressed
  components/interactables/KeybindInput/KeybindInput.vue
  components/views/friends/emptyMessage/EmptyMessage.vue
  pages/mobile/friends/index.vue
Labels: Missing Dev Review

#4469 fix(calls): improve mobile incoming calls
  components/ui/Global/Global.html
  components/views/media/incomingCall/IncomingCall.less
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4457 feat(webrtc): initialize webrtc streams with user selected devices
  components/ui/Global/Global.vue
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/Iridium/webrtc/types.ts
  libraries/WebRTC/Call.ts
  store/audio/actions.ts
  store/video/actions.ts
  store/webrtc/actions.ts
Labels: Missing Dev Review

#4479 chore(realms): hide realms - AP-2243
  components/views/settings/Sidebar.vue
Labels: Missing Dev Review

#4475 chore(unlock): notice on unlock page to recommend chrome
  components/ui/InlineNotification/InlineNotification.html
  locales/en-US.js
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/Unlock.less
  pages/auth/unlock/index.vue
Labels: Missing Dev Review

#4480 chore(fix): fix 404
  config.ts
Labels: Missing Dev Review

#4471 fix(buttons): build out size prop
  components/interactables/Button/Button.less
  components/views/media/incomingCall/IncomingCall.html
Labels: Missing Dev Review

#4481 chore(jest): add chat.test.ts
  utilities/__snapshots__/chat.test.ts.snap
  utilities/chat.test.ts
Labels: Missing Dev Review

#4473 fix(user): user states refactored
  assets/styles/framework/animations.less
  components/ui/Chat/TypingIndicator/TypingIndicator.less
  components/ui/Circle/Circle.html
  components/ui/Circle/Circle.less
  components/ui/Global/Global.html
  components/ui/SvgDefs/SvgDefs.vue
  components/ui/User/State/State.less
  components/ui/User/State/State.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/users/types.ts
Labels: Missing Dev Review

#4482 chore(jest): add AudioStreamUtils.test.ts
  utilities/AudioStreamUtils.test.ts
  utilities/__snapshots__/AudioStreamUtils.test.ts.snap
Labels: Missing Dev Review

#4489 fix(buttons): default primary color
  components/interactables/Button/Button.vue
  components/interactables/ImageCropper/ImageCropper.html
  components/interactables/KeybindInput/KeybindInput.html
  components/ui/Popups/ErrorNetwork/ErrorNetwork.html
  components/views/callToAction/CallToAction.html
  components/views/chat/message/attachments/Item/Item.html
  components/views/files/controls/Controls.html
  components/views/friends/emptyMessage/EmptyMessage.vue
  components/views/friends/friend/Friend.html
  components/views/friends/qrSection/QrSection.vue
  components/views/marketplace/glyphs/detail/Detail.html
  components/views/marketplace/glyphs/popular/Popular.html
  components/views/marketplace/glyphs/recommended/Recommended.html
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/alerts/Alerts.html
  components/views/servers/create/Create.html
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/storage/Storage.html
  components/views/settings/profile/accounts/Item/Item.html
  components/views/user/create/Create.html
  components/views/user/profile/Profile.html
  components/views/wallet/balance/Balance.html
  components/views/wallet/mini/body/Body.html
  pages/auth/unlock/Unlock.html
  pages/components.vue
Labels: Missing Dev Review

#4490 fix(calls): incoming call logic for mobile. refactor incoming call pr…
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/views/media/incomingCall/IncomingCall.vue
  components/views/media/previewCall/PreviewCall.vue
Labels: Missing Dev Review

#4491 fix(mobile): fix swiper issues around mobile chat
  components/ui/Global/Global.html
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/item/Item.vue
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4493 feat(sidebar): display other message types in message preview
  components/views/chat/message/attachments/Item/Item.less
  components/views/chat/message/notice/Notice.html
  components/views/navigation/sidebar/list/item/Item.vue
  locales/en-US.js
Labels: Missing Dev Review

#4433 feat(modal): close on 'Escape' key
  components/interactables/KeybindInput/KeybindInput.html
  components/interactables/KeybindInput/KeybindInput.vue
  components/ui/Modal/Modal.html
  components/ui/Modal/Modal.vue
  layouts/desktop.vue
Labels: Missing Dev Review

#4492 feat(mobile): background call indicator on mobile
  assets/styles/framework/ui.less
  components/ui/BackgroundCall/BackgroundCall.html
  components/ui/BackgroundCall/BackgroundCall.less
  components/ui/BackgroundCall/BackgroundCall.vue
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  layouts/mobile.vue
  locales/en-US.js
  pages/mobile/friends/index.vue
Labels: Missing Dev Review

#4474 fix(notifications): fix group chat notification messaging
  components/views/navigation/toolbar/alerts/alert/Alert.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/notifications/types.ts
  locales/en-US.js
Labels: Missing Dev Review

#4496 fix(typing): typing indicator bug
  components/views/chat/chatbar/Chatbar.vue
  config.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4495 feat(jest): 100% coverage for utilities/chat
  utilities/chat.test.ts
Labels: Missing Dev Review

#4509 fix(styling): add "sm" styling for InteractablesButton
  components/interactables/Button/Button.less
  components/interactables/Input/Input.html
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/List.less
  components/views/settings/Sidebar.vue
  components/views/settings/unit/Unit.html
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4510 feat(chat): message reaction pubsub/reactivity
  components/views/chat/message/reactions/Reactions.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
Labels: Missing Dev Review

#4507 feat(settings-profile): implement functionality for updating user det…
  components/interactables/Input/Input.html
  components/interactables/Input/Input.vue
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/index.vue
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/users/types.ts
  locales/en-US.js
  nuxt.config.js
  store/accounts/actions.ts
  store/accounts/mutations.ts
Labels: Missing Dev Review

#4508 fix(calls): fullscreen toggle bug
  components/views/media/Media.vue
Labels: Missing Dev Review

#4516 feat(jest): 100% coverage for Iridium/notifications/types
  libraries/Iridium/notifications/__snapshots__/types.test.ts.snap
  libraries/Iridium/notifications/types.test.ts
Labels: Missing Dev Review

#4523 chore(action): link issue
  .github/workflows/issue-link.yml
Labels: Missing Dev Review

#4515 feat(jest): 15% coverage for SolanaAdapter
  libraries/BlockchainClient/adapters/SolanaAdapter/SolanaAdapter.test.ts
  libraries/BlockchainClient/adapters/SolanaAdapter/__snapshots__/SolanaAdapter.test.ts.snap
Labels: Missing Dev Review

#4505 fix(toolbar): clean component
  assets/styles/base.less
  components/typography/Text.vue
  components/views/navigation/mobile/toolbar/Toolbar.html
  components/views/navigation/mobile/toolbar/Toolbar.less
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review

#4531 fix(settings-profile): stop page sometimes refreshing on status update
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/index.vue
Labels: Missing Dev Review
