Repository Satellite-im/Core-PWA, pull requests merged in 2022-11, with the labels that each got.

#5439 fix(misc): fix type related errors
  components/ui/ComingSoon/ComingSoon.vue
  components/ui/Loaders/GenericBlock/GenericBlock.vue
  components/ui/Loaders/LoadingBar/LoadingBar.vue
  components/ui/Loaders/Spinner/Spinner.vue
  components/ui/Pip/Pip.vue
  components/ui/Spacer/Spacer.vue
  components/ui/TypeAhead/TypeAhead.vue
  components/ui/Unread/Unread.html
  components/ui/Unread/Unread.less
  components/ui/Unread/Unread.vue
  components/ui/UpdateModal/UpdateModal.vue
  components/ui/WelcomeModal/WelcomeModal.vue
  components/views/chat/chatbar/commands/preview/Preview.vue
  components/views/chat/chatbar/reply/Reply.vue
  components/views/chat/chatbar/upload/Upload.vue
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/glyph/Glyph.vue
  components/views/chat/message/reactions/Reactions.vue
  components/views/files/list/row/Row.vue
  components/views/glyphs/Glyphs.vue
  components/views/glyphs/sample/Sample.vue
  components/views/media/Media.vue
  components/views/navigation/mobile/nav/Nav.vue
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/settings/breadcrumbs/Breadcrumbs.html
  components/views/settings/breadcrumbs/Breadcrumbs.less
  components/views/settings/breadcrumbs/Breadcrumbs.vue
  components/views/settings/pages/keybinds/index.vue
  components/views/settings/pages/network/index.vue
  components/views/settings/pages/privacy/index.vue
  components/views/settings/pages/realms/index.vue
  components/views/settings/pages/realms/realm/index.vue
  components/views/settings/profile/Banner.vue
  components/views/settings/profile/Picture.vue
  components/views/settings/profile/card/Card.vue
  libraries/Files/types/filesystem.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/profile/types.ts
  libraries/Iridium/users/UsersManager.ts
  libraries/Iridium/utils.ts
  libraries/SoundManager/SoundManager.ts
  libraries/WebRTC/Emitter.ts
  libraries/WebRTC/Wire.ts
  libraries/WebRTC/types.ts
  libraries/ui/ReleaseNotes.ts
  mock/marketplace.ts
  mock/profile.ts
  package.json
  store/accounts/types.ts
  store/audio/actions.ts
  store/settings/actions.ts
  store/ui/actions.ts
  store/ui/types.ts
  store/video/actions.ts
  types/marketplace/marketplace.ts
  types/modules/images.d.ts
  types/profile/profile.ts
  types/search/search.ts
  utilities/Notifications.ts
Labels: Missing Dev Review

#5442 fix(sidebar-list-item): implement timestamps for new conversations
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
Labels: Missing Dev Review

#5429 fix(actionsheet): style and behaviour
  assets/styles/base.less
  components/compositions/useMeta.ts
  components/interactables/Button/Button.less
  components/interactables/KeybindInput/KeybindInput.vue
  components/ui/ActionSheet/ActionSheet.vue
  components/ui/ContextMenu/ContextMenu.vue
  components/ui/Modal/Modal.less
  components/views/navigation/mobile/nav/Nav.less
  components/views/navigation/sidebar/list/item/Item.html
  layouts/default.vue
  middleware/safearea.ts
  nuxt.config.js
  pages/mobile/friends/index.vue
  plugins/local/contextmenu.ts
  utilities/Keyboard.ts
Labels: QA tested, QA feedback

#5446 fix(chat): set read only if at the bottom of the scroll
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review, QA tested

#5444 refactor(glyphs): move information out of mocks, improve type sense, …
  components/ui/Spacer/Spacer.vue
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/chat/enhancers/glyphs/Glyphs.less
  components/views/chat/enhancers/glyphs/Glyphs.vue
  components/views/chat/enhancers/glyphs/item/Item.html
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/chat/enhancers/glyphs/nav/Nav.html
  components/views/chat/enhancers/glyphs/nav/Nav.less
  components/views/chat/enhancers/glyphs/nav/Nav.vue
  components/views/chat/enhancers/glyphs/pack/Pack.html
  components/views/chat/enhancers/glyphs/pack/Pack.less
  components/views/chat/enhancers/glyphs/pack/Pack.vue
  components/views/chat/enhancers/glyphs/pack/PackGroup.vue
  components/views/chat/message/glyph/Glyph.vue
  components/views/glyphs/Glyphs.vue
  components/views/marketplace/glyphs/detail/Detail.html
  components/views/marketplace/glyphs/featured/Featured.html
  components/views/marketplace/glyphs/popular/Popular.html
  components/views/marketplace/glyphs/recommended/Recommended.html
  components/views/marketplace/glyphs/shop/item/Item.html
  components/views/marketplace/glyphs/trending/item/Item.html
  libraries/Iridium/chat/ChatManager.ts
  libraries/glyphs.ts
  mock/marketplace.ts
  mock/tests/__snapshots__/glyphs.test.ts.snap
  mock/tests/glyphs.test.ts
  plugins/local/mock.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/getters.test.ts
  store/ui/getters.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  types/ui/glyph.d.ts
Labels: QA tested

#5447 feat(jest): 82% coverage for store/chat/mutations
  store/chat/mutations.test.ts
Labels: Missing Dev Review, QA tested

#5451 feat(jest): improve Timestamp and ReleaseNotes coverage
  libraries/ui/ReleaseNotes.test.ts
  utilities/timestamp.test.ts
Labels: Missing Dev Review

#5455 refactor(chat): upgrade new message divider to script setup
  components/ui/Breadcrumbs/Breadcrumbs.html
  components/ui/Breadcrumbs/Breadcrumbs.less
  components/ui/Breadcrumbs/Breadcrumbs.vue
  components/ui/CaretDivider/CaretDivider.html
  components/ui/CaretDivider/CaretDivider.less
  components/ui/CaretDivider/CaretDivider.vue
Labels: Ready for QA

#5457 refactor(sort): switch to collator over localeCompare for improved pe…
  components/compositions/conversations.ts
  components/compositions/friends.ts
  store/files/getters.ts
Labels: QA tested

#5452 refactor(webrtc): composable for active call timer
  components/compositions/webrtc.ts
  components/ui/BackgroundCall/BackgroundCall.vue
  components/views/chat/message/call/Call.vue
  components/views/media/heading/Heading.vue
Labels: Ready for QA

#5461 refactor(chat): upgrade to full script setup
  pages/chat/Chat.html
  pages/chat/_id.vue
Labels: Ready for QA

#5463 fix(settings): remove user timezone settings and package
  components/views/settings/profile/card/Card.html
  components/views/settings/profile/card/Card.vue
  package.json
  store/settings/mutations.test.ts
  store/settings/mutations.ts
  store/settings/state.ts
  store/settings/types.ts
  utilities/Timezone.test.ts
  utilities/Timezone.ts
Labels: Ready for QA

#5448 test(cypress): fixes for tests failing on CI
  .github/workflows/cypress-CI-tests.yml
  cypress/e2e/add-friends.js
  cypress/e2e/chat-features.js
  cypress/e2e/chat-glyphs-validations.js
  cypress/e2e/chat-top-toolbar.js
  cypress/e2e/mobiles-responsiveness.js
  cypress/e2e/pin-unlock-validations.js
  cypress/e2e/snapshots-test.js
  cypress/e2e/version-number.js
  cypress/scripts/sync-node-script.sh
  cypress/scripts/temp-yarn.lock
  cypress/scripts/watch-script.sh
  cypress/support/commands.js
  cypress/support/first-user/commands.js
  cypress/support/second-user/commands.js
Labels: QA tested

#5470 test(cypress): unskip tests for chat-features now working
  cypress/e2e/chat-features.js
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/support/commands.js
  cypress/support/first-user/commands.js
  cypress/support/second-user/commands.js
Labels: QA tested

#5465 feat(notifications): add notification actions for android
  components/compositions/listenToNotifications.ts
  components/compositions/useNotifActionHandlers.ts
  components/compositions/useNotifCreateHandlers.ts
  components/views/settings/pages/notifications/index.vue
  libraries/Iridium/NotificationManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/notifications/types.ts
  utilities/Notifications.ts
Labels: QA tested

#5472 test(cypress): test all alphabet chars on chat
  cypress/e2e/chat-features.js
Labels: QA tested

#5473 test(cypress): updates for CI and unskip tests
  cypress/e2e/mobiles-responsiveness.js
  cypress/support/commands.js
  cypress/support/first-user/commands.js
  cypress/support/second-user/commands.js
Labels: QA tested

#5475 test(cypress): add settings themes tests
  components/interactables/Select/Select.html
  components/views/settings/pages/personalize/Personalize.html
  cypress/e2e/settings-personalize.js
  cypress/support/commands.js
Labels: QA tested

#5467 chore(chat): set read on conversation scroll bottom
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
Labels: QA tested

#5476 test(cypress): adding emoji picker tests
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/emoji/Emoji.html
  cypress/e2e/chat-features.js
  cypress/e2e/chat-text-validations.js
  cypress/support/commands.js
Labels: QA tested

#5471 feat(jest): increase coverage for chat/mutations and Markdown
  libraries/ui/Markdown.test.ts
  store/chat/mutations.test.ts
Labels: Missing Dev Review
