Repository Satellite-im/Core-PWA, pull requests merged in 2022-09, with the labels that each got.

#4563 fix(reactions): emoji reactivity
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4548 fix(groups): group icon render issues
  components/compositions/conversations.ts
  components/ui/GroupIcon/GroupIcon.html
  components/ui/GroupIcon/GroupIcon.vue
  components/views/navigation/mobile/toolbar/Toolbar.html
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/live/Live.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4571 refactor(editable): move editable component into interactables directory
  components/interactables/Editable/Editable.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/message/edit/Edit.vue
  components/views/settings/pages/profile/Profile.html
Labels: Missing Dev Review

#4569 feat(settings-profile): add functionality for updating about me
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
  components/views/settings/profile/accounts/Item/Item.less
  components/views/settings/profile/card/Card.less
  locales/en-US.js
  store/accounts/actions.ts
  store/accounts/types.ts
Labels: Missing Dev Review

#4576 fix(buttons): add correct flair color glow
  components/interactables/Button/Button.less
Labels: Missing Dev Review

#4574 fix(files): only show border if not last child
  components/views/files/mobileList/item/Item.less
Labels: Missing Dev Review

#4585 fix(chat): put back dropped subscriptions
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4587 fix(mobile): show mobile nav on consent push
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4589 chore(fix): fix jest tests
  jest.config.js
  store/accounts/mutations.test.ts
  store/chat/__snapshots__/mutations.test.ts.snap
  store/getters.test.disabled.ts
Labels: Missing Dev Review

#4591 fix(sidebar): no friends message
  components/views/navigation/sidebar/list/List.html
Labels: ready to merge

#4592 fix(sidebar): timestamps
  components/views/navigation/sidebar/list/item/Item.vue
Labels: ready to merge

#4596 feat(build): npmrc & linkscript pnpm update
  .npmrc
  linkscript.sh
Labels: Missing Dev Review

#4588 fix(toolbar): render issues surrounding user details
  components/compositions/conversations.ts
  components/views/navigation/mobile/toolbar/Toolbar.html
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review

#4593 fix(userpicker): floating checkmark for selected items
  components/interactables/Checkbox/Checkbox.less
Labels: Missing Dev Review

#4597 fix(sidebar): sort messages by latest incoming message
  components/views/navigation/sidebar/list/List.vue
Labels: ready to merge

#4572 feat(safer): add a safer validator to verify signature
  libraries/Iridium/chat/ChatManager.ts
Labels: ready to merge

#4603 fix(requests): stop friend request names sometimes being displayed as…
  components/views/friends/friend/Friend.html
  components/views/friends/friend/Friend.less
  components/views/friends/requests/Requests.vue
Labels: Missing Dev Review

#4601 fix(mobile): redirect to proper page for mobile
  pages/index.vue
Labels: ready to merge

#4611 fix(sync-init): send sync init before profile load
  libraries/Iridium/IridiumManager.ts
Labels: Missing Dev Review

#4612 fix(sync): sync init changes
  .env.example
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/users/UsersManager.ts
  linkscript.sh
  package.json
Labels: Missing Dev Review

#4613 fix(init): pnpm_home
  linkscript.sh
Labels: Missing Dev Review

#4614 fix(linkscript): yarn links
  linkscript.sh
Labels: Missing Dev Review

#4615 fix(package): restore git version hashes
  package.json
Labels: Missing Dev Review

#4617 fix(profile): wait for profile before starting managers
  components/views/friends/search/Search.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/profile/ProfileManager.ts
Labels: Missing Dev Review

#4618 fix(sync): first try
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/users/UsersManager.ts
Labels: Missing Dev Review

#4623 fix(offlinesync): send sync/fetch on connect
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/users/UsersManager.ts
Labels: Missing Dev Review

#4609 feat(permissions): permisions functionality added, improved its ui
  components/interactables/Permissions/Permissions.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
  libraries/Iridium/NotificationManager.ts
  locales/en-US.js
  utilities/Notifications.ts
Labels: Missing Dev Review

#4633 refactor(settings): v show instead of v if for settings modal
  components/views/settings/modal/Modal.html
Labels: ready to merge

#4627 fix(account): fix profile pic color on account create
  components/views/user/create/Create.html
  components/views/user/create/Create.vue
Labels: Missing Dev Review

#4638 fix(router): fix mobile auth issue
  pages/auth/register/index.vue
  pages/index.vue
Labels: Missing Dev Review

#4635 fix(sidebar): remove friend reactivity
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4553 feat(media): call ui updates
  assets/styles/base.less
  components/interactables/DragBar/DragBar.less
  components/interactables/Volume/Volume.html
  components/interactables/Volume/Volume.less
  components/interactables/Volume/Volume.vue
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
  components/views/media/actions/Actions.html
  components/views/media/actions/Actions.less
  components/views/media/actions/Actions.vue
  components/views/media/actions/volume/Volume.html
  components/views/media/actions/volume/Volume.less
  components/views/media/actions/volume/Volume.vue
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.less
  components/views/media/heading/Heading.vue
  components/views/media/user/User.html
  components/views/media/user/User.less
  components/views/media/user/User.vue
  components/views/settings/pages/audio/Audio.html
  libraries/Iridium/users/UsersManager.ts
  plugins/thirdparty/persist.ts
  store/video/__snapshots__/state.test.ts.snap
  store/video/state.ts
  utilities/AudioStreamUtils.ts
  utilities/duration.ts
Labels: Missing Dev Review

#4610 feat(jest): 14% coverage for store/files
  store/files/__snapshots__/state.test.ts.snap
  store/files/mutations.test.ts
  store/files/state.test.ts
Labels: ready to merge

#4640 feat(sidebar): add context call option
  assets/styles/base.less
  components/interactables/ContextMenu/ContextMenu.html
  components/interactables/ContextMenu/ContextMenu.less
  components/ui/ContextMenu/ContextMenu.vue
  components/ui/ContextMenu/ListItem/ListItem.vue
  components/views/navigation/sidebar/list/item/Item.vue
  locales/en-US.js
  store/ui/types.ts
Labels: ready to merge

#4650 chore(linkscript): update linkscript to pass in iridium env var for b…
  linkscript.sh
Labels: Missing Dev Review

#4645 fix(permissions): fixed browser compatibility, improved component performances
  components/interactables/Permissions/Permissions.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
Labels: Missing Dev Review

#4652 fix(init): fixes init duplication
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4654 fix(reactivity): flip local video setting in calls
  components/views/media/user/User.html
  components/views/media/user/User.vue
Labels: Missing Dev Review

#4657 fix(user-create): disable profile pic upload on account creation
  components/interactables/Button/Button.html
  components/interactables/Button/Button.less
  components/interactables/Button/Button.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/user/create/Create.html
Labels: Missing Dev Review

#4629 fix(settings): remove loading message while updating remote settings
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/index.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
Labels: Missing Dev Review

#4641 feat(jest): improve numerous store tests
  store/chat/__snapshots__/mutations.test.ts.snap
  store/chat/mutations.test.ts
  store/conversation/mutations.test.ts
  store/ui/actions.test.disabled.ts
Labels: Missing Dev Review

#4608 fix(requests): stop outgoing friend request names sometimes being dis…
  components/views/friends/friend/Friend.vue
  libraries/Iridium/friends/FriendsManager.ts
Labels: Missing Dev Review

#4660 fix(interactables): volume slider props
  components/interactables/Volume/Volume.html
  components/interactables/Volume/Volume.vue
Labels: Missing Dev Review

#4662 fix(errors): cleanup errors with wrong color
  assets/styles/framework/typography.less
  components/interactables/ContextMenu/ContextMenu.less
  components/interactables/Input/Input.html
  components/interactables/Input/Input.vue
  components/interactables/Permissions/Permissions.vue
  components/typography/Text.vue
  components/ui/ContextMenu/ContextMenu.vue
  components/views/chat/chatbar/footer/Footer.html
  components/views/chat/chatbar/upload/Error.vue
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.vue
  components/views/files/rename/Rename.html
  components/views/friends/search/Search.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/realms/realm/Realm.html
  components/views/user/create/Create.html
  pages/auth/unlock/Unlock.html
  types/typography.d.ts
Labels: Missing Dev Review

#4663 feat(buttons): add accessibility prop for aria label
  components/interactables/Button/Button.html
  components/interactables/Button/Button.vue
Labels: Missing Dev Review

#4666 refactor(bundle): remove unused packages
  assets/styles/thirdparty/multiselect.less
  assets/styles/thirdparty/v-calendar.less
  components/views/chat/search/input/Input.html
  components/views/chat/search/result/Result.html
  components/views/settings/profile/card/Card.html
  nuxt.config.js
  package.json
  plugins/thirdparty/multiselect.ts
  plugins/thirdparty/v-calendar.ts
Labels: Missing Dev Review

#4676 fix(toolbar): pull your own name in group lists
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review

#4678 fix(files): use newly added disabled styling on button
  components/views/files/aside/Aside.html
  components/views/files/aside/Aside.less
Labels: Missing Dev Review

#4685 fix(webrtc): moved the call store to the Iridium WebRTCManager
  components/ui/BackgroundCall/BackgroundCall.vue
  components/views/chat/conversation/Conversation.html
  components/views/media/Media.vue
  components/views/media/user/User.vue
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/Iridium/webrtc/types.ts
  libraries/WebRTC/WebRTC.ts
  pages/allcomponents.vue
  pages/components.vue
  plugins/local/classLoader.ts
  store/audio/actions.ts
  store/video/actions.ts
  store/webrtc/actions.ts
  store/webrtc/state.ts
  store/webrtc/types.ts
Labels: Missing Dev Review

#4674 fix(audio): talking indicator timeout
  utilities/AudioStreamUtils.ts
Labels: Missing Dev Review

#4683 fix(meta): fix favicon
  nuxt.config.js
Labels: Missing Dev Review

#4671 fix(settings): only show active routes
  components/views/settings/modal/Modal.html
Labels: Missing Dev Review

#4670 refactor(friends): dont lazy load tabs
  pages/friends/Friends.html
Labels: Missing Dev Review

#4669 feat(pip): use animation keyframe
  components/ui/Pip/Pip.vue
  utilities/animation.ts
Labels: Ready for QA

#4686 feat(sidebar): implement conversation search
  components/views/chat/message/replies/Replies.vue
  components/views/friends/mobile/List.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/List.less
  components/views/navigation/sidebar/list/List.vue
  locales/en-US.js
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4622 feat(welcome): welcome popup functioning and prelim copy
  components/ui/WelcomeModal/WelcomeModal.html
  components/ui/WelcomeModal/WelcomeModal.less
  components/ui/WelcomeModal/WelcomeModal.vue
  components/views/chat/message/Message.vue
  components/views/navigation/sidebar/Sidebar.html
  libraries/Iridium/users/types.ts
  locales/en-US.js
  store/accounts/actions.ts
  store/accounts/types.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  types/ui/user.d.ts
Labels: Ready for QA

#4690 fix(settings-profile): disable account section
  components/views/settings/pages/profile/Profile.html
  components/views/settings/profile/accounts/Item/Item.html
  locales/en-US.js
Labels: Missing Dev Review

#4630 fix(media-user): ensure AudioStreamUtils is re-enabled on page changes
  components/ui/Pip/Pip.vue
  components/views/media/user/User.vue
Labels: bug

#4698 refactor(welcome): remove data from iridium
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/ui/WelcomeModal/WelcomeModal.html
  components/ui/WelcomeModal/WelcomeModal.less
  components/ui/WelcomeModal/WelcomeModal.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  libraries/Iridium/users/types.ts
  store/accounts/__snapshots__/state.test.ts.snap
  store/accounts/actions.ts
  store/accounts/mutations.ts
  store/accounts/state.ts
  store/accounts/types.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Missing Dev Review

#4693 feat(mobile): add indicators for incoming friend requests
  components/ui/DotBadge/DotBadge.less
  components/ui/DotBadge/DotBadge.vue
  components/views/navigation/mobile/nav/Nav.html
  components/views/navigation/mobile/nav/Nav.less
  components/views/navigation/mobile/nav/Nav.vue
  pages/mobile/friends/index.vue
Labels: Missing Dev Review

#4691 fix(call): only show talking indicator for one stream
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
  components/views/media/user/User.html
  components/views/media/user/User.less
  components/views/media/user/User.vue
  utilities/AudioStreamUtils.ts
Labels: Missing Dev Review

#4696 feat(sidebar): add logic and styling for unread conversations
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/chat/ChatManager.ts
  types/typography.d.ts
Labels: Missing Dev Review

#4675 chore(bundle): remove unused scroll lock package
  components/ui/Chat/Scroll/Scroll.html
  components/ui/SimpleScroll/SimpleScroll.html
  components/views/chat/chatbar/commands/preview/Preview.html
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/navigation/server/sidebar/Sidebar.html
  nuxt.config.js
  package.json
  plugins/thirdparty/vscrolllock.ts
Labels: Missing Dev Review

#4694 feat(pip): show screen/video/audio stream in preview
  components/ui/Global/Global.html
  components/ui/Pip/Pip.vue
  components/views/media/actions/Actions.less
  components/views/media/previewCall/PreviewCall.html
  components/views/media/previewCall/PreviewCall.less
  components/views/media/previewCall/PreviewCall.vue
  components/views/media/user/User.html
  components/views/media/user/User.less
  components/views/media/user/User.vue
  config.ts
Labels: Changes Requested

#4699 fix(friends): autofocus on desktop add friend
  components/views/friends/search/Search.vue
Labels: Missing Dev Review

#4700 fix(startup): don't await pubsub promises
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/users/UsersManager.ts
Labels: Missing Dev Review

#4701 fix(iridium): fix for new iridium types, remove unused imports
  .vscode/launch.json
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/files/FilesManager.ts
  libraries/Iridium/groups/Group.ts
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/users/UsersManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
  pages/index.vue
Labels: Missing Dev Review

#4692 feat(chat): file uploads and downloads
  components/interactables/Editable/Editable.vue
  components/ui/Chat/Embeds/File/File.html
  components/ui/Chat/Embeds/File/File.less
  components/ui/Chat/Embeds/File/File.vue
  components/ui/Chat/Embeds/File/types.d.ts
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.less
  components/ui/Chat/Image/Image.vue
  components/ui/Chat/Image/Overlay/Overlay.html
  components/ui/Chat/Image/Overlay/Overlay.vue
  components/ui/ImageContainer/ImageContainer.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/upload/preview/item/Item.html
  components/views/chat/chatbar/upload/preview/item/Item.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/attachments/Attachments.html
  components/views/chat/message/attachments/Attachments.less
  components/views/chat/message/attachments/Item/Item.html
  components/views/chat/message/attachments/Item/Item.less
  components/views/chat/message/attachments/Item/Item.vue
  components/views/files/grid/item/Item.html
  components/views/files/grid/item/Item.vue
  components/views/files/mobileList/item/Item.html
  components/views/files/mobileList/item/Item.vue
  components/views/files/view/View.html
  components/views/files/view/View.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  locales/en-US.js
  store/ui/mutations.ts
  store/ui/types.ts
Labels: Missing Dev Review

#4705 fix(ios): fixes for pinch, zoom, input zoom on ios
  assets/styles/base.less
  nuxt.config.js
Labels: Missing Dev Review

#4667 feat(jest): 100% coverages
  components/ui/Circle/Circle.test.ts
  components/ui/Circle/__snapshots__/Circle.test.ts.snap
  store/accounts/mutations.test.ts
  store/files/mutations.test.ts
  store/sounds/actions.test.ts
Labels: Changes Requested

#4709 fix(call): mute screen stream after it has ended
  libraries/WebRTC/Call.ts
Labels: Missing Dev Review

#4707 chore(friendList): added unread count back, adding timing to logger
  components/typography/Tag/Tag.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.less
  components/views/navigation/sidebar/list/item/Item.vue
  utilities/Logger.ts
Labels: Missing Dev Review

#4714 fix(editable): fix compatibility issues with languages that use compo…
  components/interactables/Editable/Editable.vue
  config.ts
Labels: Missing Dev Review

#4717 fix(regex): use 3rd party regex package for emojis
  components/views/chat/message/Message.vue
  components/views/navigation/sidebar/list/item/Item.vue
  config.ts
  package.json
  utilities/onlyHasEmoji.ts
Labels: Missing Dev Review, bug

#4712 feat(chat): lock scroll to bottom of chat
  components/ui/CaretDivider/CaretDivider.less
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  locales/en-US.js
Labels: Missing Dev Review

#4720 fix(chat): fix chat items prev message
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review

#4715 refactor(message): switch heavy methods to computed, remove unused code
  components/views/chat/message/Message.html
  components/views/chat/message/Message.vue
  libraries/ui/Markdown.ts
Labels: Missing Dev Review

#4718 refactor(unlock): switch anchor tag to button
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/Unlock.less
Labels: Missing Dev Review

#4711 fix(profile): send online instead of changed on update
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/users/UsersManager.ts
Labels: Missing Dev Review

#4721 feat(chat): copy/save image context menu in chat
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.vue
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/attachments/Item/Item.html
  components/views/chat/message/attachments/Item/Item.less
Labels: Missing Dev Review

#4722 chore: use headings in PR template markdown
  PULL_REQUEST_TEMPLATE.md
Labels: Missing Dev Review

#4727 fix(welcome): improve welcome modal styles
  components/ui/Popups/ErrorNetwork/ErrorNetwork.less
  components/ui/WelcomeModal/WelcomeModal.less
Labels: Missing Dev Review

#4713 feat(jest): 100% coverage for io-ts
  package.json
  utilities/__snapshots__/io-ts.test.ts.snap
  utilities/io-ts.test.ts
Labels: Missing Dev Review

#4731 feat(jest): 100% coverage for store/ui/getters
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/getters.test.ts
Labels: Missing Dev Review

#4737 feat(perf): startup & redirect changes
  components/views/navigation/sidebar/status/Status.html
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  middleware/authenticated.ts
  store/accounts/actions.ts
Labels: Missing Dev Review

#4742 fix(sidebar): reactivity fix for sidebar user status
  components/ui/User/State/State.vue
  components/views/navigation/sidebar/list/item/Item.html
  libraries/Iridium/users/UsersManager.ts
Labels: Missing Dev Review

#4739 fix(files): set iridium state on init
  libraries/Iridium/files/FilesManager.ts
Labels: Missing Dev Review

#4746 fix(sidebar-list-item): show subtitle text as single line
  assets/styles/framework/typography.less
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
Labels: Missing Dev Review, bug

#4745 fix(sidebar): typing status
  components/ui/User/State/State.less
  components/ui/User/State/State.vue
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4749 fix(conversations): remove listeners on beforeDestroy
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review, bug

#4758 chore(webrtc): Refactor webrtc
  components/views/chat/conversation/Conversation.html
  libraries/Iridium/utils.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/WebRTC/Call.ts
  libraries/WebRTC/Peer.ts
  libraries/WebRTC/Wire.ts
  libraries/WebRTC/bus/DirectWebRTCBus.ts
  libraries/WebRTC/bus/IridiumBus.ts
  libraries/WebRTC/bus/bus.ts
Labels: Missing Dev Review, draft

#4761 fix(message): send message to user before store
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4744 refactor(sidebar): apply padding to individual sidebar elements
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
Labels: Missing Dev Review

#4763 fix(webrtc): media UI + hangup during second incoming call
  components/views/media/Media.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/WebRTC/Call.ts
Labels: Missing Dev Review

#4756 fix(pip-shadow): removed shadow
  components/ui/Pip/Pip.vue
Labels: Missing Dev Review, QA tested

#4765 fix(sidebar): add margin to last list item child
  components/views/navigation/sidebar/list/item/Item.less
Labels: Missing Dev Review

#4767 fix(toolbar): hide chat search because its not ready
  components/views/navigation/toolbar/Toolbar.html
Labels: Missing Dev Review

#4747 feat(chat): new group member sidebar for group chats
  components/views/chat/UserList.vue
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
  locales/en-US.js
  pages/chat/Chat.html
  pages/chat/Chat.less
  pages/chat/_id.vue
Labels: ready to merge

#4770 fix(typing): typing bug
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4754 fix(sidebar-list-item): time section constraining last message width
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/list/List.less
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.less
Labels: Changes Requested, Missing Dev Review, bug

#4776 fix(calls): dont shrink mediastream
  components/views/media/Media.less
Labels: Missing Dev Review

#4781 fix(ui): large object shadows
  assets/styles/framework/glows.less
  components/ui/Modal/Modal.less
  components/ui/Pip/Pip.vue
Labels: Missing Dev Review

#4779 refactor(conversation): improve hooks to avoid repeated logic
  components/compositions/conversations.ts
  components/views/chat/UserList.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/navigation/mobile/toolbar/Toolbar.html
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  pages/chat/_id.vue
Labels: Missing Dev Review

#4773 chore(cleanup): pre-launch cleanup
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.html
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/accounts/index.vue
  components/views/settings/pages/privacy/Privacy.html
  cypress/e2e/privacy-page-toggles.js
  locales/en-US.js
  pages/mobile/settings/index.vue
Labels: Missing Dev Review

#4784 fix(chat): restore drag and drop functionality
  pages/chat/Chat.html
  pages/files/Files.html
Labels: Missing Dev Review

#4786 fix(sidebar): group icon flex bug
  components/ui/GroupIcon/GroupIcon.less
Labels: Missing Dev Review

#4774 fix(account): proper reactivity on profile update
  components/views/settings/pages/profile/index.vue
  libraries/Iridium/profile/ProfileManager.ts
  store/accounts/actions.ts
Labels: Missing Dev Review

#4797 chore(cypress): install cypress
  package.json
Labels: Missing Dev Review

#4760 fix(typing-indicator): fixed on safari
  assets/styles/base.less
  components/ui/User/State/State.less
  components/ui/User/State/State.vue
Labels: QA tested, ready to merge

#4798 fix(video): reactivity video
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review, QA tested

#4808 fix(chat): add better type guard to filter undefined
  components/compositions/conversations.ts
Labels: Missing Dev Review

#4800 fix(sidebar): prevent new message indicator from shrinking
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.less
Labels: Missing Dev Review

#4789 feat(chat): add typing indicator in groups and dms
  components/ui/Chat/TypingIndicator/TypingIndicator.html
  components/ui/Chat/TypingIndicator/TypingIndicator.less
  components/ui/Chat/TypingIndicator/TypingIndicator.vue
  components/views/chat/UserList.vue
  components/views/chat/chatbar/footer/Footer.html
  components/views/chat/chatbar/footer/Footer.less
  components/views/chat/chatbar/footer/Footer.vue
  components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.html
  components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.less
  components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.vue
  components/views/chat/chatbar/footer/connected/Connected.html
  components/views/chat/chatbar/footer/connected/Connected.less
  components/views/chat/chatbar/footer/connected/Connected.vue
  components/views/navigation/toolbar/Toolbar.html
  pages/chat/_id.vue
Labels: Missing Dev Review, QA tested

#4805 fix(chat): remove 'reply' from a reply's context menu
  components/views/chat/message/Message.vue
Labels: Missing Dev Review

#4810 fix(settings-profile): disable editing of username
  components/views/settings/pages/profile/Profile.html
Labels: Missing Dev Review

#4812 fix(modals): display coming soon modal above all others
  components/ui/Global/Global.html
Labels: Missing Dev Review, bug

#4807 fix(friend): add context menu functionality to friend component
  components/ui/ActionSheet/ActionSheet.vue
  components/ui/WelcomeModal/WelcomeModal.less
  components/views/friends/friend/Friend.html
  components/views/media/actions/Fullscreen.vue
Labels: Missing Dev Review

#4811 fix(chat): only scroll to bottom when adding children
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/replies/Replies.less
Labels: Missing Dev Review

#4816 fix(unread): fix max message time logic
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review

#4820 fix(userlist): style
  components/views/chat/UserList.vue
  pages/chat/_id.vue
  pages/friends/Friends.less
Labels: Missing Dev Review

#4815 fix(call): clear incoming call object when denying call
  components/compositions/conversations.ts
  components/ui/Loaders/ScaleLoader/ScaleLoader.vue
  components/views/chat/message/Message.vue
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.less
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4822 fix(sidebar): margin and hover
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/list/item/Item.less
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#4829 chore: restored vue.set
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
Labels: Missing Dev Review

#4830 fix(remove-friend): fixed sidebars' context menu
  components/views/navigation/sidebar/list/item/Item.vue
Labels: Changes Requested

#4766 fix(call): mute state and reactivity
  components/views/media/incomingCall/IncomingCall.html
  components/views/media/incomingCall/IncomingCall.vue
  components/views/media/user/User.html
  components/views/media/user/User.vue
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/WebRTC/Call.ts
  store/audio/actions.ts
Labels: Missing Dev Review

#4825 fix(files): aside hover and active css
  components/views/files/aside/List/List.html
  components/views/files/aside/List/List.less
Labels: Missing Dev Review

#4826 fix(chat): prevent image paste if no scan permission granted
  components/views/chat/chatbar/Chatbar.vue
Labels: Missing Dev Review

#4841 chore(update): update coming soon
  components/views/navigation/slimbar/Slimbar.html
  locales/en-US.js
Labels: Missing Dev Review

#4840 chore(groups): remove coming soon
  components/views/chat/message/actions/Actions.html
Labels: Missing Dev Review

#4839 chore(sign-up): coming soon buttons
  pages/setup/disclaimer/Disclaimer.html
Labels: Missing Dev Review, QA tested

#4847 fix(chat): fixes for message delivery
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4835 fix(chat): typing indicator
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4833 fix(webrtc): add connection timeout to fix some edge cases
  libraries/WebRTC/Wire.ts
Labels: Missing Dev Review

#4819 feat(early-access-banner): add and apply EarlyAccessBanner component
  assets/styles/framework/typography.less
  components/ui/Banner/Banner.html
  components/ui/Banner/Banner.less
  components/ui/Banner/Banner.vue
  components/ui/Chat/Encrypted/Encrypted.html
  components/ui/Chat/Encrypted/Encrypted.less
  components/ui/Chat/Encrypted/Encrypted.vue
  components/ui/EarlyAccessBanner/EarlyAccessBanner.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.vue
  locales/en-US.js
  nuxt.config.js
  pages/mobile/chat/_id.vue
  types/typography.d.ts
Labels: Missing Dev Review, merge blocked

#4794 fix(chat): offline msgs order
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4836 fix(chat): stream reactivity
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/WebRTC/Call.ts
Labels: Missing Dev Review

#4843 chore(qr): hide qr section
  components/views/friends/add/Add.html
  pages/mobile/friends/index.vue
Labels: Missing Dev Review

#4846 chore(update): update prettier ignore file
  .prettierignore
Labels: Missing Dev Review

#4824 feat(chat): unblock sending while file upload in progress
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
  locales/en-US.js
  plugins/thirdparty/persist.ts
  store/chat/__snapshots__/mutations.test.ts.snap
  store/chat/__snapshots__/state.test.ts.snap
  store/chat/mutations.test.ts
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
Labels: Missing Dev Review

#4844 chore(locales): improve grammar
  locales/en-US.js
Labels: Missing Dev Review

#4845 chore(update): update read me
  README.md
Labels: Missing Dev Review

#4857 fix(prettier): restore formatting for manager
  .prettierignore
Labels: Missing Dev Review

#4859 fix(chat): handle empty file
  components/views/chat/chatbar/upload/Upload.vue
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#4865 fix(calls): dont unmute screen share if no stream
  libraries/WebRTC/Call.ts
Labels: Missing Dev Review

#4864 fix(chat): scroll to bottom on send attachment
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
Labels: Missing Dev Review

#4858 fix(ui): settings pages and button style
  assets/styles/base.less
  assets/styles/framework/colors.less
  assets/styles/framework/glows.less
  components/interactables/Button/Button.less
  components/interactables/KeybindInput/KeybindInput.less
  components/ui/Modal/Modal.less
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.less
  components/views/settings/page/Page.less
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/sounds/Sounds.html
  components/views/settings/pages/audio/sounds/Sounds.less
  components/views/settings/pages/audio/sounds/item/Item.vue
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/keybinds/Keybinds.less
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/storage/Storage.html
  components/views/settings/profile/Banner.vue
  components/views/settings/profile/accounts/Accounts.vue
  components/views/settings/profile/accounts/Item/Item.less
  components/views/settings/profile/card/Card.less
  components/views/settings/unit/Unit.less
  locales/en-US.js
  pages/mobile/chat/_id.vue
  pages/mobile/settings/index.vue
Labels: Missing Dev Review

#4868 fix(webrtc): fix incoming & active call destroy on hangup
  libraries/Enums/types/webrtc.ts
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/NotificationManager.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/files/FilesManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/settings/SettingsManager.ts
  libraries/Iridium/users/UsersManager.ts
  libraries/Iridium/webrtc/WebRTCManager.ts
  libraries/Iridium/webrtc/types.ts
  libraries/WebRTC/Call.ts
  libraries/WebRTC/Wire.ts
  libraries/WebRTC/types.ts
Labels: QA tested

#4876 fix(mobile): fix slider swipe and overflow
  components/interactables/Volume/Volume.html
  pages/mobile/settings/index.vue
Labels: Missing Dev Review

#4878 chore(list): padding for empty friends box
  components/views/navigation/sidebar/list/List.less
Labels: Missing Dev Review

#4877 feat(chat): add link colors
  assets/styles/base.less
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.less
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.less
  components/views/settings/Sidebar.vue
Labels: Missing Dev Review
