Repository Satellite-im/Core-PWA, pull requests merged in 2022-05, with the labels that each got.

#3024 chore(naming): update naming
  components/ui/Global/Global.html
  components/views/chat/enhancers/glyphs/nav/Nav.vue
  components/views/glyphs/Glyphs.vue
  components/views/navigation/mobile/nav/Nav.vue
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/toolbar/Toolbar.html
  store/ui/types.ts
Labels: Ready for QA

#3036 feat(jest): 96% coverage for libraries/Solana/Solana
  libraries/Solana/Solana.test.ts
Labels: Missing Dev Review

#3037 feat(jest): 100% coverage for store/accounts/mutations
  store/accounts/mutations.test.ts
Labels: Missing Dev Review

#3039 fix(files): hide unused dropdown
  components/views/files/controls/Controls.html
Labels: Missing Dev Review

#3035 test(cypress): fixes and unskips for tests
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/files-features.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/support/commands.js
  layouts/friends.vue
Labels: draft

#3038 fix(files): pluralization logic plus translations for dir item count
  components/views/files/file/File.vue
  locales/en-US.js
Labels: Missing Dev Review

#3042 chore(emoji-picker): clean up component
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
  package.json
Labels: QA approved

#2983 fix(sidebar): change styles for friends request label
  assets/fonts/Poppins-Bold.ttf
  assets/fonts/SpaceMono-Bold.ttf
  components/views/navigation/sidebar/Sidebar.less
  layouts/default.vue
Labels: QA approved

#2899 chore(scrollbar): added new scrollbar to emote
  assets/styles/framework/colors.less
  assets/styles/thirdparty/multiselect.less
  components/ui/BadgedIcon/BadgedIcon.less
  components/ui/Chat/Embeds/VideoPlayer/VideoPlayer.less
  components/ui/SimpleScroll/SimpleScroll.html
  components/ui/SimpleScroll/SimpleScroll.less
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/marketplace/card/Card.less
  components/views/marketplace/glyphs/shop/item/Item.less
Labels: QA approved

#3051 feat(jest): 100% coverage for store/chat/actions
  store/chat/actions.test.ts
Labels: Missing Dev Review

#3050 feat(jest): 95% coverage for store/webrtc/mutations
  store/webrtc/mutations.test.ts
Labels: Missing Dev Review

#3054 chore(quick-reactions): fixed shadow hover color
  components/interactables/ContextMenu/ContextMenu.less
Labels: QA approved

#3012 refactor(chat): change messages markdown
  components/views/chat/group/Group.html
  components/views/chat/group/Group.less
  components/views/chat/group/Group.vue
  pages/chat/direct/_address.vue
  store/settings/actions.test.ts
  types/messaging.d.ts
  utilities/Messaging.ts
Labels: QA approved, temporary blocked checking something

#3059 chore(lint): minor lint
  components/views/files/list/List.html
Labels: Missing Dev Review

#3061 feat(jest): 100% coverage for store/friends/mutations
  store/friends/__snapshots__/mutations.test.ts.snap
  store/friends/mutations.test.ts
Labels: Missing Dev Review

#3055 fix(status): remove cut off of badge
  components/ui/User/State/State.less
Labels: Ready for QA

#3044 feat(jest): 36% coverage for libraries/Files/TextileFileSystem
  jest.config.js
  libraries/Files/test/TextileFileSystem.test.ts
  package.json
Labels: Missing Dev Review, QA approved

#3049 test(cypress): add fixes for cypress
  components/views/navigation/toolbar/Toolbar.html
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/files-features.js
  cypress/integration/import-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/privacy-page-toggles.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: draft

#3067 test(cypress): more timeout for conversation load
  cypress/support/commands.js
Labels: Missing Dev Review

#3074 feat(jest): 14% coverage for store/friends/actions
  store/friends/actions.test.ts
  store/friends/actions.ts
Labels: Missing Dev Review, QA approved

#3073 feat(jest): 18% coverage for store/groups/actions
  store/groups/actions.test.ts
  store/groups/actions.ts
Labels: Missing Dev Review, QA approved

#3083 feat(jest): 100% coverage branches for store/sounds/actions
  store/sounds/__snapshots__/actions.test.ts.snap
  store/sounds/actions.test.ts
Labels: Missing Dev Review

#3085 fix(reply): display correct quick profile
  components/views/chat/message/reply/Item/Item.html
  components/views/chat/message/reply/Reply.vue
Labels: QA approved

#3095 test(cypress): add videocall tests
  components/views/media/Media.html
  components/views/media/actions/Actions.html
  components/views/media/incomingCall/IncomingCall.html
  cypress-first-user.json
  cypress-second-user.json
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/integration/create-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/support/first-user/commands.js
  cypress/support/first-user/index.js
  cypress/support/second-user/commands.js
  cypress/support/second-user/index.js
  package.json
Labels: QA approved

#2997 feat(files): recent sidebar functionality
  components/ui/SimpleList/SimpleList.html
  components/ui/SimpleList/SimpleList.less
  components/ui/SimpleList/SimpleList.vue
  components/views/files/aside/Aside.html
  components/views/files/aside/Aside.vue
  components/views/files/aside/List/List.html
  components/views/files/aside/List/List.less
  components/views/files/aside/List/List.vue
  components/views/files/file/File.vue
  components/views/files/list/List.html
  components/views/files/list/row/Row.html
  components/views/files/list/row/Row.less
  components/views/files/list/row/Row.vue
  components/views/files/rename/Rename.vue
  components/views/files/tree/Tree.html
  components/views/files/tree/Tree.less
  components/views/files/tree/Tree.vue
  components/views/files/view/View.vue
  libraries/Enums/enums.ts
  libraries/Enums/types/fileSort.ts
  libraries/Enums/types/files.ts
  libraries/Files/Directory.ts
  libraries/Files/FilSystem.ts
  libraries/Files/test/Directory.test.ts
  libraries/Files/test/FilSystem.test.ts
  libraries/Files/test/__snapshots__/Directory.test.ts.snap
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
  locales/en-US.js
  pages/files/browse/index.vue
  plugins/thirdparty/filesize.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  types/ui/sidebar.d.ts
Labels: QA approved

#3094 feat(textile): configure textile via env
  config.ts
  libraries/Files/remote/textile/Bucket.ts
  libraries/Textile/BucketManager.ts
  libraries/Textile/IdentityManager.ts
Labels: QA approved

#3070 feat(textile): release the ui asap
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/slimbar/Slimbar.less
  components/views/navigation/slimbar/Slimbar.vue
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
  components/views/user/profile/About.vue
  layouts/default.vue
  libraries/Textile/TextileManager.ts
  middleware/authenticated.ts
  pages/chat/direct/Direct.html
  pages/chat/direct/_address.vue
  pages/chat/groups/Group.html
  pages/chat/groups/_id.vue
  pages/files/browse/Browse.html
  pages/files/browse/index.vue
  pages/friends/list/FriendsList.html
  pages/friends/mobile/add/index.vue
  pages/friends/mobile/incoming/index.vue
  store/accounts/actions.ts
  store/getters.ts
  store/textile/actions.ts
Labels: QA approved

#3080 fix(search): refine search match criterion
  components/views/chat/search/input/Input.vue
  components/views/chat/search/result/Result.vue
  libraries/SatelliteDB/SearchIndex.ts
  store/textile/actions.ts
  types/search/search.ts
Labels: Ready for QA

#3104 feat(jest): update tests according to code changes
  store/textile/actions.test.ts
Labels: Missing Dev Review

#3069 fix(friends): remove friend from indexed db
  components/ui/Unread/Unread.vue
  components/views/user/User.vue
  store/friends/actions.ts
Labels: QA approved, temporary blocked checking something

#3072 refactor(chat): remove unnecessary code and fix intellisense
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.vue
Labels: QA approved

#3125 feat(jest): remove skip for timeout issue on Solana
  libraries/Solana/Solana.test.ts
Labels: Missing Dev Review

#3126 feat(jest): 9% coverage for store/textile/actions
  store/textile/actions.test.ts
Labels: Missing Dev Review

#3103 fix(indexeddb): clear idb if user manually deleted localstorage
  config.ts
  libraries/SatelliteDB/SatelliteDB.ts
  pages/auth/unlock/index.vue
Labels: QA approved

#3130 test(cypress): draft fixes for cypress on CI
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/create-account.js
  cypress/support/commands.js
Labels: Missing Dev Review, draft

#3148 chore(jest): add jest tests
  jest.config.js
  store/conversation/__snapshots__/actions.test.ts.snap
  store/conversation/__snapshots__/mutations.test.ts.snap
  store/conversation/__snapshots__/state.test.ts.snap
  store/conversation/actions.test.ts
  store/conversation/mutations.test.ts
  store/conversation/state.test.ts
Labels: Missing Dev Review

#3123 feat(icons): add headphones-off-icon
  components/views/navigation/sidebar/controls/Controls.html
  components/views/navigation/sidebar/controls/Controls.vue
  package.json
Labels: QA approved

#3163 fix(webrtc): add configurable list of stun servers wrtc config
  config.ts
  libraries/WebRTC/Call.ts
Labels: QA approved

#3169 fix(input): improve a11y of interactablesswitch
  assets/styles/base.less
  components/interactables/Switch/Switch.html
  components/interactables/Switch/Switch.less
  components/interactables/Switch/Switch.vue
Labels: Missing Dev Review, QA approved

#3161 test(cypress): fixes for tests after videocall updates
  components/ui/Loaders/Message/Message.vue
  components/views/navigation/mobile/nav/Nav.html
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account.js
  cypress/integration/import-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
  cypress/support/first-user/commands.js
  cypress/support/second-user/commands.js
Labels: Missing Dev Review

#3173 test(cypress): skip and fixes cypress tests
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/files-features.js
  cypress/support/commands.js
Labels: Missing Dev Review, draft

#2913 chore(jest): add jest tests - 2908
  libraries/Textile/NotificationManager.test.ts
  libraries/Textile/__snapshots__/NotificationManager.test.ts.snap
  store/ui/__snapshots__/actions.test.ts.snap
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/actions.test.ts
  store/ui/mutations.test.ts
Labels: draft

#3174 chore(lint): lint
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/alerts/Alerts.html
  components/views/navigation/toolbar/alerts/alert/Alert.html
Labels: Missing Dev Review, draft

#3156 refactor(z-index): created layers system
  assets/styles/base.less
  assets/styles/framework/framework.less
  assets/styles/thirdparty/multiselect.less
  components/interactables/ContextMenu/ContextMenu.less
  components/interactables/ImageCropper/ImageCropper.less
  components/interactables/Input/Input.less
  components/interactables/QuickProfile/QuickProfile.less
  components/interactables/Select/Select.less
  components/ui/Chat/Image/Overlay/Overlay.less
  components/ui/Chat/Scroll/Scroll.less
  components/ui/ComingSoon/ComingSoon.less
  components/ui/DroppableWrapper/DroppableWrapper.less
  components/ui/GlowingCursorArea/GlowingCursorArea.less
  components/ui/InlineNotification/InlineNotification.less
  components/ui/Loaders/Updating/Updating.less
  components/ui/Modal/Modal.less
  components/ui/Popups/Error/Error.less
  components/ui/TypeAhead/TypeAhead.less
  components/views/chat/chatbar/Editable.vue
  components/views/chat/chatbar/commands/preview/Preview.less
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/message/actions/Actions.less
  components/views/chat/message/reactions/Reactions.less
  components/views/chat/search/input/Input.less
  components/views/chat/search/input/Input.vue
  components/views/chat/search/result/Result.less
  components/views/files/file/File.less
  components/views/files/view/View.less
  components/views/friends/quick/Quick.less
  components/views/group/aside/Aside.less
  components/views/group/create/Create.less
  components/views/group/icon/GroupIcon.less
  components/views/group/invite/Invite.less
  components/views/marketplace/filterbox/Filterbox.less
  components/views/media/Media.less
  components/views/media/actions/settings/Settings.html
  components/views/media/actions/settings/Settings.less
  components/views/media/user/User.less
  components/views/message/Friend.less
  components/views/navigation/mobile/nav/Nav.less
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/server/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/slimbar/Slimbar.less
  components/views/servers/create/Create.less
  components/views/settings/pages/profile/Profile.less
  components/views/user/User.less
  components/views/user/create/Create.less
  components/views/wallet/mini/Mini.less
  layouts/Layout.less
Labels: QA approved

#3133 fix(user): prevent profile picture drag
  assets/styles/framework/ui.less
  components/interactables/AsideMenu/AsideMenu.less
  components/interactables/Select/Select.less
  components/ui/CaretDivider/CaretDivider.less
  components/ui/Chat/Image/Image.less
  components/ui/Circle/Circle.html
  components/ui/Circle/Circle.less
  components/ui/DroppableWrapper/DroppableWrapper.less
  components/ui/GlowingCursorArea/GlowingCursorArea.less
  components/ui/User/User.less
  components/views/chat/chatbar/Editable.vue
  components/views/chat/chatbar/footer/Footer.less
  components/views/chat/enhancers/Enhancers.less
  components/views/files/aside/List/List.less
  components/views/files/list/List.less
  components/views/friends/friend/Friend.less
  components/views/group/clickable/Clickable.less
  components/views/message/Friend.less
  components/views/navigation/toolbar/Toolbar.less
  components/views/user/User.less
  layouts/Layout.less
Labels: Changes Requested

#3190 feat(jest): 84% coverage for store/ui
  store/ui/__snapshots__/actions.test.ts.snap
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/actions.test.ts
  store/ui/actions.ts
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#3187 fix(glyph): send glyph to active chat
  components/views/chat/enhancers/glyphs/item/Item.vue
Labels: Ready for QA

#3183 fix(files): hide sidebar options that 100% wont be ready
  components/views/files/aside/Aside.html
Labels: Missing Dev Review

#3195 test(cypress): add swipe tests and new accounts
  cypress/fixtures/test-data-accounts.json
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/files-features.js
  cypress/integration/mobiles-responsiveness.js
  cypress/support/commands.js
Labels: Missing Dev Review

#3177 fix(notification): remove glow from clear all button
  components/views/navigation/toolbar/Toolbar.vue
  components/views/navigation/toolbar/alerts/Alerts.html
  components/views/navigation/toolbar/alerts/Alerts.less
  store/textile/mutations.ts
Labels: QA approved

#3165 fix(edit): edit was not getting friends textile key anymore
  components/views/chat/message/Message.vue
Labels: Ready for QA

#3159 fix(footer): adds offline text if user is offline in footer
  components/typography/Text/Text.vue
  components/views/chat/chatbar/footer/is-connected/Connected.html
  components/views/chat/chatbar/footer/is-connected/Connected.less
  components/views/chat/chatbar/footer/is-connected/Connected.vue
  locales/en-US.js
  store/conversation/getters.ts
Labels: Changes Requested

#3196 feat(calls): properly unbind all listeners after call closure
  components/views/media/incomingCall/IncomingCall.html
  components/views/navigation/toolbar/Toolbar.html
  libraries/WebRTC/Call.ts
  libraries/WebRTC/WebRTC.ts
  store/textile/mutations.ts
  store/webrtc/actions.ts
Labels: QA approved, OMG SO EXCITED

#3204 feat(calls): properly unbind all listeners after call closure
  components/views/media/incomingCall/IncomingCall.html
  components/views/navigation/toolbar/Toolbar.html
  libraries/WebRTC/Call.ts
  libraries/WebRTC/WebRTC.ts
  store/textile/mutations.ts
  store/webrtc/actions.ts
Labels: Missing Dev Review

#3207 test(cypress): add save image test and updates to mobiles
  cypress/integration/chat-images-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/support/commands.js
Labels: Missing Dev Review

#3154 refactor(inputs): refactor InteractablesInputGroup
  components/interactables/InputGroup/InputGroup.html
  components/interactables/InputGroup/InputGroup.less
  components/interactables/InputGroup/InputGroup.vue
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.vue
  components/views/files/controls/Controls.html
  components/views/files/rename/Rename.html
  components/views/friends/friend/Friend.vue
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/accounts/index.vue
Labels: Ready for QA

#3215 fix(share): remove share for alpha prep
  components/views/files/file/File.vue
  components/views/files/list/row/Row.vue
  components/views/files/view/View.html
Labels: Ready for QA

#3127 feat(markdown): added markdown preview in sidebar
  assets/styles/base.less
  components/views/user/User.html
  components/views/user/User.less
  components/views/user/User.vue
Labels: QA approved

#3216 fix(toolbar): disable group call button
  components/views/group/clickable/Clickable.vue
  components/views/navigation/toolbar/Toolbar.html
  locales/en-US.js
Labels: Ready for QA, QA approved

#3157 fix(chat): focus on chatbar on send message click
  components/views/user/User.vue
  layouts/chat.vue
Labels: Ready for QA

#3223 fix(files): width and height for files image view
  components/views/files/view/View.less
Labels: Ready for QA

#3214 fix(bundle): remove v clipboard
  components/views/navigation/sidebar/status/Status.html
  components/views/navigation/sidebar/status/Status.vue
  nuxt.config.js
  package.json
  plugins/thirdparty/clipboard.ts
Labels: QA approved

#3217 fix(hounddog): copy houndog logic to store getters
  store/friends/__snapshots__/state.test.ts.snap
  store/friends/getters.ts
  store/friends/state.ts
  store/friends/types.ts
  types/ui/friends.d.ts
Labels: QA tested

#3062 feat(solana): error popup shows whenever an error occurs to prevent infinite loading
  components/ui/Popups/ErrorNetwork/ErrorNetwork.html
  components/ui/Popups/ErrorNetwork/ErrorNetwork.less
  components/ui/Popups/ErrorNetwork/ErrorNetwork.vue
  config.ts
  layouts/default.vue
  locales/en-US.js
  pages/auth/register/index.vue
  pages/index.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: QA tested

#3235 fix(settings): correct audio input/output volume control position
  components/views/settings/pages/audio/Audio.html
Labels: Ready for QA

#3234 fix(style): disable font ligatures
  assets/styles/base.less
Labels: Ready for QA

#3222 feat(friends): autofocus add friend input
  components/interactables/InputGroup/InputGroup.vue
  components/views/friends/add/Add.html
Labels: Ready for QA

#3252 feat(jest): 100% branch coverage for store/chat/mutations
  store/chat/__snapshots__/mutations.test.ts.snap
  store/chat/mutations.test.ts
Labels: Missing Dev Review

#3251 feat(jest): 37% coverage for store/conversation/mutations
  store/conversation/mutations.test.ts
Labels: Missing Dev Review

#3250 feat(jest): 80% coverage for store/ui/mutations
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#3221 fix(notification): clear alert number on open
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  components/views/navigation/toolbar/alerts/Alerts.html
  components/views/navigation/toolbar/alerts/Alerts.vue
  components/views/navigation/toolbar/alerts/alert/Alert.html
  components/views/navigation/toolbar/alerts/alert/Alert.less
  components/views/navigation/toolbar/alerts/alert/Alert.vue
  libraries/ui/Alerts.ts
  store/ui/actions.test.ts
  store/ui/actions.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
Labels: QA tested

#3109 fix(chat): auto scroll to the end of the chat, hide older messages in…
  components/ui/Chat/Scroll/Scroll.vue
  layouts/chat.vue
Labels: Ready for QA

#3254 test(cypress): skips tests due to solana issues
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/create-account.js
  cypress/integration/files-features.js
  cypress/integration/pin-unlock-validations.js
Labels: Missing Dev Review, draft

#3247 fix(nametag): fixed tag color
  assets/styles/base.less
  assets/styles/framework/colors.less
Labels: QA tested

#3238 fix(settings): remove mobile redirect to profile modal settings
  components/views/settings/modal/Modal.vue
Labels: QA tested

#3160 fix(status): position and size of status
  components/ui/Circle/Circle.vue
  components/ui/User/State/State.less
  components/ui/User/State/State.vue
  components/views/chat/group/Group.html
  components/views/chat/message/reply/Item/Item.html
  components/views/group/aside/Aside.html
  components/views/group/icon/GroupIcon.html
  components/views/media/user/User.html
  components/views/navigation/toolbar/Toolbar.html
  components/views/wallet/recent/item/Item.html
Labels: QA tested

#3233 fix(settings): limit modal width/height
  components/views/settings/modal/Modal.less
  components/views/settings/modal/Modal.vue
Labels: QA tested

#3220 feat(media): update mute indicator style
  components/views/media/user/User.html
  components/views/media/user/User.less
Labels: QA tested

#3256 test(cypress): skip tests failing due to textile
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/privacy-page-toggles.js
Labels: Missing Dev Review, draft

#3257 chore(typo): fix typo - UNINITIALIZED
  libraries/Solana/FriendsProgram/FriendsProgram.ts
  libraries/Solana/FriendsProgram/FriendsProgram.types.ts
Labels: Ready for QA

#3170 chore(userstatus): fixed user state display while changing chat
  components/ui/Unread/Unread.vue
  components/views/group/clickable/Clickable.html
  components/views/group/clickable/Clickable.less
  components/views/group/clickable/Clickable.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/user/User.vue
Labels: QA tested, temporary blocked checking something

#3245 refactor(friends): move sort methods into getters
  pages/friends/list/index.vue
  pages/friends/mobile/add/index.vue
  pages/friends/mobile/block/index.vue
  store/friends/getters.ts
Labels: QA tested, temporary blocked checking something

#3258 chore(jest): organize jest imports
  libraries/Textile/BucketManager.test.ts
  libraries/Textile/GroupChatManager.test.ts
  libraries/Textile/NotificationManager.test.ts
  libraries/Textile/encoders.test.ts
  libraries/ui/Markdown.test.ts
  store/chat/actions.test.ts
  store/groups/actions.test.ts
  store/settings/actions.test.ts
  store/settings/state.test.ts
  store/textile/actions.test.ts
  store/textile/getters.test.ts
  store/ui/actions.test.ts
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
  utilities/ConsoleWarning.test.ts
  utilities/EnvInfo.test.ts
  utilities/HotkeyList.test.ts
  utilities/Hounddog.test.ts
  utilities/Messaging.test.ts
Labels: Missing Dev Review

#3259 chore(lint): minor lint
  components/views/media/user/User.less
Labels: Missing Dev Review

#3264 feat(jest): 100% coverage for store/conversation/getters
  store/conversation/__snapshots__/getters.test.ts.snap
  store/conversation/getters.test.ts
Labels: Missing Dev Review

#3279 test(cypress): skip tests failing due to textile
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/import-account-negative-tests.js
  cypress/integration/mobiles-responsiveness.js
Labels: Missing Dev Review

#3280 test(cypress): skip one test on mobiles
  cypress/integration/mobiles-responsiveness.js
Labels: Missing Dev Review

#3260 chore(imports): remove not used imports
  libraries/Solana/Solana.ts
  libraries/Solana/SolanaManager/SolanaManager.ts
  libraries/WebRTC/encoders.ts
  store/chat/getters.ts
  store/ui/types.ts
  store/webrtc/types.ts
  utilities/Hounddog.ts
  utilities/Messaging.ts
Labels: QA tested

#3218 feat(sounds): combine deafen/undeafen into one toggle control
  components/views/settings/pages/audio/sounds/Sounds.html
  components/views/settings/pages/audio/sounds/Sounds.vue
Labels: Ready for QA

#3287 fix(chat): user navigate to chat
  components/ui/Unread/Unread.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/user/User.vue
Labels: Ready for QA

#3262 fix(friends): fix disabled add friends input bug
  components/interactables/ContextMenu/ContextMenu.vue
  components/interactables/Input/Input.html
  components/interactables/Input/Input.vue
  components/views/friends/add/Add.html
  components/views/friends/add/Add.vue
  components/views/friends/friend/Friend.vue
Labels: Ready for QA

#3295 feat(jest): 100% coverage for store/conversation/mutations
  store/conversation/mutations.test.ts
Labels: Missing Dev Review

#3297 feat(jest): 94% coverage for store/conversation/action
  store/conversation/actions.test.ts
Labels: Missing Dev Review

#3294 feat(account): button to delete account on login screen
  components/views/settings/pages/storage/index.vue
  locales/en-US.js
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/Unlock.less
  pages/auth/unlock/index.vue
  store/settings/actions.test.ts
  store/settings/actions.ts
  store/settings/mutations.test.ts
  store/settings/mutations.ts
Labels: Missing Dev Review

#3299 fix(toolbar): disable call button when in call
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
Labels: QA tested

#3298 fix(search): filter selected by user address
  components/views/settings/pages/user/Search.vue
Labels: Ready for QA

#3162 fix(startup): do not await promises in accounts/startup
  store/accounts/actions.ts
Labels: Ready for QA

#3307 fix(login): more spacing for delete account link
  pages/auth/unlock/Unlock.less
Labels: Ready for QA

#3324 fix(spacing): reduce link spacing for signin delete account link
  pages/auth/unlock/Unlock.less
Labels: Missing Dev Review

#3322 feat(jest): 100% branch coverage for store/friends/mutations
  store/friends/__snapshots__/mutations.test.ts.snap
  store/friends/mutations.test.ts
Labels: Missing Dev Review

#3321 feat(jest): 84% coverage for store/video/actions
  store/video/actions.test.ts
Labels: Missing Dev Review

#3319 fix(modal): modal background blur
  assets/styles/framework/blurs.less
Labels: testing blocked

#3306 fix(media): user video class/styling
  components/views/media/user/User.html
  components/views/media/user/User.less
Labels: testing blocked

#3227 refactor(tooltip): changed and improved tooltips component
  assets/styles/base.less
  assets/styles/framework/framework.less
  components/interactables/Button/Button.html
  components/ui/ComingSoon/ComingSoon.html
  components/ui/ComingSoon/ComingSoon.less
  components/ui/Unread/Unread.html
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/message/actions/Actions.html
  components/views/files/aside/Aside.html
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.less
  components/views/files/view/View.html
  components/views/friends/friend/Friend.html
  components/views/friends/mobile/list.vue
  components/views/group/aside/Aside.html
  components/views/media/actions/Actions.html
  components/views/media/actions/settings/Settings.html
  components/views/media/heading/Heading.html
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/server/sidebar/channels/group/Group.html
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/controls/Controls.html
  components/views/navigation/sidebar/status/Status.html
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/toolbar/Toolbar.html
  locales/en-US.js
  nuxt.config.js
  package.json
  plugins/thirdparty/tooltip.ts
Labels: testing blocked

#3246 refactor(friends): move friend method from hounddog into getters
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/chat/group/Group.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/reply/Item/Item.vue
  components/views/files/upload/Upload.vue
  pages/chat/direct/_address.vue
  plugins/local/classLoader.ts
  store/friends/actions.test.ts
  store/friends/actions.ts
  store/friends/getters.ts
  types/store/store.ts
  utilities/Hounddog.test.ts
  utilities/Hounddog.ts
  utilities/__snapshots__/Hounddog.test.ts.snap
Labels: Ready for QA

#3327 fix(solana): fix breaking change in @solana/web3.js
  package.json
Labels: Missing Dev Review

#3236 fix(sidebar): fix toggle mute dispatch
  components/views/media/actions/Actions.vue
  components/views/media/user/User.html
  components/views/media/user/User.vue
  components/views/navigation/sidebar/controls/Controls.vue
  store/audio/actions.ts
  store/webrtc/actions.ts
Labels: Changes Requested

#3323 feat(account): add copy phrase button to settings page
  components/typography/NumberedWord/NumberedWord.less
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/accounts/Accounts.less
  components/views/settings/pages/accounts/index.vue
  locales/en-US.js
Labels: Ready for QA

#3316 fix(user): general refactor, show call options if user is online
  components/views/user/User.html
  components/views/user/User.vue
  types/ui/user.d.ts
Labels: Ready for QA

#3107 feat(files): rework store nsfw, scan consent, update diff instances
  components/views/chat/chatbar/Chatbar.html
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.vue
  components/views/files/file/File.vue
  components/views/files/rename/Rename.vue
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.less
  components/views/files/upload/Upload.vue
  components/views/files/view/View.vue
  components/views/media/actions/settings/Settings.vue
  components/views/settings/pages/audio/index.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
  layouts/chat.vue
  layouts/files.vue
  libraries/Files/FilSystem.ts
  libraries/Files/remote/textile/Bucket.ts
  libraries/Files/test/FilSystem.test.ts
  libraries/Textile/UserManager.ts
  libraries/Textile/schema.ts
  locales/en-US.js
  pages/files/browse/index.vue
  plugins/thirdparty/persist.ts
  store/accounts/actions.ts
  store/audio/types.ts
  store/settings/actions.test.ts
  store/settings/actions.ts
  store/settings/mutations.test.ts
  store/settings/mutations.ts
  store/settings/state.ts
  store/settings/types.ts
  store/textile/__snapshots__/state.test.ts.snap
  store/textile/actions.test.ts
  store/textile/actions.ts
  store/textile/mutations.ts
  store/textile/state.ts
  store/textile/types.ts
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/getters.test.ts
  store/ui/getters.ts
  types/store/store.ts
  types/textile/user.ts
Labels: Changes Requested

#3343 feat(jest): fixed warnings, 8% coverage for store/textile/actions
  store/textile/actions.test.ts
Labels: Missing Dev Review

#3353 feat(jest): 100% coverage for store/friends/getters
  store/friends/getters.test.ts
Labels: Missing Dev Review

#3357 chore(jest): remove dup keys on jest test
  store/accounts/mutations.test.ts
Labels: Missing Dev Review

#3354 test(cypress): update cypress
  cypress/fixtures/test-data-accounts.json
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account.js
  cypress/integration/import-account-negative-tests.js
  cypress/integration/localstorage-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/support/commands.js
Labels: Missing Dev Review

#3356 chore(jest): organize imports on jest
  store/accounts/actions.test.ts
  store/audio/actions.test.ts
  store/conversation/actions.test.ts
  store/conversation/getters.test.ts
  store/conversation/mutations.test.ts
  store/friends/actions.test.ts
  store/friends/getters.test.ts
  store/settings/actions.test.ts
  store/video/actions.test.ts
Labels: Missing Dev Review

#3355 chore(jest): minor update file
  jest-setup.js
Labels: Missing Dev Review

#3345 fix(accounts): resolve for loop key warning
  components/views/settings/pages/accounts/Accounts.html
Labels: Missing Dev Review

#3352 fix(toolbar): add tooltip to alerts
  components/views/navigation/toolbar/Toolbar.html
  locales/en-US.js
Labels: QA tested

#3351 fix(controls): change controls tooltips
  components/views/media/actions/Actions.html
  components/views/navigation/sidebar/controls/Controls.html
  locales/en-US.js
Labels: QA tested

#3367 chore(cypress): add comment hash
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/localstorage-validations.js
Labels: Missing Dev Review

#3344 fix(switch): add white circle for locked, enabled switch
  components/interactables/Switch/Switch.html
  components/interactables/Switch/Switch.less
Labels: QA tested

#3374 chore(add): add name on github action
  .github/workflows/add-conflicts-label.yml
Labels: Missing Dev Review

#3373 chore(githubAction): fix typos
  .github/workflows/fix-typos.yml
Labels: Missing Dev Review

#3267 fix(notifications): stop alert notification if alert would notify of message of current active chat
  libraries/Textile/NotificationManager.ts
  store/textile/actions.ts
  store/ui/actions.test.ts
  store/ui/actions.ts
Labels: QA tested

#3308 fix(friends): show error toast if friend request not found
  components/views/friends/friend/Friend.vue
  locales/en-US.js
Labels: Ready for QA

#3347 fix(messages): remove unused imageMessage, switch to fileMessage
  components/ui/Chat/Image/Image.vue
  components/views/chat/message/Message.html
  libraries/Textile/__snapshots__/encoders.test.ts.snap
  libraries/Textile/encoders.test.ts
  libraries/Textile/encoders.ts
  store/ui/mutations.ts
  store/ui/types.ts
  types/messaging.d.ts
  types/textile/mailbox.ts
  utilities/Messaging.test.ts
  utilities/__snapshots__/Messaging.test.ts.snap
Labels: QA tested

#3314 feat(toast): add error toast styling
  assets/styles/base.less
Labels: Ready for QA

#3366 fix(ios): fix overlap of iOS status bar on file overlay
  components/views/files/view/View.less
Labels: Ready for QA

#3377 feat(jest): 87% coverage for store/ui/actions
  store/ui/actions.test.ts
Labels: Missing Dev Review

#3317 fix(message): disable save on empty message
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/edit/Edit.less
  components/views/chat/message/edit/Edit.vue
  locales/en-US.js
Labels: Ready for QA

#3349 fix(chat): change enhancers position
  assets/styles/framework/ui.less
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/enhancers/Enhancers.less
  layouts/Layout.less
Labels: QA tested

#3380 fix(spoilers): transparent background on open spoilers
  assets/styles/base.less
  components/views/chat/message/Markdown.vue
  components/views/chat/message/Message.less
  components/views/user/User.vue
Labels: Ready for QA

#3376 chore(upload): remove unused computed
  components/views/files/upload/Upload.vue
Labels: Changes Requested

#3390 chore(cypress): docker cypress pair testing
  .github/workflows/cypress-docker-pair-testing.yml
Labels: Missing Dev Review

#3394 chore(lint): lint actions
  .github/workflows/cypress-docker-pair-testing.yml
  .github/workflows/fix-typos.yml
Labels: Missing Dev Review

#3393 test(cypress): add logout test
  cypress/integration/localstorage-validations.js
Labels: Missing Dev Review
