Repository Satellite-im/Core-PWA, pull requests merged in 2022-03, with the labels that each got.

#1746 fix(chat): fix profile different bubble color issue
  utilities/Messaging.ts
Labels: QA approved

#1749 fix(chat): fix big emoji with letter c
  components/views/chat/message/Message.vue
  config.ts
Labels: Ready for QA

#1740 fix(filesUpgrade): dull the storage space upgrade button
  components/views/files/aside/Aside.html
  components/views/files/aside/Aside.less
  locales/en-US.js
Labels: QA approved

#1716 fix(files): show image if possible and css cleanup
  components/views/files/file/File.vue
  components/views/files/view/View.html
  components/views/files/view/View.less
  components/views/files/view/View.vue
Labels: QA approved

#1500 fix(encryption): encrypt group chat messages
  libraries/Textile/GroupChatManager.ts
  libraries/Textile/TextileManager.ts
  locales/en-US.js
  mock/groups.ts
  store/accounts/types.ts
  types/ui/core.d.ts
Labels: QA approved, temporary blocked checking something

#1755 feat(jest): 100% coverage for store/getters AP-964
  store/getters.test.ts
Labels: Missing Dev Review, QA approved

#1752 chore(packageJson): update package deps, move dev deps
  package.json
  utilities/__snapshots__/Messaging.test.ts.snap
Labels: temporary blocked checking something

#1751 fix(mobileSettingSwipe): close setting modal upon refresh
  layouts/chat.vue
Labels: Missing Dev Review, QA approved

#1762 fix(image): fix crashes when you click an image in chat
  components/ui/Chat/Image/Image.html
Labels: QA approved

#1679 fix(chat): mobile adaptation of chat toolbar
  components/interactables/QuickProfile/QuickProfile.vue
  components/ui/User/State/State.vue
  components/views/chat/group/Group.vue
  components/views/chat/message/reply/Reply.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
  store/ui/actions.ts
  store/ui/mutations.ts
  store/ui/types.ts
Labels: temporary blocked checking something

#1768 feat(jest): 100% coverage for mock/search.ts
  mock/tests/__snapshots__/search.test.ts.snap
  mock/tests/search.test.ts
Labels: QA approved

#1753 feat(files): add support for last modified timestamp
  components/views/files/list/List.html
  components/views/files/list/List.vue
  components/views/media/incomingCall/IncomingCall.vue
  config.ts
  libraries/Files/Directory.ts
  libraries/Files/Fil.ts
  libraries/Files/FilSystem.ts
  libraries/Files/abstracts/Item.abstract.ts
  libraries/Files/types/filesystem.ts
  pages/files/browse/Browse.html
Labels: QA approved

#1757 feat(jest): 35% coverage for store/accounts/actions
  package.json
  store/accounts/actions.test.ts
  store/accounts/actions.ts
Labels: Missing Dev Review, QA approved

#1771 chore(typo): fix typo
  config.ts
Labels: Missing Dev Review, QA approved

#1770 fix(upload): image upload
  components/views/files/upload/Upload.vue
Labels: QA approved

#1773 chore(dotenv): enable dev webtorrent tracker with env var
  .env.example
  config.ts
  package.json
Labels: Missing Dev Review

#1774 fix(contextMenu): fix contextMenu error when clicking out of bounds
  components/interactables/ContextMenu/ContextMenu.vue
Labels: Ready for QA

#1763 fix(files): reduce max height of fullscreen file view
  components/views/files/filepath/Filepath.less
  components/views/files/view/View.less
Labels: Ready for QA

#1775 fix(storeTextileActions): reset message load state on init
  store/textile/actions.ts
Labels: QA approved

#1778 fix(collapse): allow sidebar toggle in chat
  components/views/navigation/toolbar/Toolbar.less
  layouts/Layout.less
Labels: QA approved

#1758 fix(base): fix swipe refresh issue AP-747
  assets/styles/base.less
Labels: QA approved

#1780 feat(jest): 93% coverage for utilities/Messaging.ts
  utilities/Messaging.test.ts
  utilities/Messaging.ts
  utilities/__snapshots__/Messaging.test.ts.snap
Labels: Ready for QA

#1605 chore(update): hide blocked friends
  pages/friends/list/FriendsList.html
  pages/friends/list/index.vue
Labels: Missing Dev Review, QA approved

#1777 fix(fileTypes): add support for common file types
  libraries/Files/types/file.ts
Labels: QA approved

#1782 fix(embeddedVideo): fix parsing youtube video url
  components/ui/Chat/Embeds/EmbeddedLinkContent/EmbeddedLinkContent.vue
Labels: Missing Dev Review, QA approved

#1787 test(cypress): add changes to cypressjson file to improve tests
  cypress.json
  package.json
Labels: Missing Dev Review, QA approved

#1796 fix(toolbar): grey out options & update coming soon buttons
  components/views/navigation/toolbar/Toolbar.html
  locales/en-US.js
Labels: Missing Dev Review, QA approved

#1786 chore(gifs): hide gifs
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
Labels: QA approved

#1797 feat(jest): 19% coverage for Bucket.ts
  jest.config.js
  libraries/Files/test/Bucket.test.ts
Labels: QA approved

#1798 feat(jest): 100% coverage for Filesize.ts
  utilities/Filesize.test.ts
  utilities/__snapshots__/Filesize.test.ts.snap
Labels: QA approved

#1800 chore(update): minor update
  .env.example
  README.md
Labels: Missing Dev Review, QA approved

#1791 fix(settings): show full sidebar in settings on mobile
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.less
  components/views/settings/modal/Modal.vue
Labels: QA approved

#1803 fix(settings): fix highlight issue on mobile settings modal
  components/views/settings/Sidebar.vue
Labels: QA approved

#1572 fix(groupChat): all message types working in group chats
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/files/upload/Upload.vue
  libraries/Textile/GroupChatManager.ts
  pages/chat/groups/_id.vue
  store/textile/actions.ts
Labels: temporary blocked checking something

#1784 fix(user): fix mute icon position issue AP-981
  components/views/media/user/User.less
Labels: QA approved

#1804 feat(jest): 100% coverage for store/chat/actions AP-1000
  store/chat/actions.test.ts
Labels: Missing Dev Review, QA approved

#1809 feat(jest): 100% coverage for ServerProgram.layout.ts
  libraries/Solana/ServerProgram/ServerProgram.layout.test.ts
  libraries/Solana/ServerProgram/__snapshots__/ServerProgram.layout.test.ts.snap
Labels: Missing Dev Review, QA approved

#1810 chore(jest): remove skipped tests jest
  components/mixins/UI/ContextMenu.test.ts
  components/mixins/UserPermissions/index.test.ts
  libraries/Solana/ServerProgram/ServerProgram.layout.test.ts
  libraries/Solana/Solana.test.ts
  libraries/SoundManager/SolanaManager.test.ts
Labels: QA approved

#1805 fix(chat): chatbar push bottom while calling
  layouts/Layout.less
Labels: QA approved

#1811 fix(privacy): change the toggle default setting
  assets/styles/base.less
  pages/setup/privacy/Privacy.html
  store/accounts/__snapshots__/state.test.ts.snap
  store/accounts/state.ts
Labels: QA approved

#1808 fix(settings): fix storage clearing issue
  plugins/thirdparty/persist.ts
  store/settings/actions.ts
  store/settings/mutations.ts
  store/settings/state.ts
  store/settings/types.ts
Labels: QA approved, temporary blocked checking something

#2260 fix(files): prevent folder name issue
  components/views/files/controls/Controls.vue
  locales/en-US.js
Labels: Ready for QA

#2265 feat(jest): 100% coverage for mock/servers.ts
  mock/tests/__snapshots__/servers.test.ts.snap
  mock/tests/servers.test.ts
Labels: QA approved

#2267 fix(textile): resubscribe textile if it is unsubscribed
  store/webrtc/actions.ts
Labels: Ready for QA

#1814 feat(jest): 89% coverage for middleware/authenticated.ts AP-570
  middleware/__snapshots__/authenticated.test.ts.snap
  middleware/authenticated.test.ts
Labels: QA approved

#1795 fix(profile): fix close button issue on ios device
  components/views/user/profile/Profile.less
Labels: QA approved

#2264 fix(marketplace): swiper marketplace modal, fix broken styles on mobile
  components/views/marketplace/Marketplace.html
  components/views/marketplace/Marketplace.less
  components/views/marketplace/Marketplace.vue
  components/views/marketplace/glyphs/Glyphs.less
Labels: QA approved

#2261 feat(files): Improve UX for files list view
  components/views/files/list/List.html
  components/views/files/list/List.less
  components/views/files/list/List.vue
  components/views/files/row/Row.html
  components/views/files/row/Row.less
  components/views/files/row/Row.vue
Labels: QA approved, temporary blocked checking something

#1790 feat(files): encrypted bucket for personal files
  components/views/files/file/File.html
  components/views/files/file/File.less
  components/views/files/file/File.vue
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.less
  components/views/files/filepath/Filepath.vue
  components/views/files/view/View.html
  components/views/files/view/View.vue
  config.ts
  jest.config.js
  libraries/Files/Fil.ts
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/abstracts/Item.abstract.ts
  libraries/Files/remote/textile/Bucket.ts
  libraries/Files/test/Bucket.test.ts
  libraries/Files/test/TextileFileSystem.test.ts
  libraries/Files/types/filesystem.ts
  package.json
  plugins/local/classLoader.ts
  store/textile/actions.test.ts
  store/textile/actions.ts
  tsconfig.json
  types/modules/skaler.d.ts
Labels: QA approved

#1682 fix(webrtc): hangs up call when accepting a new call
  components/ui/Global/Global.vue
  components/views/media/Media.html
  components/views/media/Media.vue
  components/views/media/actions/Actions.vue
  components/views/navigation/sidebar/live/Live.vue
Labels: QA approved

#2287 chore(cypress): import luis work
  README.md
  cypress.json
  cypress/fixtures/test-file.txt
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/import-account-negative-tests.js
  cypress/integration/import-account.js
  cypress/integration/localstorage-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pair-chat/chat-first-user.js
  cypress/integration/pair-chat/chat-second-user.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
Labels: Ready for QA

#2288 chore(cypress): update files
  cypress/plugins/index.js
  cypress/support/index.js
Labels: Missing Dev Review

#2289 chore(cypress): rename folder
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Create Account - Buffering screen after submission.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Create Account - Create or Import Account Selection screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Create Account - PIN screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Create Account - Privacy Settings screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Create Account - User Input Screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Buffering screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Click on emojis.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Click on glyphs.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Create or Import Account Selection screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Enter passphrase screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Go to a chat.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Go to files.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Go to friends.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Main Screen Loaded.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - PIN screen.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Screen after adding recovery seed.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - Developer - App Info.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - General - Accounts & Devices.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - General - Audio & Video.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - General - Keybinds.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - General - Personalize.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - General - Privacy.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - General - Profile.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - Realms & Security - Network.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - Realms & Security - Realms.snap.png
  cypress/snapshots/All Integration Specs.js/Snapshots Testing -- Import account - Settings - Realms & Security - Storage.snap.png
Labels: Missing Dev Review

#2290 chore(cypress): rename folder
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Create Account - Buffering screen after submission.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Create Account - Create or Import Account Selection screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Create Account - PIN screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Create Account - Privacy Settings screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Create Account - User Input Screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Buffering screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Click on emojis.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Click on glyphs.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Create or Import Account Selection screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Enter passphrase screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Go to a chat.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Go to files.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Go to friends.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Main Screen Loaded.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - PIN screen.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Screen after adding recovery seed.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - Developer - App Info.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - General - Accounts & Devices.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - General - Audio & Video.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - General - Keybinds.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - General - Personalize.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - General - Privacy.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - General - Profile.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - Realms & Security - Network.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - Realms & Security - Realms.snap.png
  cypress/snapshots/All Integration Specs/Snapshots Testing -- Import account - Settings - Realms & Security - Storage.snap.png
Labels: Missing Dev Review

#2284 test(cypress): add cypress locators, setup changes to test 2 accounts
  components/ui/Chat/Embeds/File/File.html
  components/ui/Chat/Image/Image.html
  components/views/chat/group/Group.html
  components/views/chat/message/Message.html
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/glyph/Glyph.html
  cypress-first-user.json
  cypress-second-user.json
  package.json
Labels: QA approved

#1817 feat(searchIndex): index conversation messages, implement basic search
  components/interactables/Search/Input/Input.html
  components/interactables/Search/Result/Result.vue
  components/views/chat/conversation/Conversation.vue
  libraries/IndexedDB/index.test.ts
  libraries/IndexedDB/index.ts
  libraries/SearchIndex/index.test.ts
  libraries/SearchIndex/index.ts
  package.json
  plugins/local/classLoader.ts
  plugins/thirdparty/dexie.ts
  store/textile/actions.ts
  store/textile/mutations.test.ts
  store/textile/mutations.ts
  store/textile/types.ts
Labels: temporary blocked checking something

#1812 fix(connectedPeers): fix issue showing connected peers
  components/views/chat/chatbar/footer/is-connected/Connected.html
  components/views/chat/chatbar/footer/is-connected/Connected.vue
  components/views/navigation/sidebar/live/Live.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  middleware/authenticated.test.ts
  plugins/thirdparty/persist.ts
  store/getters.test.ts
  store/webrtc/__snapshots__/state.test.ts.snap
  store/webrtc/actions.ts
  store/webrtc/mutations.test.ts
  store/webrtc/mutations.ts
  store/webrtc/state.ts
  store/webrtc/types.ts
  utilities/Hounddog.test.ts
  utilities/Notifications.ts
Labels: QA approved

#2280 fix(register): create user after page update
  pages/auth/register/index.vue
  store/accounts/actions.ts
Labels: temporary blocked checking something

#2297 fix(media): fix media viewer issue after exiting fullscreen
  components/views/media/Media.vue
Labels: Missing Dev Review, QA approved

#2294 fix(files): show full size icon all the time
  components/views/files/controls/Controls.less
Labels: QA approved

#2300 feat(jest): 58% coverage for TextileFileSystem.ts
  libraries/Files/test/TextileFileSystem.test.ts
  utilities/assets/svg-image.svg
Labels: Missing Dev Review, QA approved

#2292 chore(cypress): update libs
  package.json
Labels: Missing Dev Review, QA approved

#2295 feat(files): size for folders list view
  libraries/Files/Directory.ts
  libraries/Files/abstracts/Item.abstract.ts
Labels: QA approved

#2304 chore(update): update cypress
  cypress.json
Labels: Missing Dev Review

#2309 test(cypress): changes to privacy toggle and create account tests for registry public toggle
  cypress/integration/privacy-page-toggles.js
  cypress/support/commands.js
Labels: QA approved

#2318 test(cypress): changes to cypress chat pair scripts and setup
  cypress-first-user.json
  cypress-second-user.json
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
Labels: QA approved

#2319 chore(cypress): minor update on devices list
  cypress/fixtures/mobile-devices.json
Labels: Missing Dev Review

#2307 fix(settings): fix tab for settings sidebar toggle
  components/interactables/AsideMenu/AsideMenu.html
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.less
Labels: QA approved

#2311 fix(call): fixed webrtc signaling issues
  libraries/WebRTC/Call.ts
Labels: QA approved

#2317 fix(media): removed "mute sound" played on recipient users
  components/views/media/Media.vue
Labels: Missing Dev Review, QA approved

#2314 feat(jest): 100% coverage for Directory.ts
  libraries/Files/test/Directory.test.ts
Labels: Changes Requested

#1766 fix(chat): scroll through glyphs/emoji
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/chat/enhancers/glyphs/Glyphs.less
Labels: Ready for QA

#2325 fix(lifecycleHook): fix Vue3 syntax
  components/interactables/ContextMenu/ContextMenu.vue
  components/ui/Chat/Scroll/Scroll.vue
  components/views/chat/group/Group.vue
  components/views/chat/message/Message.vue
  components/views/media/actions/volume/Volume.vue
  components/views/media/heading/Heading.vue
  components/views/settings/pages/audio/index.vue
Labels: QA approved

#2329 feat(jest): 100% coverage for mock/tests/users.ts
  mock/tests/__snapshots__/users.test.ts.snap
  mock/tests/users.test.ts
Labels: Missing Dev Review, QA approved

#2330 chore(cypress): add github action
  .github/workflows/cypress.yml
Labels: QA approved

#2293 fix(nsfw): nsfw check valid files, allow unscannable/unembeddable files through
  components/views/files/controls/Controls.vue
  config.ts
  libraries/Files/types/file.ts
  libraries/Security/Security.test.ts
  libraries/Security/Security.ts
  utilities/NSFW.ts
Labels: QA approved, temporary blocked checking something

#2327 fix(sidebar): deactivate sidebar search
  assets/styles/base.less
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/interactables/Input/Input.vue
  components/ui/ComingSoon/ComingSoon.html
  components/ui/ComingSoon/ComingSoon.less
  components/ui/ComingSoon/ComingSoon.vue
  components/views/navigation/sidebar/Sidebar.html
  locales/en-US.js
Labels: QA approved

#2352 chore(jest): add more coverage on Solana.test.ts
  libraries/Solana/Solana.test.ts
  libraries/Solana/__snapshots__/Solana.test.ts.snap
Labels: Missing Dev Review, QA approved

#2348 chore(jest): add more coverage on libraries/SearchIndex/index.test.ts
  libraries/SearchIndex/__snapshots__/index.test.ts.snap
  libraries/SearchIndex/index.test.ts
Labels: Missing Dev Review, QA approved

#2359 chore(updates): add more jest tests + minor lint
  .github/workflows/cypress.yml
  components/ui/UpdateModal/UpdateModal.html
  components/views/chat/enhancers/Enhancers.html
  components/views/friends/add/Add.html
  libraries/SearchIndex/index.test.ts
  libraries/Textile/BucketManager.test.ts
  libraries/WebRTC/TracksManager.test.ts
  libraries/WebRTC/__snapshots__/TracksManager.test.ts.snap
  libraries/ui/Cursor.test.ts
  libraries/ui/__snapshots__/Cursor.test.ts.snap
  pages/friends/list/FriendsList.html
Labels: Missing Dev Review

#2276 fix(chat): change message hover
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
Labels: QA approved, temporary blocked checking something

#2363 fix(files): prevent context click during load
  components/views/files/row/Row.html
Labels: Ready for QA

#2386 fix(files): prevent folder name of pure spaces
  components/views/files/controls/Controls.vue
  config.ts
  locales/en-US.js
Labels: QA approved

#2302 feat(modal): add calltoAction modal
  assets/styles/framework/colors.less
  components/ui/Global/Global.html
  components/ui/Modal/Modal.less
  components/views/callToAction/CallToAction.html
  components/views/callToAction/CallToAction.less
  components/views/callToAction/CallToAction.vue
  components/views/chat/enhancers/glyphs/nav/Nav.vue
  components/views/glyphs/Glyphs.vue
  components/views/navigation/mobile/nav/Nav.html
  components/views/navigation/mobile/nav/Nav.vue
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/slimbar/Slimbar.vue
  components/views/navigation/toolbar/Toolbar.html
  locales/en-US.js
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/state.ts
  store/ui/types.ts
Labels: QA approved

#2395 fix(files): remove glow on upgrade button
  components/views/files/aside/Aside.less
Labels: QA approved

#2404 fix(chat): emojies size
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  components/views/chat/message/actions/Actions.less
Labels: QA approved, temporary blocked checking something

#2396 fix(files): add flair color to list view file icons
  components/views/files/row/Row.html
  components/views/files/row/Row.less
  components/views/files/row/Row.vue
Labels: Ready for QA

#2364 fix(files): fullscreen view swiper issue
  components/views/files/view/View.less
Labels: QA approved

#2403 feat(jest): improve naming on TextileFileSystem.test.ts
  libraries/Files/test/TextileFileSystem.test.ts
Labels: QA approved

#2402 feat(jest): 75% coverage for components/mixins/UserPermissions
  components/mixins/UserPermissions/__snapshots__/index.test.ts.snap
  components/mixins/UserPermissions/index.test.ts
  components/mixins/UserPermissions/index.ts
Labels: QA approved

#2398 test(cypress): add chat toolbar cypress tests
  components/views/navigation/toolbar/Toolbar.html
  cypress/integration/chat-features.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
Labels: Missing Dev Review

#2409 feat(jest): 72% coverage for TextileFileSystem.ts
  libraries/Files/test/TextileFileSystem.test.ts
Labels: Missing Dev Review, QA approved

#2411 chore(jest): increase coverage on Logger.ts
  utilities/Logger.test2.ts
Labels: Missing Dev Review, QA approved

#2413 chore(jest): fix warnings
  components/interactables/Search/SearchUtil.test.ts
  libraries/SearchIndex/index.test.ts
  libraries/Solana/SolanaManager/SolanaManager.test.ts
  libraries/Textile/GroupChatManager.test.ts
  libraries/Textile/IdentityManager.test.ts
  libraries/WebRTC/TracksManager.test.ts
  libraries/ui/Cursor.test.ts
Labels: Missing Dev Review, QA approved

#2414 chore(jest): fix warnings
  utilities/Logger.test2.ts
Labels: Missing Dev Review, QA approved

#2399 update(filesAside): fix css on files aside
  components/ui/SimpleList/SimpleList.vue
  components/views/files/aside/Aside.html
  components/views/files/aside/Aside.less
Labels: QA approved, temporary blocked checking something

#2362 fix(messages): context menu shows correct options
  components/views/chat/message/Message.vue
  locales/en-US.js
Labels: QA approved, temporary blocked checking something

#2423 test(cypress): fixes for existing cypress tests
  components/ui/User/State/State.vue
  cypress/integration/create-account.js
  cypress/integration/import-account.js
  cypress/integration/localstorage-validations.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/integration/snapshots-test.js
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Click on emojis.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Click on glyphs.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Go to a chat.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Go to files.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Go to friends.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Main Screen Loaded.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Developer - App Info.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Accounts & Devices.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Audio & Video.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Keybinds.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Personalize.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Privacy.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Profile.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Realms & Security - Network.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Realms & Security - Realms.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Realms & Security - Storage.snap.png
  cypress/support/commands.js
Labels: Missing Dev Review, QA approved

#2418 chore(typo): fix typo
  store/accounts/actions.ts
Labels: Missing Dev Review, QA approved

#2425 chore(update): update github action
  .github/workflows/add-label.yml
  .github/workflows/cypress.yml
  .github/workflows/run-jest-tests.yml
Labels: Missing Dev Review

#2427 feat(jest): 81% coverage for FilSystem.test.ts
  libraries/Files/test/FilSystem.test.ts
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
Labels: Missing Dev Review

#2429 feat(jest): maintenance, fix eslint errors and warnings
  components/interactables/Search/SearchQuery.test.ts
  libraries/Files/test/Bucket.test.ts
  libraries/SearchIndex/index.test.ts
  libraries/Solana/SolanaManager/SolanaManager.test.ts
  libraries/Textile/BucketManager.test.ts
  libraries/Textile/IdentityManager.test.ts
  libraries/WebRTC/TracksManager.test.ts
  mock/tests/__snapshots__/friends.test.ts.snap
  mock/tests/__snapshots__/glyphs.test.ts.snap
  mock/tests/friends.test.ts
  mock/tests/glyphs.test.ts
  mock/tests/users.test.ts
  store/textile/actions.test.ts
  utilities/EXIF.test.ts
  utilities/EnvInfo.test.ts
Labels: Missing Dev Review

#1769 fix(media): close call on tab reload
  components/views/media/Media.vue
Labels: Ready for QA

#2406 fix(GroupDisplay): fix bug in displaying group chats
  components/views/group/aside/Aside.html
  components/views/group/aside/Aside.less
  components/views/navigation/sidebar/Sidebar.vue
  components/views/settings/profile/card/Card.less
Labels: Ready for QA

#2366 feat(chatbar): undo/redo manager
  components/mixins/UI/WithHistory.ts
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/Editable.vue
  config.ts
  libraries/Enums/types/keybindings.ts
Labels: Ready for QA

#2442 test(cypress): fixes for type on disabled elements issue and visit root command
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/integration/chat-pair-features.js
  cypress/integration/import-account-negative-tests.js
  cypress/integration/import-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
Labels: Missing Dev Review, QA approved

#2365 fix(files): responsive issue on files list view
  components/views/files/list/List.html
  components/views/files/list/List.less
  components/views/files/row/Row.html
  components/views/files/row/Row.less
Labels: Ready for QA

#2449 feat(jest): 100% coverage for mock/wallet.ts
  mock/tests/__snapshots__/wallet.test.ts.snap
  mock/tests/wallet.test.ts
Labels: Missing Dev Review

#2448 feat(jest): 100% coverage for store/accounts/mutations
  store/accounts/mutations.test.ts
Labels: Missing Dev Review

#2371 fix(audio): disable sound when deafened
  components/views/navigation/sidebar/controls/Controls.vue
  libraries/SoundManager/SoundManager.ts
  store/accounts/actions.ts
  store/audio/actions.ts
  store/sounds/actions.ts
Labels: QA approved, temporary blocked checking something

#2443 fix(files): standardize archive icon
  components/views/files/file/File.html
  components/views/files/file/File.vue
  components/views/files/view/View.html
  locales/en-US.js
Labels: QA approved

#2424 chore(update): update swiper due to security alert
  package.json
  plugins/thirdparty/swiper.ts
Labels: Missing Dev Review, QA approved

#1779 feat(profileNote): input field and allow user to store private note
  components/interactables/ClickToEdit/ClickToEdit.html
  components/interactables/ClickToEdit/ClickToEdit.less
  components/interactables/ClickToEdit/ClickToEdit.vue
  components/views/user/User.vue
  components/views/user/profile/About.vue
  components/views/user/profile/Profile.html
  components/views/user/profile/Profile.less
  libraries/Textile/MetadataManager.ts
  libraries/Textile/TextileManager.ts
  libraries/Textile/schema.ts
  store/friends/actions.ts
  store/friends/mutations.ts
  store/textile/types.ts
  store/ui/actions.ts
  types/store/store.ts
  types/textile/metadata.ts
  types/ui/friends.d.ts
  types/ui/user.d.ts
Labels: Changes Requested

#2419 feat(indexedDB): clean up searchIndex, indexeddb
  .gitignore
  .vscode/settings.json
  cli.tsconfig.json
  components/interactables/Search/Input/Input.html
  libraries/SatelliteDB/SatelliteDB.test.ts
  libraries/SatelliteDB/SatelliteDB.ts
  libraries/SatelliteDB/SearchIndex.test.ts
  libraries/SatelliteDB/SearchIndex.ts
  libraries/SatelliteDB/__snapshots__/SatelliteDB.test.ts.snap
  libraries/SearchIndex/__snapshots__/index.test.ts.snap
  libraries/SearchIndex/index.test.ts
  libraries/SearchIndex/index.ts
  nuxt.config.js
  package.json
  plugins/local/classLoader.ts
  plugins/thirdparty/dexie.ts
  store/accounts/actions.ts
  store/friends/actions.ts
  store/friends/mutations.ts
  store/settings/actions.ts
  store/textile/actions.ts
  store/textile/mutations.test.ts
  store/textile/mutations.ts
  types/ui/friends.d.ts
  utilities/Hounddog.ts
Labels: Ready for QA

#2468 feat(jest): 100% coverage for libraries/SatelliteDB/SatelliteDB
  libraries/SatelliteDB/SatelliteDB.test.ts
Labels: Missing Dev Review

#2446 fix(chat): reset emotes search on modal close/change
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
Labels: QA approved

#2315 fix(keybinds): prevent default behavior for shortcuts,add call shortcuts
  components/views/navigation/toolbar/Toolbar.vue
  components/views/settings/pages/keybinds/index.vue
  layouts/chat.vue
  libraries/Enums/types/blockKeys.ts
  libraries/Enums/types/modifierKeys.ts
  locales/en-US.js
  package.json
  pages/index.vue
  store/ui/actions.test.ts
  store/ui/actions.ts
  store/webrtc/actions.ts
  utilities/HotkeyList.ts
  utilities/Keybinds.ts
  utilities/__snapshots__/HotkeyList.test.ts.snap
Labels: QA approved

#2444 fix(chat): block sending empty message on quick profile
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.less
  components/interactables/QuickProfile/QuickProfile.vue
  locales/en-US.js
Labels: QA approved

#2407 feat(signaling): ui update to soon allow user to set signaling servers
  components/interactables/Input/Input.less
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/Privacy.less
  components/views/settings/pages/privacy/index.vue
  libraries/ui/Common.ts
  locales/en-US.js
  pages/setup/privacy/Privacy.html
  pages/setup/privacy/Privacy.less
  pages/setup/privacy/index.vue
  store/settings/mutations.ts
  store/settings/state.ts
  store/settings/types.ts
Labels: QA approved

#2326 fix(chat): multiple files upload
  components/ui/Chat/Scroll/Scroll.vue
  components/views/files/upload/Upload.vue
  layouts/chat.vue
  store/textile/actions.ts
  store/ui/actions.test.ts
  store/ui/actions.ts
Labels: temporary blocked checking something

#2447 fix(register): submit form on enter
  components/interactables/Button/Button.html
  components/interactables/Button/Button.vue
  components/views/user/create/Create.html
  components/views/user/create/Create.vue
  config.ts
Labels: Ready for QA

#2495 feat(jest): 100% coverage for store/settings/actions
  store/settings/actions.test.ts
Labels: Missing Dev Review

#2494 feat(jest): 100% coverage for store/settings/mutations
  store/settings/mutations.test.ts
Labels: Missing Dev Review

#2477 fix(bug): added a check to see if friend was already added
  components/views/friends/friend/Friend.html
  components/views/friends/friend/Friend.vue
  store/friends/actions.ts
Labels: QA approved

#2496 fix(profile): increase line height of title
  components/views/settings/pages/profile/Profile.less
Labels: QA approved

#2497 fix(profile): add condition for badges
  components/views/settings/profile/card/Card.html
  mock/profile.ts
Labels: QA approved

#2498 fix(upload): change close button color depend on theme
  components/views/files/upload/previewItem/PreviewItem.less
Labels: QA approved

#2499 fix(reply): change replier name color
  components/views/chat/chatbar/reply/Reply.less
Labels: QA approved

#2500 chore(githubAction): remove github action
  .github/workflows/rebase.yml
Labels: Missing Dev Review

#2510 feat(jest): 100% coverage for libraries/SoundManager/SoundManager
  libraries/SoundManager/SoundManager.test.ts
Labels: Missing Dev Review

#2509 feat(jest): 100% coverage for store/chat/mutations
  store/chat/mutations.test.ts
Labels: Missing Dev Review

#2508 fix: possibility to send glyphs in group chats
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/glyphs/item/Item.vue
Labels: Ready for QA

#2514 chore(jest): remove not used stuff
  libraries/Textile/BucketManager.test.ts
Labels: Missing Dev Review

#2445 feat(files): rename files and directories
  components/interactables/InputGroup/InputGroup.html
  components/ui/Global/Global.html
  components/ui/Modal/Modal.less
  components/views/files/file/File.less
  components/views/files/file/File.vue
  components/views/files/grid/Grid.html
  components/views/files/grid/Grid.vue
  components/views/files/list/List.html
  components/views/files/list/List.vue
  components/views/files/rename/Rename.html
  components/views/files/rename/Rename.less
  components/views/files/rename/Rename.vue
  components/views/files/row/Row.vue
  components/views/files/view/View.html
  components/views/files/view/View.vue
  libraries/Files/Directory.ts
  libraries/Files/Fil.ts
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/abstracts/Item.abstract.ts
  libraries/Files/remote/textile/Bucket.ts
  libraries/Files/test/Fil.test.ts
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
  libraries/Files/types/filesystem.ts
  locales/en-US.js
  package.json
  pages/files/browse/Browse.html
  pages/files/browse/index.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Ready for QA

#2515 test(cypress): add chat tests and fixes for db changes
  components/interactables/ContextMenu/ContextMenu.html
  components/interactables/ImageCropper/ImageCropper.html
  components/views/chat/chatbar/Editable.vue
  components/views/chat/message/Message.html
  components/views/user/create/Create.html
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/import-account.js
  cypress/integration/localstorage-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/integration/snapshots-test.js
  cypress/integration/version-release-notes.js
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Create Account - Buffering screen after submission.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Create Account - Create or Import Account Selection screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Create Account - PIN screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Create Account - Privacy Settings screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Create Account - User Input Screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Buffering screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Click on emojis.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Click on glyphs.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Create or Import Account Selection screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Enter passphrase screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Go to a chat.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Go to files.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Go to friends.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Main Screen Loaded.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - PIN screen.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Screen after adding recovery seed.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Developer - App Info.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Accounts & Devices.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Audio & Video.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Keybinds.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Personalize.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Privacy.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - General - Profile.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Realms & Security - Network.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Realms & Security - Realms.snap.png
  cypress/snapshots/snapshots-test.js/Snapshots Testing -- Import account - Settings - Realms & Security - Storage.snap.png
  cypress/snapshots/snapshots-test.js/__diff_output__/Snapshots Testing -- Import account - Click on emojis.diff.png
  cypress/snapshots/snapshots-test.js/__diff_output__/Snapshots Testing -- Import account - Click on glyphs.diff.png
  cypress/snapshots/snapshots-test.js/__diff_output__/Snapshots Testing -- Import account - Go to a chat.diff.png
  cypress/snapshots/snapshots-test.js/__diff_output__/Snapshots Testing -- Import account - Main Screen Loaded.diff.png
  cypress/snapshots/snapshots-test.js/__diff_output__/Snapshots Testing -- Import account - Screen after adding recovery seed.diff.png
  cypress/support/commands.js
Labels: QA approved

#2523 feat(jest): 100% coverage for Fil.test.ts
  libraries/Files/test/Fil.test.ts
Labels: Missing Dev Review, QA approved

#2527 feat(jest): 95% branch covered for Directory.test.ts
  libraries/Files/test/Directory.test.ts
Labels: Missing Dev Review

#2530 feat(jest): 100% coverage for authenticated.ts
  middleware/__snapshots__/authenticated.test.ts.snap
  middleware/authenticated.test.ts
Labels: Missing Dev Review

#2532 feat(jest): 81% coverage for store/ui/mutations
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#2534 feat(jest): 100% coverage for store/sounds/actions
  store/sounds/actions.test.ts
Labels: Missing Dev Review, QA approved

#2536 chore(cypress): add retries
  cypress.json
Labels: Missing Dev Review

#2524 fix(mobile): video icon touching marketplace icon
  components/views/navigation/toolbar/Toolbar.html
Labels: Missing Dev Review, QA approved

#2542 chore(scripts): package.json updated
  package.json
Labels: Missing Dev Review

#2516 chore(Groups): combines groups and users, fixes several group UI bugs
  components/views/group/clickable/Clickable.html
  components/views/group/clickable/Clickable.less
  components/views/group/clickable/Clickable.vue
  components/views/group/create/Create.less
  components/views/group/icon/GroupIcon.html
  components/views/group/invite/Invite.less
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  store/groups/actions.ts
  store/groups/mutations.ts
  store/groups/types.ts
Labels: Ready for QA

#2519 fix(profileNote): fix remaining issues in profile note
  components/interactables/ClickToEdit/ClickToEdit.html
  components/interactables/ClickToEdit/ClickToEdit.vue
  components/interactables/Tabs/Tabs.less
  components/views/user/profile/About.vue
  components/views/user/profile/Profile.less
  config.ts
  libraries/Enums/types/keybindings.ts
Labels: Missing Dev Review, QA approved

#2431 fix(chat): scroll on iOS
  components/ui/Chat/Scroll/Scroll.html
  components/ui/Chat/Scroll/Scroll.less
  components/ui/Chat/Scroll/Scroll.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/message/glyph/Glyph.less
  layouts/Layout.less
  layouts/chat.vue
  layouts/server.vue
  pages/chat/direct/Direct.less
  plugins/thirdparty/persist.ts
Labels: temporary blocked checking something

#2645 fix(sidebar): change key for users
  components/views/navigation/sidebar/Sidebar.html
Labels: Missing Dev Review, QA approved

#2644 fix(keybinds): add meta + l to blocked mac shortcuts
  utilities/HotkeyList.ts
  utilities/__snapshots__/HotkeyList.test.ts.snap
Labels: QA approved

#2639 fix(files): better archive file check
  components/views/files/file/File.vue
  components/views/files/row/Row.vue
  config.ts
Labels: QA approved, temporary blocked checking something

#2422 feat(importAccount): typeahead support using searchindex
  components/ui/TypeAhead/TypeAhead.html
  components/ui/TypeAhead/TypeAhead.less
  components/ui/TypeAhead/TypeAhead.vue
  pages/setup/ImportAccount/ImportAccount.html
Labels: temporary blocked checking something
