Repository Satellite-im/Core-PWA, pull requests merged in 2022-01, with the labels that each got.

#866 chore(update): add todo's on JIRA
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/message/reply/Reply.html
  components/views/files/upload/Upload.vue
  components/views/friends/add/Add.vue
  components/views/media/Media.html
  components/views/media/Media.vue
  components/views/navigation/server/sidebar/channels/Channels.vue
  layouts/chat.vue
  libraries/Solana/ServerProgram/ServerProgram.ts
  libraries/Textile/BucketManager.ts
  libraries/WebRTC/Wire.ts
  libraries/ui/Alerts.ts
  middleware/authenticated.ts
  pages/auth/register/index.vue
  types/ui/friends.d.ts
  utilities/Messaging.ts
Labels: Missing Dev Review, QA approved

#851 chore(console): remove console log
  components/views/navigation/toolbar/Toolbar.vue
Labels: Missing Dev Review, QA approved

#850 chore(jest): minor update on jest tests
  test/Circle.test.ts
  test/Commands.test.ts
  test/ComponentsMixinsTouchIndex.test.ts
  test/EXIF.skip.ts
  test/Friends.test.ts
  test/StoreSearchMutations.test.ts
  test/StoreSettingsMutations.test.ts
Labels: Missing Dev Review, QA approved

#869 fix(call): fix 'video viewers are not adjusting to size when entering fullscreen'
  components/views/media/Media.less
Labels: Ready for QA

#877 task(githubAction): conflicts checker
  .github/workflows/pr-conflicts.yml
Labels: Missing Dev Review

#874 chore(typos): fix typo
  commit-guide.md
  components/interactables/QuickProfile/QuickProfile.vue
  components/ui/Chat/Embeds/File/File.html
  components/ui/Chat/Embeds/File/File.less
  libraries/ui/Alerts.ts
Labels: Missing Dev Review, QA approved

#882 Revert "task(githubAction): conflicts checker"
  .github/workflows/pr-conflicts.yml
Labels: Missing Dev Review

#849 fix(call): set incoming call properties in webrtc in blacklist for vuex-persist
  plugins/thirdparty/persist.ts
Labels: QA approved

#848 fix(call): disable call buttons after it is clicked until hang up or error happened
  components/views/navigation/toolbar/Toolbar.html
Labels: QA approved

#878 fix(chat): fix 'anything typed will be added to the end of the text instead of where user clicked'
  components/views/chat/chatbar/Chatbar.vue
Labels: Ready for QA

#879 fix(friends): fix 'removing one friend will remove all of user's friends'
  components/views/friends/friend/Friend.vue
  store/friends/actions.ts
  store/friends/mutations.ts
Labels: Ready for QA

#897 fix(chat): fix style issues in edit message
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/edit/Edit.less
Labels: QA approved

#898 update(utils): centralize get platform helpers/utilities AP-409
  components/ui/Popups/Error/Error.vue
  components/views/chat/message/Message.vue
  components/views/settings/pages/audio/index.vue
  components/views/settings/pages/info/Developer.html
  components/views/settings/pages/info/index.vue
  components/views/settings/pages/notifications/index.vue
  nuxt.config.js
  plugins/local/envinfo.ts
  utilities/ConsoleWarning.ts
  utilities/EnvInfo.ts
  utilities/Notifications.ts
Labels: Ready for QA

#905 fix(settings): fix copy not aligned to the toggle AP-309
  components/interactables/Switch/Switch.less
Labels: Ready for QA

#907 fix(marketplace): marketplace button not working AP-269
  components/views/glyphs/Glyphs.vue
  store/ui/state.ts
Labels: QA approved

#910 chore(cypress): add missing file
  cypress.json
Labels: Missing Dev Review, QA approved

#908 fix(call): fix issues when disable video
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
Labels: Ready for QA

#920 chore(various): minor updates
  components/ui/Popups/Error/Error.vue
  components/views/chat/message/reply/Reply.html
  package.json
Labels: Missing Dev Review

#918 fix(replies): render replies for all messages AP-271
  components/views/chat/message/reply/Reply.vue
  utilities/Messaging.ts
Labels: Missing Dev Review, QA approved, missing fixing conflict

#919 fix(reaction): fix message reply reaction issue AP-413
  components/views/chat/message/reactions/Reactions.vue
  components/views/chat/message/reply/Reply.html
  utilities/Messaging.ts
Labels: Missing Dev Review, QA approved

#973 fix(reaction): fixes emoji reacts for reply messages of inner messages
  utilities/Messaging.ts
Labels: Missing Dev Review, QA approved

#917 feat(tslint): added typescript eslint for nuxt and force vscode prettier format on save
  .eslintrc.js
  .vscode/settings.json
  package.json
  store/sounds/types.ts
  store/textile/actions.ts
  store/textile/types.ts
Labels: QA approved

#977 fix(media): fix settings tooltip layered issue AP-412
  components/ui/Chat/Scroll/Scroll.less
  components/views/media/Media.less
Labels: QA approved

#978 fix(modal): fix send money modal issue AP-470
  components/views/wallet/mini/Mini.less
  components/views/wallet/mini/Mini.vue
  components/views/wallet/mini/body/Body.vue
Labels: QA approved

#1003 fix(glyphs): add missing glyphs that were previously returning 404
  mock/glyphs.ts
Labels: Ready for QA

#997 fix(ui): quick chat modal action for 1on1 chat AP-475
  components/views/friends/quick/Quick.vue
Labels: Ready for QA

#994 fix(ui): change first sentence in settings>network page
  components/views/settings/pages/realms/Realms.html
Labels: Ready for QA

#992 fix(ui): sidebar stretching outside view AP-383
  assets/styles/framework/ui.less
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/slimbar/Slimbar.less
Labels: Ready for QA

#993 fix(keybinds): ignore modified keys in keybinding AP-427
  components/views/settings/pages/keybinds/index.vue
Labels: Ready for QA

#1005 fix(login): fix padding issues on create/import account buttons
  components/interactables/Button/Button.html
  pages/setup/disclaimer/Disclaimer.html
  pages/setup/disclaimer/Disclaimer.less
Labels: QA approved

#1007 feat(themes): flair dropdown deactivated until user select theme
  components/interactables/Select/Select.html
  components/interactables/Select/Select.less
  components/interactables/Select/Select.vue
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/personalize/index.vue
Labels: QA approved

#1011 fix(enhancer): close enhancer(emoji,glyph) after choose
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/glyphs/item/Item.vue
Labels: Ready for QA

#1009 fix(highlight): fix 'highlight issue in character count'
  components/views/chat/chatbar/footer/Footer.vue
Labels: QA approved

#1006 add(userprofile): add user profile modal AP-489
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.less
  components/ui/Global/Global.html
  components/views/user/User.vue
  components/views/user/profile/Profile.html
  components/views/user/profile/Profile.less
  components/views/user/profile/Profile.vue
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: QA approved

#1019 fix(typing): fix “user is typing…” appears when the user is not typing
  components/views/chat/chatbar/Chatbar.vue
Labels: QA approved

#1017 fix(ui): ui issues in search results AP-496
  components/interactables/Search/Result/Result.html
  components/interactables/Search/Result/Result.less
Labels: QA approved

#1032 Revert "fix(call): fixed timer not reseting, toggle video button, and user feedback for muting AP-344, AP-345, AP-350, AP-353"
  assets/styles/framework/ui.less
  assets/styles/themes/moonless_night.less
  components/interactables/Button/Button.html
  components/interactables/Select/Select.html
  components/interactables/Select/Select.less
  components/interactables/Select/Select.vue
  components/views/chat/chatbar/footer/Footer.vue
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/friends/quick/Quick.vue
  components/views/media/Media.vue
  components/views/media/actions/Actions.vue
  components/views/media/heading/Heading.vue
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/navigation/slimbar/Slimbar.less
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/sounds/Sounds.html
  components/views/settings/pages/audio/sounds/Sounds.less
  components/views/settings/pages/audio/sounds/Sounds.vue
  components/views/settings/pages/audio/sounds/item/Item.vue
  components/views/settings/pages/keybinds/index.vue
  components/views/settings/pages/notifications/index.vue
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/personalize/index.vue
  components/views/settings/pages/realms/Realms.html
  libraries/Enums/enums.ts
  libraries/Enums/types/webrtc.ts
  libraries/WebRTC/Call.ts
  mock/glyphs.ts
  pages/setup/disclaimer/Disclaimer.html
  pages/setup/disclaimer/Disclaimer.less
  store/webrtc/mutations.ts
Labels: Missing Dev Review

#1033 fix(call): fixed timer not reseting, toggle video button, and user feedback for muting AP-344, AP-345, AP-350, AP-353
  components/views/media/Media.vue
  components/views/media/actions/Actions.vue
  components/views/media/heading/Heading.vue
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.vue
  libraries/Enums/enums.ts
  libraries/Enums/types/webrtc.ts
  libraries/WebRTC/Call.ts
  store/webrtc/mutations.ts
Labels: Missing Dev Review

#1014 fix(ui): missing components on themes
  assets/styles/themes/moonless_night.less
Labels: QA approved

#1039 chore(template): update PR template
  PULL_REQUEST_TEMPLATE.md
Labels: Missing Dev Review, QA approved

#1038 fix(call): sync call timer
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.vue
  store/webrtc/actions.ts
  store/webrtc/mutations.ts
  store/webrtc/state.ts
Labels: QA approved

#1018 add(filesystem): add import/export features for file system AP-467
  libraries/Files/FileSystem.ts
  libraries/Files/test/FSImport.test.ts
  libraries/Files/test/FileSystem.test.ts
Labels: Changes Requested

#1051 feat(profile): profile modal responsive layout AP-507
  assets/styles/framework/breakpoints.less
  components/interactables/Tabs/Tabs.html
  components/interactables/Tabs/Tabs.less
  components/interactables/Tabs/Tabs.vue
  components/interactables/Tabs/types.d.ts
  components/ui/Global/Global.html
  components/ui/HorizontalRule/HorizontalRule.vue
  components/ui/Popups/Error/Error.less
  components/ui/User/State/State.less
  components/ui/User/State/State.vue
  components/views/chat/enhancers/Enhancers.less
  components/views/servers/create/Create.less
  components/views/user/create/Create.less
  components/views/user/profile/Profile.html
  components/views/user/profile/Profile.less
  components/views/user/profile/Profile.vue
Labels: Ready for QA

#1060 feat(privacySettings): create privacy settings tab
  components/views/settings/Sidebar.vue
  components/views/settings/modal/Modal.html
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
Labels: Ready for QA

#1064 chore(update): PR template update
  PULL_REQUEST_TEMPLATE.md
Labels: QA approved

#1067 chore(colors): update naming
  store/ui/types.ts
Labels: Missing Dev Review, QA approved

#1072 feat(media): indicator added for remote user muted
  components/views/media/Media.html
  components/views/media/Media.less
  components/views/media/Media.vue
Labels: Missing Dev Review, QA approved

#1075 fix(chat): enforce the 256 chars when sending
  components/views/chat/chatbar/Chatbar.vue
Labels: QA approved

#1074 feat(profile): hide add friend button if already friends or self
  components/interactables/Tabs/Tabs.vue
  components/views/files/upload/Upload.vue
  components/views/friends/add/Add.vue
  components/views/friends/friend/Friend.vue
  components/views/media/actions/Actions.vue
  components/views/user/profile/Profile.html
  components/views/user/profile/Profile.vue
  libraries/Enums/enums.ts
  libraries/Enums/types/addFriend.ts
  libraries/Enums/types/blockKeys.ts
  libraries/Enums/types/encoding-types.ts
  libraries/Enums/types/keybindings.ts
  libraries/Enums/types/measurement-units.ts
  libraries/Enums/types/message-routes.ts
  libraries/Enums/types/messaging-types.ts
  libraries/Enums/types/modifierKeys.ts
  libraries/Enums/types/prop-common-events.ts
  libraries/Textile/MailboxManager.ts
  store/friends/actions.ts
  store/friends/mutations.ts
  tsconfig.json
  types/ui/tab.d.ts
  utilities/Messaging.ts
Labels: QA approved

#1162 add(jest): 100% coverage for store/webrtc/state.ts unit test
  store/webrtc/__snapshots__/state.test.ts.snap
  store/webrtc/state.test.ts
Labels: Ready for QA

#1169 fix(chat): enforce chat limit on chatbar
  components/views/chat/chatbar/Chatbar.vue
Labels: QA approved

#1163 add(jest): 100% coverage for store/ui/types.ts unit test
  store/ui/__snapshots__/types.test.ts.snap
  store/ui/types.test.ts
Labels: Ready for QA

#1160 add(jest): 100% coverage for store/friends/state.ts unit test
  store/friends/__snapshots__/state.test.ts.snap
  store/friends/state.test.ts
Labels: Ready for QA

#1158 add(jest): 100% coverage for store/ui/state.ts unit test
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/state.test.ts
Labels: QA approved

#1157 fix(emoji): fix emoji appearance in chatbox smooth
  components/views/chat/message/Message.less
Labels: QA approved

#1152 add(jest): 100% coverage for store/webrtc/mutations.ts unit test
  store/webrtc/mutations.test.ts
  store/webrtc/mutations.ts
Labels: Ready for QA

#1146 add(jest): 100% coverage for store/sounds/mutations.ts unit test
  store/sounds/mutations.test.ts
Labels: QA approved

#1145 add(jest): 100% coverage for store/sounds/state.ts unit test
  store/sounds/__snapshots__/state.test.ts.snap
  store/sounds/state.test.ts
Labels: QA approved

#1159 feat(call): call - waiting for other user to accept indication
  components/views/media/Media.html
  components/views/media/user/User.html
  components/views/media/user/User.less
  components/views/media/user/User.vue
Labels: QA approved

#1073 add(jest): unit tests for Hounddog and Logger
  utilities/Hounddog.test.ts
  utilities/Hounddog.ts
  utilities/Logger.test.ts
  utilities/__snapshots__/Hounddog.test.ts.snap
Labels: Ready for QA

#1196 add(jest): 100% for store/friends/mutations.ts unit test
  store/friends/mutations.test.ts
Labels: QA approved

#1195 update(jest): improve data state.mutations.ts
  store/dataState/mutations.test.ts
  store/dataState/mutations.ts
Labels: QA approved

#1198 add(jest): 100% coverage for libraries/WebRTC/encoders.ts
  libraries/WebRTC/__snapshots__/encoders.test.ts.snap
  libraries/WebRTC/encoders.test.ts
  libraries/WebRTC/encoders.ts
Labels: QA approved

#1192 add(jest): 100% coverage for libraries/ui/Alerts.ts unit test
  libraries/ui/Alerts.test.ts
  libraries/ui/Alerts.ts
Labels: Missing Dev Review, QA approved

#1178 add(jest): 100% coverage for store/textile/getters.ts unit test
  store/textile/__snapshots__/getters.test.ts.snap
  store/textile/getters.test.ts
Labels: QA approved

#1186 fix(controls): toggle buttons go off correctly after hangup
  components/views/navigation/sidebar/controls/Controls.html
Labels: QA approved

#1241 add(jest): 100% coverage for store/media/mutations.ts
  store/media/mutations.test.ts
Labels: QA approved

#1242 add(jest): 100% coverage for store/media/state.ts
  store/media/__snapshots__/state.test.ts.snap
  store/media/state.test.ts
Labels: QA approved

#1184 feat(sidebar): sort the friend list by last updated time AP-119
  components/views/friends/friend/Friend.vue
  components/views/navigation/sidebar/Sidebar.vue
  store/friends/mutations.ts
  types/ui/user.d.ts
Labels: QA approved
