Repository Satellite-im/Core-PWA, pull requests merged in 2022-07, with the labels that each got.

#3839 fix(notifications): text overflow for notifications
  components/ui/FloatingContainer/FloatingContainer.html
  components/ui/FloatingContainer/FloatingContainer.less
  components/ui/FloatingContainer/FloatingContainer.vue
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/alerts/Alerts.html
  components/views/navigation/toolbar/alerts/Alerts.less
  components/views/navigation/toolbar/alerts/Alerts.vue
  components/views/navigation/toolbar/alerts/alert/Alert.html
  components/views/navigation/toolbar/alerts/alert/Alert.less
Labels: Ready for QA

#3884 fix(user-name-style): fixed name lineheight
  components/views/user/User.less
Labels: QA tested

#3904 feat(jest): 100% coverage for store/chat/mutations
  store/chat/mutations.test.ts
Labels: Missing Dev Review

#3878 refactor(mediauser): styling and fix indicator color
  components/views/media/user/User.html
  components/views/media/user/User.less
Labels: Ready for QA

#3847 fix(files): keyboard accessible, hit esc to close
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/views/files/view/View.html
  components/views/files/view/View.vue
Labels: QA tested

#3591 feat(call): create background call component
  assets/styles/framework/framework.less
  assets/styles/framework/ui.less
  components/ui/BackgroundCall/BackgroundCall.html
  components/ui/BackgroundCall/BackgroundCall.less
  components/ui/BackgroundCall/BackgroundCall.vue
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/ui/Modal/Modal.less
  components/views/friends/friend/Friend.vue
  components/views/media/Media.vue
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.vue
  components/views/navigation/toolbar/Toolbar.html
  layouts/Layout.less
  layouts/chat.vue
  layouts/files.vue
  layouts/friends.vue
  layouts/server.vue
  locales/en-US.js
  store/conversation/mutations.ts
  store/friends/actions.ts
  store/friends/getters.test.ts
  store/textile/actions.ts
  store/ui/mutations.ts
  store/webrtc/__snapshots__/state.test.ts.snap
  store/webrtc/getters.ts
  store/webrtc/mutations.ts
  store/webrtc/state.ts
  store/webrtc/types.ts
Labels: QA tested

#3777 fix(chatbar-mobile): fixed chatbar focus when pressed
  components/ui/Chat/Scroll/Scroll.html
  components/ui/Chat/Scroll/Scroll.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/Editable.vue
  components/views/chat/message/Message.vue
Labels: QA tested

#3910 chore(githubAction): add iridium label automatically
  .github/workflows/iridium-label.yml
Labels: draft, iridium

#3924 fix(files): fix files embed overflow issue
  components/ui/Chat/Embeds/File/File.html
  components/ui/Chat/Embeds/File/File.less
  components/ui/Chat/Embeds/File/File.vue
  components/views/chat/group/Group.less
Labels: Missing Dev Review

#3926 fix(sidebar): add relative timestamps to sidebar
  components/views/chat/search/result/item/Item.vue
  components/views/user/User.vue
  locales/en-US.js
  store/settings/getters.ts
Labels: Missing Dev Review

#3925 fix(audio): error handling for missing audio output devices
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/index.vue
Labels: testing blocked, merge blocked

#3928 feat(settings): add page and section components
  components/interactables/Select/Select.less
  components/interactables/Volume/Volume.less
  components/views/settings/page/Page.html
  components/views/settings/page/Page.less
  components/views/settings/page/Page.vue
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/developer/Info.html
  components/views/settings/pages/info/Developer.html
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/network/Network.html
  components/views/settings/pages/notifications/Notifications.html
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/realms/Realms.html
  components/views/settings/pages/storage/Storage.html
  components/views/settings/section/Section.html
  components/views/settings/section/Section.less
  components/views/settings/section/Section.vue
  components/views/settings/unit/Unit.html
  components/views/settings/unit/Unit.less
  components/views/settings/unit/Unit.vue
Labels: testing blocked, merge blocked

#3929 feat(files): unblock files ui, basic upload and download
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.vue
  components/views/files/file/File.html
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.vue
  components/views/files/rename/Rename.vue
  components/views/files/upload/Upload.vue
  components/views/files/view/View.vue
  components/views/settings/Sidebar.vue
  components/views/settings/pages/profile/index.vue
  components/views/user/create/Create.vue
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/remote/textile/PersonalBucket.ts
  libraries/Files/test/Bucket.test.ts
  libraries/Files/test/FilSystem.test.ts
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
  libraries/Files/types/file.ts
  libraries/Files/types/filesystem.ts
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/files/FilesManager.ts
  libraries/Iridium/files/types.ts
  libraries/Textile/TextileManager.ts
  pages/files/browse/Browse.html
  pages/files/browse/index.vue
  plugins/local/classLoader.ts
  store/textile/actions.ts
  utilities/BlobManip.test.ts
  utilities/BlobManip.ts
  utilities/BlobToBase64.ts
  utilities/FileType.ts
  utilities/NSFW.ts
Labels: iridium

#3893 feat(friends): can click on a friend and open direct message
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
  components/views/friends/add/Add.vue
  layouts/chat.vue
  libraries/Iridium/chat/ChatManager.ts
  pages/chat/direct/Direct.html
  pages/chat/direct/_address.vue
Labels: Missing Dev Review, iridium

#3940 chore(dexie): clear all dbs from settings
  libraries/Iridium/__snapshots__/encoders.test.ts.snap
  store/settings/actions.test.ts
  store/settings/actions.ts
Labels: Missing Dev Review

#3949 chore(jest): fix jest github action
  .github/workflows/run-jest-tests.yml
  store/textile/actions.test.ts.disabled.ts
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/__snapshots__/types.test.ts.snap
  store/ui/getters.test.ts.disabled.ts
  store/ui/mutations.test.ts.disabled.ts
  store/ui/state.test.ts.disabled.ts
  store/ui/types.test.ts.disabled.ts
Labels: draft

#3952 chore(cypress): fix github action
  .github/workflows/cypress.yml
Labels: draft

#3953 feat(settings-profile): account link component/markup
  assets/styles/framework/animations.less
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/profile/Banner.vue
  components/views/settings/profile/accounts/Accounts.vue
  components/views/settings/profile/accounts/Item/Item.html
  components/views/settings/profile/accounts/Item/Item.less
  components/views/settings/profile/accounts/Item/Item.vue
  locales/en-US.js
Labels: Missing Dev Review

#3946 feat(iridium): add settings manager
  assets/styles/framework/colors.less
  assets/styles/themes/moonless_night.less
  components/ui/HorizontalRule/HorizontalRule.vue
  components/views/media/user/User.vue
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/index.vue
  components/views/settings/pages/audio/sounds/Sounds.html
  components/views/settings/pages/audio/sounds/Sounds.vue
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/keybinds/index.vue
  components/views/settings/pages/personalize/Personalize.html
  components/views/settings/pages/personalize/index.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
  layouts/chat.vue
  layouts/default.vue
  layouts/files.vue
  layouts/friends.vue
  layouts/server.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/profile/ProfileManager.ts
  libraries/Iridium/settings/SettingsManager.ts
  libraries/Iridium/settings/types.ts
  libraries/Iridium/utils.ts
  package.json
  store/ui/actions.ts
  store/ui/state.ts
  store/ui/types.ts
  utilities/merge.ts
Labels: iridium

#3942 fix(signup): fix glitch
  pages/auth/unlock/Unlock.html
  pages/auth/unlock/index.vue
Labels: Missing Dev Review

#3992 chore(assets): switching to infura
  config.ts
  mock/glyphs.ts
  mock/tests/__snapshots__/glyphs.test.ts.snap
  mock/tests/__snapshots__/messages.test.ts.snap
  nuxt.config.js
  store/textile/getters.test.ts
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
Labels: Missing Dev Review, QA tested

#3994 chore(jest): jest updates
  jest.config.js
  store/textile/actions.test.ts
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/getters.test.ts
  store/ui/mutations.test.ts
  store/ui/state.test.ts
  store/ui/types.test.ts
Labels: Missing Dev Review

#3954 fix(files): add all functionality to iridium filesManager
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/views/files/aside/Aside.html
  components/views/files/aside/Aside.vue
  components/views/files/aside/List/List.html
  components/views/files/aside/List/List.vue
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.vue
  components/views/files/controls/switch/Switch.html
  components/views/files/controls/switch/Switch.less
  components/views/files/controls/switch/Switch.vue
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.vue
  components/views/files/grid/Grid.html
  components/views/files/grid/Grid.vue
  components/views/files/grid/item/Item.html
  components/views/files/grid/item/Item.less
  components/views/files/grid/item/Item.vue
  components/views/files/list/List.html
  components/views/files/list/List.vue
  components/views/files/list/row/Row.html
  components/views/files/list/row/Row.vue
  components/views/files/rename/Rename.html
  components/views/files/rename/Rename.vue
  components/views/files/view/View.html
  components/views/files/view/View.vue
  components/views/files/viewSwitcher/ViewSwitcher.html
  components/views/files/viewSwitcher/ViewSwitcher.vue
  layouts/files.vue
  libraries/Enums/enums.ts
  libraries/Enums/types/files.ts
  libraries/Iridium/files/FilesManager.ts
  libraries/Iridium/files/types.ts
  locales/en-US.js
  pages/files/browse/Browse.html
  pages/files/browse/Browse.less
  pages/files/browse/index.vue
  plugins/thirdparty/persist.ts
  store/files/getters.ts
  store/files/mutations.ts
  store/files/state.ts
  store/files/types.ts
  store/getters.test.ts
  store/ui/actions.test.ts.disabled.ts
  store/ui/getters.test.ts
  store/ui/getters.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
  types/store/store.ts
  types/ui/sidebar.d.ts
Labels: Missing Dev Review, iridium

#3998 feat(profile): remove photo when user already uploaded
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
  locales/en-US.js
Labels: Missing Dev Review

#3956 refactor(imageCropper): reduce anti pattern of passing functions as props
  components/interactables/ImageCropper/ImageCropper.html
  components/interactables/ImageCropper/ImageCropper.less
  components/interactables/ImageCropper/ImageCropper.vue
  components/interactables/ImageInput/ImageInput.vue
  components/views/chat/message/Message.vue
  components/views/servers/create/Create.html
  components/views/servers/create/Create.vue
  components/views/settings/modal/Modal.vue
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
  components/views/user/create/Create.html
  components/views/user/create/Create.less
  components/views/user/create/Create.vue
  config.ts
  store/ui/types.ts
  utilities/NSFW.ts
Labels: Missing Dev Review

#4002 fix(files-aside): update total size used after every operation
  components/views/files/aside/Aside.vue
Labels: Missing Dev Review

#4007 feat(chat): chat/improvement
  components/views/chat/chatbar/Chatbar.vue
  components/views/user/User.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/friends/FriendsManager.ts
  pages/chat/direct/_address.vue
Labels: Missing Dev Review, iridium

#4004 feat(files): refactor thumbnails to lazy load
  components/views/files/grid/item/Item.html
  components/views/files/grid/item/Item.vue
  components/views/files/view/View.html
  components/views/files/view/View.less
  components/views/files/view/View.vue
  libraries/Iridium/files/FilesManager.ts
  libraries/Iridium/files/types.ts
Labels: Missing Dev Review

#4010 fix(files): fix broken recent files route
  components/views/files/aside/List/List.vue
  pages/files/browse/index.vue
  plugins/thirdparty/persist.ts
  store/files/getters.ts
  store/files/mutations.ts
  store/files/state.ts
  store/files/types.ts
Labels: Missing Dev Review

#4005 refactor(files): refactor layout
  components/ui/SimpleScroll/SimpleScroll.vue
  components/views/files/list/row/Row.less
  pages/files/browse/Browse.html
  pages/files/browse/Browse.less
Labels: Missing Dev Review

#4017 refactor(inputGroup): simplify inputGroup component
  components/interactables/InputGroup/InputGroup.html
  components/interactables/InputGroup/InputGroup.less
  components/interactables/InputGroup/InputGroup.vue
  pages/auth/unlock/Unlock.html
Labels: Missing Dev Review

#3955 fix(friends-requests): improved requests and notifications display
  components/views/friends/add/Add.less
  components/views/friends/add/Add.vue
  components/views/friends/friend/Friend.html
  components/views/friends/friend/Friend.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/user/User.vue
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/friends/types.ts
  pages/chat/direct/_address.vue
  pages/friends/list/FriendsList.html
  pages/friends/list/FriendsList.less
  pages/friends/list/index.vue
Labels: Missing Dev Review

#4021 fix(call): display errors on permission denied and change mute/unmute. Duplicate of Alex's pr against dev
  components/views/media/actions/Actions.vue
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/navigation/toolbar/Toolbar.vue
  libraries/WebRTC/Call.ts
  store/audio/actions.ts
  store/audio/mutations.ts
  store/video/actions.ts
  store/webrtc/actions.ts
Labels: Missing Dev Review

#4023 feat(iridium-chat): create conversation/types
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/conversation/Conversation.vue
  components/views/friends/friend/Friend.vue
  components/views/user/User.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/settings/SettingsManager.ts
  pages/chat/Chat.html
  pages/chat/Chat.less
  pages/chat/_id.vue
  pages/chat/direct/Direct.html
  pages/chat/direct/_address.vue
  pages/chat/groups/Group.html
  pages/chat/groups/Group.less
  pages/chat/groups/_id.vue
Labels: Missing Dev Review

#4015 feat(settings/keybinds): redesign and connect to iridium
  components/interactables/Input/Input.html
  components/interactables/KeybindInput/KeybindInput.html
  components/interactables/KeybindInput/KeybindInput.less
  components/interactables/KeybindInput/KeybindInput.vue
  components/views/settings/pages/keybinds/Keybinds.html
  components/views/settings/pages/keybinds/index.vue
  components/views/settings/section/Section.less
  components/views/settings/unit/Unit.less
  libraries/Iridium/settings/SettingsManager.ts
  libraries/Iridium/settings/types.ts
  locales/en-US.js
  store/ui/actions.ts
Labels: Changes Requested, Missing Dev Review

#4025 refactor(files): refactor table layout
  components/views/files/list/List.html
  components/views/files/list/List.less
  components/views/files/list/row/Row.html
  components/views/files/list/row/Row.less
  components/views/files/mobileList/item/Item.html
  components/views/files/mobileList/item/Item.less
  components/views/files/mobileList/item/Item.vue
  components/views/files/mobileList/mobileList.html
  components/views/files/mobileList/mobileList.less
  components/views/files/mobileList/mobileList.vue
  locales/en-US.js
  pages/files/browse/Browse.html
  pages/files/browse/Browse.less
Labels: Missing Dev Review, iridium-dev

#4029 feat(settings/keybinds): update key press logic
  components/interactables/KeybindInput/KeybindInput.html
  components/interactables/KeybindInput/KeybindInput.vue
  components/views/settings/pages/keybinds/index.vue
  utilities/Keyboard.ts
Labels: Missing Dev Review, iridium-dev

#4032 chore(warnings): fix terminal warnings
  components/views/files/mobileList/mobileList.less
  components/views/settings/pages/keybinds/Keybinds.html
  utilities/Keyboard.test.ts
  utilities/__snapshots__/Keyboard.test.ts.snap
Labels: Missing Dev Review

#4033 feat(chat): create groups and render in sidebar
  components/interactables/UserPicker/UserPicker.vue
  components/ui/GroupIcon/GroupIcon.html
  components/ui/GroupIcon/GroupIcon.less
  components/ui/GroupIcon/GroupIcon.vue
  components/ui/User/State/State.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/friends/friend/Friend.vue
  components/views/friends/quick/Quick.html
  components/views/friends/quick/Quick.vue
  components/views/group/clickable/Clickable.html
  components/views/group/clickable/Clickable.less
  components/views/group/clickable/Clickable.vue
  components/views/group/icon/GroupIcon.html
  components/views/group/icon/GroupIcon.less
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/sidebar/status/Status.html
  components/views/navigation/toolbar/Toolbar.html
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/friends/types.ts
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/groups/types.ts
  locales/en-US.js
  pages/files/browse/index.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/state.ts
  store/ui/types.ts
  types/ui/user.d.ts
Labels: Missing Dev Review, iridium-dev

#4042 feat(layouts): consolidate "friends" and "files" layouts
  components/views/friends/mobile/list.vue
  layouts/basic.vue
  layouts/friends.vue
  pages/files/browse/Browse.html
  pages/files/browse/index.vue
  pages/friends/list/index.vue
Labels: Missing Dev Review

#4046 feat(chat): display uploaded files in ui
  assets/styles/base.less
  components/ui/DroppableWrapper/DroppableWrapper.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/Editable.vue
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/chatbar/controls/Controls.vue
  components/views/chat/chatbar/upload/Error.vue
  components/views/chat/chatbar/upload/Upload.html
  components/views/chat/chatbar/upload/Upload.less
  components/views/chat/chatbar/upload/Upload.vue
  components/views/chat/chatbar/upload/preview/Preview.html
  components/views/chat/chatbar/upload/preview/Preview.less
  components/views/chat/chatbar/upload/preview/Preview.vue
  components/views/chat/chatbar/upload/preview/item/Item.html
  components/views/chat/chatbar/upload/preview/item/Item.less
  components/views/chat/chatbar/upload/preview/item/Item.vue
  components/views/files/controls/Controls.vue
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.less
  components/views/files/upload/preview/Preview.html
  layouts/Layout.less
  layouts/chat.vue
  pages/files/browse/index.vue
  store/chat/getters.test.ts
  store/chat/getters.ts
  store/chat/mutations.test.ts
  store/chat/mutations.ts
  store/chat/types.ts
  store/ui/actions.ts
Labels: Changes Requested, iridium-dev

#4064 feat(chat): conversation message components
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  components/views/chat/message/actions/Actions.less
  components/views/chat/message/reactions/Reactions.vue
  components/views/chat/message/reply/Reply.vue
Labels: Missing Dev Review

#4063 fix(toolbar): connect conversation data using iridium
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/navigation/toolbar/Toolbar.vue
  layouts/chat.vue
Labels: 1 more code review needed

#4067 fix(circle): render different colors based on provided did string
  components/ui/Circle/Circle.html
  components/ui/Circle/Circle.less
  components/ui/Circle/Circle.test.ts
  components/ui/Circle/Circle.vue
  components/ui/Circle/__snapshots__/Circle.test.ts.snap
  components/ui/SatelliteCircle/SatelliteCircle.html
  components/ui/SatelliteCircle/SatelliteCircle.less
  components/ui/SatelliteCircle/SatelliteCircle.vue
  utilities/Circle.ts
Labels: Missing Dev Review

#4065 fix(sidebar): conditionally render context menu items based on type
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/friends/types.ts
  locales/en-US.js
Labels: iridium-dev

#4038 feat(account): ux improvement to import account functionality
  components/ui/TypeAhead/TypeAhead.html
  components/ui/TypeAhead/TypeAhead.less
  components/ui/TypeAhead/TypeAhead.vue
  config.ts
  locales/en-US.js
  pages/setup/ImportAccount/ImportAccount.html
  pages/setup/ImportAccount/ImportAccount.less
  pages/setup/ImportAccount/index.vue
  pages/setup/phrase/Phrase.less
Labels: iridium-dev

#4069 chore(lint): lint
  components/ui/TypeAhead/TypeAhead.html
  components/ui/TypeAhead/TypeAhead.less
  pages/setup/ImportAccount/ImportAccount.html
  pages/setup/ImportAccount/ImportAccount.less
  pages/setup/phrase/Phrase.less
Labels: iridium-dev

#4070 chore(names): colors
  utilities/Circle.ts
Labels: Missing Dev Review

#4071 fix(media): prevent image update #3919
  store/conversation/actions.ts
Labels: Missing Dev Review

#4073 feat(iridium): refactor & updates
  .env.example
  components/interactables/UserPicker/UserPicker.vue
  components/ui/Global/Global.vue
  components/views/friends/friend/Friend.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/toolbar/Toolbar.vue
  config.ts
  layouts/chat.vue
  libraries/Iridium/IridiumManager.ts
  libraries/Iridium/MailboxManager.ts
  libraries/Iridium/MetadataManager.test.ts
  libraries/Iridium/MetadataManager.ts
  libraries/Iridium/NotificationManager.test.ts
  libraries/Iridium/NotificationManager.ts
  libraries/Iridium/TextileManager.test.ts
  libraries/Iridium/UserManager.test.ts
  libraries/Iridium/UserManager.ts
  libraries/Iridium/__snapshots__/NotificationManager.test.ts.snap
  libraries/Iridium/__snapshots__/TextileManager.test.ts.snap
  libraries/Iridium/__snapshots__/encoders.test.ts.snap
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/encoders.test.ts
  libraries/Iridium/encoders.test.ts.disable
  libraries/Iridium/encoders.ts
  libraries/Iridium/files/FilesManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/groups/types.ts
  libraries/Iridium/schema.ts
  libraries/Iridium/settings/SettingsManager.ts
  nuxt.config.js
  package.json
  pages/friends/list/FriendsList.html
  pages/friends/list/index.vue
  store/accounts/actions.ts
  store/iridium/actions.ts
Labels: Missing Dev Review

#4074 fix(friends): render issues surrounding friend requests. fix group hash method
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  libraries/Iridium/groups/GroupManager.ts
  libraries/WebRTC/Libp2p.test.ts
  libraries/WebRTC/__snapshots__/Libp2p.test.ts.snap
  pages/friends/list/FriendsList.html
  pages/friends/list/index.vue
Labels: Missing Dev Review

#4022 feat(mobile): long press context menu
  components/interactables/ContextMenu/ContextMenu.html
  components/interactables/ContextMenu/ContextMenu.vue
  components/ui/ContextMenu/ContextMenu.vue
  components/ui/ContextMenu/ListItem/ListItem.vue
  components/ui/Unread/Unread.html
  components/ui/Unread/Unread.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.vue
  components/views/files/grid/item/Item.html
  components/views/files/grid/item/Item.less
  components/views/files/grid/item/Item.vue
  components/views/files/list/row/Row.html
  components/views/files/list/row/Row.vue
  components/views/files/mobileList/item/Item.html
  components/views/files/mobileList/item/Item.less
  components/views/files/mobileList/item/Item.vue
  components/views/friends/friend/Friend.vue
  components/views/friends/mobile/list.vue
  components/views/message/Friend.html
  components/views/message/Friend.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  nuxt.config.js
  plugins/local/contextmenu.ts
  store/ui/types.ts
Labels: iridium-dev

#4075 feat(chat): persist draft messages in chatbar
  components/views/chat/chatbar/Chatbar.vue
  store/chat/__snapshots__/state.test.ts.snap
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
Labels: Missing Dev Review

#4079 feat(friends): friendsManager cleanups
  components/views/friends/friend/Friend.vue
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/friends/FriendsManager.ts
Labels: Missing Dev Review

#4081 feat(layout): refactor layout, untangle mobile from desktop
  assets/styles/base.less
  assets/styles/framework/animations.less
  assets/styles/framework/breakpoints.less
  assets/styles/framework/framework.less
  assets/styles/framework/ui.less
  components/interactables/SidebarToggle/SidebarToggle.vue
  components/interactables/Switch/Switch.less
  components/ui/Chat/Encrypted/Encrypted.html
  components/ui/Chat/Encrypted/Encrypted.less
  components/ui/Chat/Scroll/Scroll.less
  components/ui/DroppableWrapper/DroppableWrapper.html
  components/ui/DroppableWrapper/DroppableWrapper.less
  components/ui/HorizontalRule/HorizontalRule.vue
  components/ui/Modal/Modal.html
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/footer/Footer.less
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/grid/item/Item.less
  components/views/files/view/View.less
  components/views/friends/add/Add.less
  components/views/friends/friend/Friend.html
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/server/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/slimbar/Slimbar.html
  components/views/navigation/slimbar/Slimbar.less
  components/views/navigation/toolbar/Toolbar.html
  components/views/navigation/toolbar/Toolbar.less
  components/views/settings/modal/Modal.less
  layouts/Layout.less
  layouts/basic.vue
  layouts/default.vue
  layouts/mobile.vue
  nuxt.config.js
  package.json
  pages/chat/Chat.html
  pages/chat/Chat.less
  pages/chat/_id.vue
  pages/files/browse/Browse.html
  pages/files/browse/Browse.less
  pages/files/browse/index.vue
  pages/friends/list/FriendsList.html
  pages/friends/list/FriendsList.less
  pages/friends/list/index.vue
Labels: Missing Dev Review

#3859 feat(modal): add fade animation
  assets/styles/framework/animations.less
  components/ui/Global/Global.html
  components/ui/Modal/Modal.html
  components/ui/Modal/Modal.less
  layouts/chat.vue
Labels: missing fixing conflict, iridium-dev

#4084 fix: chat reply and file preview size bug
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/chatbar/footer/Footer.less
  components/views/chat/chatbar/reply/Reply.less
  components/views/chat/chatbar/upload/preview/Preview.less
Labels: Missing Dev Review

#4092 refactor(layout): move droppable wrapper up to desktop layout
  layouts/basic.vue
  pages/chat/Chat.html
  pages/chat/_id.vue
  pages/files/browse/Browse.html
  pages/files/browse/Browse.less
  pages/files/browse/index.vue
Labels: Missing Dev Review

#4094 refactor(pages): update url paths for files and friends pages
  components/views/files/grid/item/Item.vue
  components/views/files/list/row/Row.vue
  components/views/files/mobileList/item/Item.vue
  components/views/navigation/mobile/nav/Nav.vue
  components/views/navigation/mobile/sidebar/sidebar.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/list/List.vue
  nuxt.config.js
  pages/allcomponents.vue
  pages/auth/register/index.vue
  pages/files/Files.html
  pages/files/Files.less
  pages/files/index.vue
  pages/friends/Friends.html
  pages/friends/Friends.less
  pages/friends/index.vue
  pages/index.vue
Labels: Missing Dev Review

#4096 refactor(sidebar): refactor styles and improve visibility of quickchat button
  assets/styles/base.less
  assets/styles/framework/ui.less
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/sidebar/controls/Controls.html
  components/views/navigation/sidebar/controls/Controls.less
  components/views/navigation/sidebar/list/item/Item.less
  components/views/navigation/sidebar/quick/Quick.html
  components/views/navigation/sidebar/quick/Quick.less
  components/views/navigation/sidebar/quick/Quick.vue
  components/views/navigation/toolbar/Toolbar.less
Labels: Missing Dev Review

#4086 feat(groups): build leave group method
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/groups/Group.ts
  libraries/Iridium/groups/GroupManager.ts
  libraries/Iridium/groups/types.ts
Labels: iridium-dev

#4097 fix(chat): glyphs
  assets/styles/framework/ui.less
  components/views/chat/chatbar/controls/Controls.vue
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/glyphs/Glyphs.html
  components/views/chat/enhancers/glyphs/Glyphs.less
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  libraries/Iridium/chat/types.ts
Labels: iridium-dev
