Repository Satellite-im/Core-PWA, pull requests merged in 2022-04, with the labels that each got.

#2661 fix(toolbar): remove glitch effect on hover in safari
  components/ui/ComingSoon/ComingSoon.html
  components/ui/ComingSoon/ComingSoon.less
  components/ui/SatelliteCircle/SatelliteCircle.html
Labels: Ready for QA

#2563 fix(reaction): fix issue when try to add emoji reaction
  components/views/chat/message/reactions/Reactions.vue
  types/messaging.d.ts
Labels: Ready for QA

#2664 feat(chat): save image
  components/views/chat/message/Message.vue
Labels: Ready for QA

#2671 feat(jest): 84% coverage for store/ui/actions
  store/ui/actions.test.ts
Labels: Missing Dev Review

#2686 chore(jest): add Common.test.ts + FileType.test.ts
  libraries/ui/Common.test.ts
  libraries/ui/__snapshots__/Common.test.ts.snap
  utilities/FileType.test.ts
  utilities/__snapshots__/FileType.test.ts.snap
Labels: Missing Dev Review

#2691 test(cypress): skip cypress tests failing on CI
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
Labels: Missing Dev Review

#2669 chore(chat-scroll): scroll fixed while on call
  layouts/Layout.less
Labels: Missing Dev Review

#2667 fix(env): clean up envinfo errors via casting
  utilities/EnvInfo.ts
Labels: Missing Dev Review

#2701 test(cypress): small improvements to cypress scripts
  cypress.json
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/support/commands.js
Labels: Missing Dev Review, draft

#2687 chore(lint): minor lint
  .github/workflows/cypress.yml
  .github/workflows/run-jest-tests.yml
  components/ui/Unread/Unread.html
  components/ui/Unread/Unread.less
  components/views/chat/message/Message.less
  components/views/group/aside/Aside.html
  components/views/group/aside/Aside.less
Labels: QA approved

#2665 fix(heic): better heic checking
  components/views/files/upload/Upload.vue
  utilities/Heic.test.ts
  utilities/Heic.ts
  utilities/__snapshots__/Heic.test.ts.snap
Labels: Ready for QA

#2654 fix(files): rename quality of life update
  components/views/files/controls/Controls.vue
  config.ts
  libraries/Files/Directory.ts
  libraries/Files/Fil.ts
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/abstracts/Item.abstract.ts
  libraries/Files/errors/Errors.ts
  locales/en-US.js
Labels: QA approved

#2722 feat(jest): 85% coverage for FilSystem.ts
  libraries/Files/test/FilSystem.test.ts
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
Labels: Missing Dev Review

#2713 chore(mock): remove mock file info
  mock/files.ts
  plugins/local/mock.ts
  store/files/__snapshots__/actions.test.ts.snap
  store/files/__snapshots__/mutations.test.ts.snap
  store/files/__snapshots__/state.test.ts.snap
  store/files/actions.test.ts
  store/files/actions.ts
  store/files/mutations.test.ts
  store/files/mutations.ts
  store/files/state.test.ts
  store/files/state.ts
  store/files/types.ts
  types/files/file.ts
Labels: Missing Dev Review, QA approved

#2726 fix(mobile): coming soon page top padding issue
  components/views/callToAction/CallToAction.less
Labels: Missing Dev Review, QA approved

#2729 fix(toolbar): fix lack resolution of icons
  components/views/navigation/toolbar/Toolbar.less
Labels: Missing Dev Review, QA approved

#2670 fix(register): throw error on unscannable file type and block upload
  components/views/user/create/Create.vue
  utilities/NSFW.ts
Labels: QA approved

#2732 chore(lint): minor lint
  components/ui/ComingSoon/ComingSoon.less
  components/ui/SatelliteCircle/SatelliteCircle.html
  components/views/navigation/toolbar/Toolbar.less
Labels: Missing Dev Review, QA approved

#2746 feat(jest): 78% coverage for store/ui/mutations
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#2734 test(cypress): add tests for glyphs
  components/views/chat/enhancers/glyphs/nav/Nav.html
  components/views/chat/enhancers/glyphs/pack/Pack.html
  cypress/integration/chat-glyphs-validations.js
  cypress/support/commands.js
Labels: Missing Dev Review, QA approved

#2751 chore(cypress): update devices
  cypress/fixtures/mobile-devices.json
Labels: Missing Dev Review

#2752 chore(commands): hide commands for early access
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
Labels: Missing Dev Review

#2668 feat(files): sort list view columns
  components/views/files/list/List.html
  components/views/files/list/List.less
  components/views/files/list/List.vue
  components/views/files/row/Row.html
  components/views/files/row/Row.vue
  libraries/Enums/enums.ts
  libraries/Enums/types/fileSort.ts
  pages/files/browse/Browse.html
  pages/files/browse/index.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Ready for QA

#2712 fix(chat): rclick options for non-embeddable images
  components/views/chat/message/Message.vue
Labels: QA approved

#2689 fix(reply): fix 'if user sends reply chat will autoscroll to bottom'
  store/textile/actions.ts
Labels: QA approved

#2728 update(files): fs errors are translation friendly
  components/views/files/controls/Controls.vue
  components/views/files/rename/Rename.vue
  libraries/Files/Fil.ts
  libraries/Files/errors/Errors.ts
  locales/en-US.js
Labels: QA approved

#2715 feat(search): better search results pagination counter and timestamps
  components/views/chat/search/input/Input.html
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/Result.less
  components/views/chat/search/result/Result.vue
  components/views/chat/search/result/ResultGlobal.less
  components/views/chat/search/result/item/Item.html
  components/views/chat/search/result/item/Item.less
  components/views/chat/search/result/item/Item.vue
  components/views/chat/search/result/meta/Meta.html
  components/views/chat/search/result/meta/Meta.less
  components/views/chat/search/result/meta/Meta.vue
  locales/en-US.js
  store/textile/actions.ts
  store/ui/types.ts
  types/search/search.ts
Labels: QA approved

#2759 test(cypress): draft for fixes on ci and mobile responsiveness
  .github/workflows/cypress.yml
  components/views/navigation/sidebar/Sidebar.html
  cypress.json
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/support/commands.js
  package.json
Labels: QA approved

#2735 fix(colors): fix selection text color in safari
  assets/styles/base.less
  assets/styles/themes/moonless_night.less
  layouts/chat.vue
  layouts/files.vue
  layouts/friends.vue
  layouts/server.vue
  utilities/Colors.ts
Labels: Ready for QA

#2401 fix(chat): fix unknown name issue when the user is registered with an avatar
  components/views/friends/add/Add.vue
  pages/friends/list/FriendsList.html
  store/accounts/actions.ts
  store/textile/actions.ts
Labels: QA approved, temporary blocked checking something

#2762 test(cypress): add timestamp validations for chat
  cypress/integration/chat-pair-features.js
Labels: Missing Dev Review

#2772 chore(jest): add Colors.test.ts
  utilities/Colors.test.ts
  utilities/__snapshots__/Colors.test.ts.snap
Labels: Missing Dev Review

#2758 feat(libp2p): implement libp2p instead of p2pt wire and peer
  components/ui/Global/Global.html
  components/ui/Global/Global.vue
  components/ui/User/State/State.vue
  components/views/chat/chatbar/Chatbar.vue
  components/views/media/Media.vue
  components/views/media/actions/Actions.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/controls/Controls.vue
  components/views/navigation/sidebar/live/Live.vue
  libraries/WebRTC/Call.ts
  libraries/WebRTC/Libp2p.ts
  libraries/WebRTC/Peer.ts
  libraries/WebRTC/WebRTC.ts
  libraries/WebRTC/Wire.ts
  libraries/WebRTC/__snapshots__/encoders.test.ts.snap
  libraries/WebRTC/encoders.ts
  nuxt.config.js
  package.json
  plugins/local/classLoader.ts
  store/accounts/actions.ts
  store/audio/actions.ts
  store/friends/__snapshots__/mutations.test.ts.snap
  store/friends/actions.ts
  store/friends/mutations.test.ts
  store/friends/mutations.ts
  store/webrtc/__snapshots__/state.test.ts.snap
  store/webrtc/actions.ts
  store/webrtc/mutations.ts
  store/webrtc/state.ts
  store/webrtc/types.ts
  types/ui/friends.d.ts
Labels: QA approved

#2535 feat(groupChats): add group events AP-1174
  components/views/chat/group/Group.vue
  components/views/friends/quick/Quick.html
  components/views/friends/quick/Quick.vue
  components/views/group/clickable/Clickable.html
  components/views/group/clickable/Clickable.vue
  components/views/group/icon/GroupIcon.html
  components/views/group/icon/GroupIcon.vue
  components/views/group/invite/Invite.html
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/navigation/toolbar/Toolbar.html
  libraries/Solana/GroupChatsProgram/GroupChatsProgram.ts
  libraries/Solana/GroupChatsProgram/GroupChatsProgram.types.ts
  libraries/Solana/GroupChatsProgram/GroupCrypto.ts
  libraries/Textile/GroupChatManager.ts
  locales/en-US.js
  pages/chat/groups/_id.vue
  plugins/thirdparty/persist.ts
  store/accounts/actions.ts
  store/groups/__snapshots__/mutations.test.ts.snap
  store/groups/__snapshots__/state.test.ts.snap
  store/groups/actions.ts
  store/groups/mutations.test.ts
  store/groups/mutations.ts
  store/groups/state.ts
  store/groups/types.ts
Labels: QA approved

#2754 fix(message): emoji picker position
  components/views/chat/message/Message.vue
Labels: Ready for QA

#2785 chore(jest): remove not used test
  libraries/Files/test/TextileFileSystem.test.ts
Labels: Missing Dev Review

#2786 chore(lint): minor group lint
  components/views/group/icon/GroupIcon.html
Labels: Missing Dev Review

#2783 fix(files): reactivity issue on files operations
  components/views/files/list/List.vue
  libraries/Files/Directory.ts
  pages/files/browse/index.vue
Labels: QA approved

#2782 test(cypress): add links validations and fixes on CI
  components/views/glyphs/Glyphs.html
  components/views/navigation/sidebar/status/Status.html
  cypress.json
  cypress/integration/chat-features.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/support/commands.js
Labels: draft

#2771 feat(jest): 100% coverage for FileType.ts
  jest-setup.js
  utilities/FileType.test.ts
  utilities/test_assets/heic-image.heic
  utilities/test_assets/non-heic-image.png
  utilities/test_assets/svg-image.svg
  utilities/test_assets/type_heic_but_is_converted_png.heic
  utilities/test_assets/type_heic_not_recognized.HEIC
Labels: Missing Dev Review, QA approved

#2745 fix(files): rework store for files modal
  components/ui/Global/Global.html
  components/views/files/view/View.vue
  pages/files/browse/index.vue
  plugins/thirdparty/persist.ts
  store/ui/mutations.ts
  store/ui/types.ts
Labels: Ready for QA

#2766 fix(search): switch to static timestamps
  components/views/chat/search/result/item/Item.vue
  locales/en-US.js
  plugins/local/dayjs.ts
  store/settings/getters.ts
Labels: QA approved

#2804 fix(chat): hide action icons if message is editing status
  components/views/chat/message/Message.html
Labels: Ready for QA

#2808 feat(jest): 100% coverage for store/groups/mutations
  store/groups/mutations.test.ts
Labels: Missing Dev Review

#2812 refactor(github): update action on lint PR - AP-1362
  .github/workflows/lint-PR-title.yml
Labels: Missing Dev Review

#2801 fix(chat): cancel message edit on unmount
  components/views/chat/message/Message.vue
Labels: QA approved

#2815 fix(ui): image preview stretch issue
  components/ui/Chat/Image/Overlay/Overlay.less
Labels: Ready for QA

#2814 test(cypress): unskip tests, improvements on tests/commands
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account.js
  cypress/integration/localstorage-validations.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
Labels: temporary blocked checking something

#2506 fix(user): styled as planned on figma
  components/views/chat/group/Group.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/reply/Reply.html
  components/views/chat/message/reply/Reply.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  components/views/user/User.html
  components/views/user/User.less
  components/views/user/User.vue
  locales/en-US.js
  plugins/local/dayjs.ts
  store/textile/mutations.ts
  utilities/Messaging.ts
Labels: QA approved, missing fixing conflict

#2819 feat(jest): 79% coverage for store/ui/mutations.ts
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#2795 fix(chat): fix scrollbar appearing while sending message
  components/views/chat/conversation/Conversation.less
Labels: QA approved

#2792 fix(mobile): hide virtual keyboard when scroll
  components/ui/Chat/Scroll/Scroll.html
  components/ui/Chat/Scroll/Scroll.vue
Labels: temporary blocked checking something

#2828 chore(cypress): update workflow file from cypress gh action
  .github/workflows/cypress.yml
Labels: Missing Dev Review

#2784 feat(chat): create older messages info block above chatbar
  components/ui/Chat/Info/Info.html
  components/ui/Chat/Info/Info.less
  components/ui/Chat/Info/Info.vue
  components/ui/Chat/Info/types.d.ts
  components/ui/Chat/Scroll/Scroll.vue
  components/views/chat/chatbar/Chatbar.less
  layouts/chat.vue
  locales/en-US.js
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: QA approved

#2833 chore(jest): add more tests on UserPermissions/index.test.ts
  components/mixins/UserPermissions/__snapshots__/index.test.ts.snap
  components/mixins/UserPermissions/index.test.ts
Labels: Missing Dev Review

#2834 chore(jest): update test
  components/views/chat/search/SearchQuery.test.ts
Labels: Missing Dev Review

#2835 chore(jest): add more tests in Crypto.test.ts
  libraries/Crypto/Crypto.test.ts
  libraries/Crypto/__snapshots__/Crypto.test.ts.snap
Labels: Missing Dev Review, QA approved

#2838 chore(jest): more tests
  libraries/Files/test/FilSystem2.test.ts
  libraries/Files/test/__snapshots__/FilSystem2.test.ts.snap
Labels: Missing Dev Review

#2842 chore(jest): add more solana tests
  libraries/Solana/Solana.test.ts
  libraries/Solana/__snapshots__/Solana.test.ts.snap
Labels: Missing Dev Review

#2843 chore(jest): add more coverage on SolanaManager.test.ts
  libraries/Solana/SolanaManager/SolanaManager.test.ts
  libraries/Solana/SolanaManager/__snapshots__/SolanaManager.test.ts.snap
Labels: Missing Dev Review

#2830 test(cypress): skip chat tests failing in CI
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/mobiles-responsiveness.js
Labels: Missing Dev Review, draft

#2655 fix(files): nsfw scan memory limit
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/controls/Controls.vue
  components/views/files/upload/Upload.vue
  components/views/files/view/View.html
  components/views/files/view/View.less
  components/views/files/view/View.vue
  components/views/user/create/Create.vue
  config.ts
  layouts/files.vue
  libraries/Files/Directory.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/remote/textile/Bucket.ts
  locales/en-US.js
  package.json
  utilities/NSFW.ts
Labels: temporary blocked checking something

#2829 test(cypress): add tests for invalid image on account creation
  components/ui/Circle/Circle.html
  components/ui/User/State/State.vue
  cypress/integration/create-account.js
Labels: Missing Dev Review, QA approved

#2794 feat(search): orderby search results
  components/views/chat/search/SearchUtil.test.ts
  components/views/chat/search/SearchUtil.ts
  components/views/chat/search/__snapshots__/SearchUtil.test.ts.snap
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/Result.vue
  components/views/chat/search/result/meta/Meta.html
  components/views/chat/search/result/meta/Meta.less
  components/views/chat/search/result/meta/Meta.vue
  libraries/SatelliteDB/SearchIndex.ts
  store/textile/actions.ts
  types/search/search.ts
Labels: Ready for QA

#2809 feat(csam): add toggle for csam scan and save info to textile
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
  libraries/Textile/TextileManager.ts
  libraries/Textile/UserManager.ts
  libraries/Textile/schema.ts
  locales/en-US.js
  store/settings/actions.ts
  store/settings/mutations.ts
  store/settings/state.ts
  store/settings/types.ts
  store/textile/actions.ts
  store/textile/types.ts
  types/textile/user.ts
Labels: QA approved

#2852 feat(jest): 90% coverage for FilSystem.ts
  libraries/Files/test/FilSystem.test.ts
  libraries/Files/test/FilSystem2.test.ts
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
  libraries/Files/test/__snapshots__/FilSystem2.test.ts.snap
Labels: Missing Dev Review, QA approved

#2851 feat(jest): 97% coverage for store/friends/mutations
  store/friends/__snapshots__/mutations.test.ts.snap
  store/friends/__snapshots__/mutations2.test.ts.snap
  store/friends/mutations.test.ts
  store/friends/mutations2.test.ts
Labels: Missing Dev Review

#2796 feat(files): dropzone for file uploads
  components/ui/DroppableWrapper/DroppableWrapper.vue
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.vue
  layouts/files.vue
  locales/en-US.js
  pages/files/browse/Browse.html
  store/ui/getters.ts
  tsconfig.json
Labels: Ready for QA

#2861 test(cypress): skip cypress tests for timeouts
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
Labels: Missing Dev Review, draft

#2862 chore(import): remove not used import
  store/friends/actions.ts
Labels: Missing Dev Review, QA approved

#2863 chore(import): remove not used import
  mock/groups.ts
  store/audio/actions.ts
Labels: Missing Dev Review

#2875 chore(glyphs): removes description
  components/views/glyphs/Glyphs.html
  components/views/glyphs/Glyphs.vue
Labels: Ready for QA

#2821 fix(mobile): user jump between different photo
  components/ui/Chat/Image/Overlay/Overlay.html
Labels: Ready for QA

#2856 chore(scrollbar): created new scrollbar component
  assets/styles/framework/ui.less
  components/ui/SimpleScroll/SimpleScroll.html
  components/ui/SimpleScroll/SimpleScroll.less
  components/ui/SimpleScroll/SimpleScroll.vue
Labels: Ready for QA

#2864 fix(mobile): virtual keyboard hide chatbox in chat
  components/views/chat/chatbar/Chatbar.vue
Labels: Ready for QA

#2849 fix: mobile keyboard update
  components/ui/Chat/Scroll/Scroll.vue
Labels: Missing Dev Review, QA approved

#2884 chore(update): update bread
  store/ui/types.ts
Labels: Ready for QA

#2818 fix(chat): show placeholder on image load error
  components/ui/Chat/Image/Image.html
  components/ui/Chat/Image/Image.less
  components/ui/Chat/Image/Image.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/actions/Actions.less
  components/views/chat/message/reply/Reply.html
  locales/en-US.js
Labels: Ready for QA

#2841 chore(ui): refactor view/message/Friend
  components/views/message/Friend.html
  components/views/message/Friend.less
  components/views/message/Friend.vue
Labels: QA approved

#2887 test(cypress): add chat reaction tests
  components/views/chat/message/Message.html
  components/views/chat/message/reactions/Reactions.html
  cypress/integration/chat-pair-features.js
  cypress/support/commands.js
Labels: Missing Dev Review

#2803 chore(refactor): refactor to document title using vue composition api
  components/compositions/useMeta.ts
  layouts/chat.vue
  layouts/default.vue
  layouts/files.vue
  layouts/friends.vue
  layouts/server.vue
  nuxt.config.js
  package.json
  pages/files/browse/index.vue
  store/meta/mutations.ts
  store/meta/state.ts
  store/meta/types.ts
Labels: Ready for QA

#2879 fix(profile): change quick profile position on error display
  components/interactables/QuickProfile/QuickProfile.vue
Labels: QA approved

#2895 chore(jest): add jest test - store/meta/state.test.ts
  store/meta/__snapshots__/state.test.ts.snap
  store/meta/state.test.ts
Labels: Missing Dev Review

#2897 feat(jest): 100% coverage for store/meta/mutations
  store/meta/mutations.test.ts
Labels: Missing Dev Review

#2882 fix(replies): display correct reply text
  components/views/chat/message/reply/Reply.less
  components/views/chat/message/reply/Reply.vue
  locales/en-US.js
Labels: QA approved

#2905 feat(jest): 79% coverage for store/ui/mutations
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#2906 feat(jest): 22% coverage for MetadataManager
  libraries/Textile/MetadataManager.test.ts
Labels: Changes Requested

#2891 fix(files): missing accent color files
  assets/styles/base.less
Labels: QA approved

#2920 feat(jest): 100% coverage for Directory.ts
  libraries/Files/test/Directory.test.ts
  libraries/Files/test/__snapshots__/Directory.test.ts.snap
Labels: Missing Dev Review

#2922 chore(jest): increase coverage on store/settings/actions.test.ts
  store/settings/actions.test.ts
Labels: Missing Dev Review

#2925 chore(jest): increase coverage on store/textile/getters.test.ts
  store/textile/__snapshots__/getters.test.ts.snap
  store/textile/getters.test.ts
Labels: Missing Dev Review

#2927 chore(jest): remove skip on test
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#2934 test(cypress): add reaction tests and skip tests failing
  components/views/chat/message/reactions/Reactions.html
  cypress/integration/chat-features.js
  cypress/integration/chat-pair-features.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/support/commands.js
Labels: Missing Dev Review

#2904 chore(vuetify): shrink bundle, remove vuetify
  components/views/chat/search/result/Result.html
  nuxt.config.js
  package.json
  plugins/thirdparty/vuetify.ts
Labels: Ready for QA

#2921 fix(mobile): fix image picker position
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.vue
Labels: Ready for QA

#2911 fix(chat): fix reply modal disappearing issue
  components/views/chat/chatbar/Chatbar.vue
Labels: QA approved

#2900 chore(chat): fixed actions position issue replies width
  components/views/chat/message/reply/Reply.less
Labels: QA approved

#2937 feat(jest): 100% coverage for store/settings/actions
  store/settings/actions.test.ts
Labels: Missing Dev Review

#2924 fix(emoji-scroll): emoji persist on scroll
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
Labels: Ready for QA

#2894 chore(translations): updated sidebar's translations
  components/views/user/User.vue
  locales/en-US.js
Labels: Ready for QA

#2889 fix(files): persistent files upload status
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.less
  components/views/files/controls/Controls.vue
  libraries/Files/remote/textile/Bucket.ts
  plugins/thirdparty/persist.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Ready for QA

#2892 feat(account): better image format rules on profile pic creation
  components/views/user/create/Create.html
  components/views/user/create/Create.vue
  libraries/Files/TextileFileSystem.ts
  locales/en-US.js
  pages/auth/register/Register.html
  utilities/BlobToBase64.ts
Labels: QA approved, temporary blocked checking something

#2903 feat(ui): user update profile picture
  components/views/settings/pages/profile/index.vue
  store/accounts/actions.ts
  store/accounts/mutations.ts
Labels: temporary blocked checking something

#2952 feat(jest): 100% coverage for store/textile/getters
  store/textile/__snapshots__/getters.test.ts.snap
  store/textile/getters.test.ts
Labels: Missing Dev Review

#2917 feat(settings): nsfw filter user setting
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/pages/privacy/index.vue
  libraries/Textile/UserManager.ts
  libraries/Textile/schema.ts
  locales/en-US.js
  pages/setup/disclaimer/Disclaimer.html
  pages/setup/disclaimer/index.vue
  pages/setup/privacy/Privacy.html
  pages/setup/privacy/Privacy.less
  pages/setup/privacy/index.vue
  store/settings/actions.ts
  store/settings/mutations.ts
  store/settings/state.ts
  store/settings/types.ts
  store/textile/actions.ts
  types/textile/user.ts
Labels: Ready for QA

#2878 fix(replies): change avatar color to correct one
  components/views/chat/message/Message.less
  components/views/chat/message/reply/Item/Item.html
  components/views/chat/message/reply/Item/Item.less
  components/views/chat/message/reply/Item/Item.vue
  components/views/chat/message/reply/Reply.html
  components/views/chat/message/reply/Reply.less
  components/views/chat/message/reply/Reply.vue
Labels: Ready for QA

#2961 feat(jest): 86% coverage for BlobToBase64.ts
  utilities/BlobToBase64.test.ts
Labels: Missing Dev Review

#2960 feat(jest): 100% coverage for store/ui/getters
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/getters.test.ts
Labels: Missing Dev Review

#2717 chore(refactor): upload component refactor
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/files/upload/Upload.html
  components/views/files/upload/Upload.less
  components/views/files/upload/Upload.vue
  components/views/files/upload/filePreview/FilePreview.html
  components/views/files/upload/filePreview/FilePreview.less
  components/views/files/upload/filePreview/FilePreview.vue
  store/chat/__snapshots__/state.test.ts.snap
  store/chat/actions.ts
  store/chat/getters.ts
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
Labels: QA approved

#2914 chore(jest): add jest tests - 2717
  store/chat/__snapshots__/getters.test.ts.snap
  store/chat/__snapshots__/mutations.test.ts.snap
  store/chat/getters.test.ts
  store/chat/mutations.test.ts
Labels: draft

#2943 chore(locales): minor improvements
  locales/en-US.js
Labels: Missing Dev Review, QA approved

#2846 feat(files): large file downloads, improved qol, and improve extension fixing
  components/views/files/view/View.html
  components/views/files/view/View.vue
  libraries/Files/Fil.ts
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/remote/textile/Bucket.ts
  libraries/Files/test/__snapshots__/Directory.test.ts.snap
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
  libraries/Files/types/filesystem.ts
  package.json
  plugins/thirdparty/persist.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Changes Requested

#2965 feat(jest): 65% coverage for store/settings/actions
  store/settings/actions.test.ts
Labels: Missing Dev Review

#2954 fix(sidebar): theme color for unread badge
  components/views/navigation/sidebar/Sidebar.less
Labels: QA approved

#2964 test(cypress): remove privacy toggles screen validations
  components/views/friends/friend/Friend.html
  components/views/user/User.html
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/create-account-negative-tests.js
  cypress/integration/create-account.js
  cypress/integration/mobiles-responsiveness.js
  cypress/integration/pin-unlock-validations.js
  cypress/integration/privacy-page-toggles.js
  cypress/integration/snapshots-test.js
  cypress/support/commands.js
Labels: Missing Dev Review

#2968 chore(update): minor update
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#2967 test(cypress): add tests for profile note
  components/views/navigation/toolbar/Toolbar.html
  components/views/user/profile/About.vue
  components/views/user/profile/Profile.html
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
  cypress/integration/chat-features.js
  cypress/integration/chat-glyphs-validations.js
  cypress/integration/chat-images-validations.js
  cypress/integration/chat-pair-features.js
  cypress/integration/chat-text-validations.js
  cypress/integration/chat-top-toolbar.js
  cypress/integration/mobiles-responsiveness.js
Labels: Missing Dev Review

#2969 feat(jest): 100% coverage for store/settings/actions
  store/settings/actions.test.ts
Labels: Missing Dev Review

#2974 test(cypress): add tests for context menu
  components/interactables/ContextMenu/ContextMenu.html
  cypress/integration/chat-pair-features.js
  cypress/integration/mobiles-responsiveness.js
  cypress/support/commands.js
  layouts/chat.vue
Labels: Missing Dev Review

#2978 feat(jest): 100% coverage for store/settings/mutations
  store/settings/mutations.test.ts
Labels: Missing Dev Review

#2982 fix(files): change position of close button tooltip
  components/views/files/view/View.html
  components/views/files/view/View.less
Labels: Missing Dev Review, QA approved

#2981 fix(files): change line height for image title
  components/views/files/upload/previewItem/PreviewItem.less
  components/views/files/view/View.less
Labels: Missing Dev Review, QA approved

#2977 fix(settings): remove signaling server setting
  components/views/settings/pages/privacy/Privacy.html
Labels: Missing Dev Review, QA approved

#2984 test(cypress): add tests for chat search
  components/views/chat/search/input/Input.html
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/item/Item.html
  components/views/chat/search/result/meta/Meta.html
  cypress/integration/chat-features.js
  cypress/support/commands.js
Labels: Missing Dev Review, draft

#2980 fix(chat): fix quick reaction context menu
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/message/Message.vue
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/actions.test.ts
  store/ui/actions.ts
  store/ui/getters.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Ready for QA

#2958 feat(files): blur nsfw image thumbnails based on settings
  assets/styles/framework/blurs.less
  components/views/files/controls/Controls.vue
  components/views/files/file/File.html
  components/views/files/file/File.less
  components/views/files/file/File.vue
  components/views/files/view/View.html
  components/views/files/view/View.less
  components/views/files/view/View.vue
  libraries/Files/Fil.ts
  libraries/Files/FilSystem.ts
  libraries/Files/TextileFileSystem.ts
  libraries/Files/test/__snapshots__/Directory.test.ts.snap
  libraries/Files/test/__snapshots__/FilSystem.test.ts.snap
  libraries/Files/types/filesystem.ts
  store/ui/types.ts
  types/store/store.ts
Labels: Ready for QA

#2988 fix(locales): add punctuation
  locales/en-US.js
Labels: temporary blocked checking something

#3001 feat(jest): 87% coverage for libraries/Solana/Solana
  libraries/Solana/Solana.test.ts
  libraries/Solana/Solana.ts
  libraries/Solana/__snapshots__/Solana.test.ts.snap
Labels: Missing Dev Review, QA approved

#2971 fix(files): store cleanup and additional files status messages
  components/views/files/controls/Controls.html
  components/views/files/controls/Controls.vue
  components/views/files/file/File.html
  components/views/files/file/File.vue
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.vue
  components/views/files/list/List.html
  components/views/files/list/List.vue
  components/views/files/rename/Rename.html
  components/views/files/rename/Rename.vue
  components/views/files/row/Row.html
  components/views/files/row/Row.vue
  components/views/files/view/View.html
  components/views/files/view/View.vue
  layouts/files.vue
  locales/en-US.js
  pages/files/browse/index.vue
  plugins/thirdparty/persist.ts
  store/ui/__snapshots__/getters.test.ts.snap
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/getters.test.ts
  store/ui/getters.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: temporary blocked checking something

#3013 feat(jest): 100% coverage for store/chat/getters
  store/chat/__snapshots__/getters.test.ts.snap
  store/chat/getters.test.ts
Labels: Missing Dev Review, QA approved

#2962 chore(bundle): minors
  assets/img/glyphLoader.png
  assets/img/glyphLoader.webp
  assets/img/glyphShopBg1.png
  assets/img/glyphShopBg1.webp
  assets/img/glyphShopBg2.png
  assets/img/glyphShopBg2.webp
  assets/img/icon.png
  assets/img/icon.webp
  assets/img/icon_wht.png
  assets/img/icon_wht.webp
  assets/img/logo_center.svg
  assets/img/logo_center.webp
  assets/img/logo_sat.svg
  assets/img/logo_sat.webp
  assets/img/profile.png
  assets/img/profile.webp
  components/ui/Loaders/LogoLoader/LogoLoader.html
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/glyphs/sample/Sample.vue
  libraries/Files/remote/textile/Bucket.ts
  libraries/Textile/BucketManager.ts
  libraries/Textile/GroupChatManager.ts
  libraries/Textile/IdentityManager.ts
  libraries/Textile/MailboxManager.ts
  libraries/Textile/MetadataManager.test.ts
  libraries/Textile/MetadataManager.ts
  libraries/Textile/UserManager.ts
  mock/marketplace.ts
  mock/profile.ts
  nuxt.config.js
  package.json
Labels: QA approved, temporary blocked checking something

#3014 test(cypress): add tests for file folder rename
  components/interactables/InputGroup/InputGroup.html
  components/views/files/list/List.html
  components/views/files/rename/Rename.html
  components/views/files/row/Row.html
  components/views/files/viewSwitcher/ViewSwitcher.html
  cypress/integration/chat-features.js
  cypress/integration/chat-text-validations.js
  cypress/support/commands.js
  pages/files/browse/Browse.html
Labels: QA approved

#3017 chore(script): add script
  package.json
Labels: Missing Dev Review

#3021 feat(jest): 100% coverage for components/views/chat/search/SearchUtil
  components/views/chat/search/SearchUtil.test.ts
  components/views/chat/search/__snapshots__/SearchUtil.test.ts.snap
Labels: Changes Requested

#3002 fix(settings): disable scroll while crop is opening
  components/ui/Scroll/Scroll.less
  components/ui/Scroll/Scroll.vue
  components/views/settings/modal/Modal.html
  components/views/settings/modal/Modal.vue
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/state.ts
  store/ui/types.ts
Labels: QA approved
