Repository Satellite-im/Core-PWA, pull requests merged in 2022-10, with the labels that each got.

#5106 feat(jest): 59% coverage for DirectWebRTCBus
  libraries/WebRTC/bus/DirectWebRTCBus.test.ts
Labels: Missing Dev Review

#5057 feat(chat): add message loader in chat
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  components/views/chat/message/glyph/Glyph.html
  components/views/chat/message/glyph/Glyph.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
Labels: Missing Dev Review, QA tested

#5098 feat(chat): unread message indicators
  assets/styles/framework/animations.less
  components/ui/CaretDivider/CaretDivider.less
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.html
  components/views/chat/message/Message.less
  components/views/chat/message/Message.vue
  locales/en-US.js
Labels: Changes Requested, Missing Dev Review

#5110 chore(modals): check close button on all modals
  components/ui/Global/Global.html
  layouts/default.vue
  pages/auth/unlock/Unlock.html
Labels: Missing Dev Review, QA tested

#5100 feat(notifications): add browser notification click functionality
  components/ui/Global/Global.vue
  libraries/Iridium/NotificationManager.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/notifications/__snapshots__/types.test.ts.snap
  libraries/Iridium/notifications/types.ts
  pages/mobile/friends/index.vue
  utilities/Notifications.ts
Labels: Missing Dev Review

#5105 fix(chat): typing indicator on new conversation fixed
  store/chat/mutations.ts
Labels: Missing Dev Review, QA tested

#5120 fix(cta): layout and style
  assets/styles/framework/typography.less
  components/interactables/Button/Button.less
  components/views/callToAction/CallToAction.html
  components/views/callToAction/CallToAction.less
Labels: Missing Dev Review

#5123 fix(toolbar): hide notifications temporarily
  components/views/navigation/toolbar/Toolbar.html
Labels: Missing Dev Review

#5115 fix(notifications): don't display if user is already in the chat
  components/views/chat/conversation/Conversation.vue
  libraries/Enums/enums.ts
  libraries/Enums/types/notification-types.ts
  libraries/Iridium/chat/ChatManager.ts
  types/ui/notifications.d.ts
Labels: Ready for QA

#5126 feat(jest): 93% coverage for store/files/mutations
  store/files/mutations.test.ts
Labels: Missing Dev Review

#5121 feat(a11y): trap keyboard focus loop inside modals
  components/interactables/Close/Close.html
  components/interactables/Close/Close.less
  components/interactables/Close/Close.vue
  components/interactables/Close/README.md
  components/interactables/ImageCropper/ImageCropper.html
  components/interactables/ImageCropper/ImageCropper.less
  components/ui/Global/Global.vue
  components/ui/Modal/Modal.html
  components/ui/Modal/Modal.vue
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/Result.less
  components/views/files/rename/Rename.html
  components/views/marketplace/Marketplace.html
  components/views/navigation/toolbar/alerts/alert/Alert.html
  components/views/settings/Sidebar.vue
  components/views/user/profile/Profile.html
  components/views/wallet/popup/Popup.html
  package.json
  types/ui/sidebar.d.ts
Labels: QA tested

#5131 fix(chat): switch to Date.now for timestamp update
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review

#5097 refactor(sidebar): simplify sidebar button styles
  components/interactables/Tabs/Tabs.html
  components/interactables/Tabs/Tabs.less
  components/typography/Tag.vue
  components/typography/Text.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/list/item/Item.less
  components/views/navigation/sidebar/quick/Quick.less
  locales/en-US.js
Labels: Missing Dev Review, feel-free-to-add-opinions

#5134 fix(coming-soon): disabled button color
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/chatbar/upload/Upload.less
  locales/en-US.js
Labels: Missing Dev Review

#5133 fix(input): improve a11y around input component
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/interactables/Input/Input.vue
  package.json
Labels: Missing Dev Review

#5135 fix(chatbar): fix a11y outline around chatbar
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
Labels: Missing Dev Review

#5119 feat(notifications): add sound for new notifications
  libraries/Iridium/NotificationManager.ts
Labels: Missing Dev Review

#5137 fix(chatbar): placeholder visibility for ime langages
  components/interactables/Editable/Editable.vue
Labels: Missing Dev Review

#5141 chore(styles): organize base styles and remove unused
  assets/styles/base.less
  components/ui/ActionSheet/ActionSheet.vue
  components/ui/Banner/Banner.html
  components/ui/Banner/Banner.less
  components/ui/Banner/Banner.vue
  components/ui/Chat/Embeds/AudioPlayer/AudioPlayer.vue
  components/ui/ContextMenu/ContextMenu.vue
  components/ui/WelcomeModal/WelcomeModal.vue
  components/views/chat/chatbar/reply/Reply.less
  components/views/chat/chatbar/reply/Reply.vue
  components/views/chat/message/Markdown.vue
  components/views/chat/message/replies/Replies.less
  components/views/media/actions/settings/Settings.vue
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/settings/profile/card/Card.vue
  pages/friends/Friends.less
Labels: Missing Dev Review

#5101 refactor(users): implement better type safety and type guard
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/upload/Upload.vue
  components/views/friends/mobile/RequestList.vue
  components/views/friends/requests/Requests.vue
  components/views/message/Friend.html
  components/views/message/Friend.less
  components/views/message/Friend.vue
  layouts/desktop.vue
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/friends/types.ts
  libraries/Iridium/users/UsersManager.ts
  locales/en-US.js
  middleware/authenticated.ts
  pages/friends/index.vue
  pages/mobile/friends/index.vue
  utilities/notNull.ts
  utilities/typeGuard.test.ts
  utilities/typeGuard.ts
Labels: Ready for QA

#5130 test(cypress): fixes for chat images tests
  components/views/chat/chatbar/upload/Upload.html
  components/views/chat/conversation/Conversation.html
  components/views/confirmation/Confirmation.vue
  cypress/e2e/chat-images-validations.js
  cypress/support/commands.js
Labels: Missing Dev Review

#5138 feat(switch): improve switch a11y
  components/interactables/Switch/README.md
  components/interactables/Switch/Switch.html
  components/interactables/Switch/Switch.less
  components/interactables/Switch/Switch.vue
  components/views/settings/pages/audio/Audio.html
  components/views/settings/pages/audio/sounds/item/Item.vue
  components/views/settings/pages/privacy/Privacy.html
  components/views/settings/profile/accounts/Item/Item.html
  components/views/wallet/accounts/Accounts.html
  pages/auth/unlock/Unlock.html
Labels: QA tested

#5143 refactor(notifications): construct notification body inside of global…
  components/ui/Global/Global.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/notifications/types.ts
  locales/en-US.js
Labels: QA tested

#5108 chore(chat): remove observer
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review, QA tested

#5147 fix(notifications): take user to chat on chat notification click
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review, bug

#5145 feat(jest): 92% coverage for SearchIndex
  libraries/SatelliteDB/SearchIndex.test.ts
Labels: Missing Dev Review

#5159 feat(jest): 46% coverage for SolanaManager
  libraries/Solana/SolanaManager/SolanaManager.test.ts
Labels: Missing Dev Review

#5152 feat(sidebar): add keyboard accessibility to sidebar chat list
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.less
Labels: Ready for QA

#5155 feat(files): breadcrumbs a11y
  assets/styles/reset.css
  components/views/files/filepath/Filepath.html
  components/views/files/filepath/Filepath.less
Labels: Ready for QA

#5148 feat(files): upload files to ipfs
  components/ui/Chat/Image/Image.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/utils.ts
Labels: merge blocked

#5144 fix(scroll): infinite scroll trigger and scroll position
  components/ui/Banner/Banner.vue
  components/ui/Chat/InfiniteScroll/InfiniteScroll.less
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/replies/Replies.less
Labels: Missing Dev Review

#5164 refactor(hooks): switch conversation hooks to use param id, create webrtc hooks
  components/compositions/conversations.ts
  components/compositions/webrtc.ts
  components/views/chat/UserList.vue
  components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/toolbar/Toolbar.vue
  pages/chat/_id.vue
Labels: Missing Dev Review

#5167 fix(sidebar): small screen overflow issue
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/List.less
Labels: Missing Dev Review

#5171 feat(pip): drag release momentum
  components/ui/Pip/Pip.vue
Labels: Ready for QA

#5169 feat(jest): 100% coverage for DirectWebRTCBus
  libraries/WebRTC/bus/DirectWebRTCBus.test.ts
  utilities/typeGuard.test.ts
Labels: Missing Dev Review

#5163 feat(chatbar): add autocomplete to chatbar
  components/interactables/Editable/Editable.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/chatbar/autocomplete/Autocomplete.html
  components/views/chat/chatbar/autocomplete/Autocomplete.less
  components/views/chat/chatbar/autocomplete/Autocomplete.vue
Labels: merge-or-not-merge

#5180 feat(jest): 31% coverage for libraries/Crypto
  libraries/Crypto/Crypto.test.ts
Labels: Missing Dev Review

#5161 chore(cypress): adding cypress yml
  .github/workflows/cypress-tests.yml
  cypress/e2e/add-friend.js
  cypress/e2e/chat-features.js
  cypress/e2e/chat-glyphs-validations.js
  cypress/e2e/chat-images-validations.js
  cypress/scripts/sync-node-script.sh
  cypress/scripts/watch-script.sh
Labels: action-running

#5066 chore(action): eslint/prettier
  .github/workflows/eslint.yml
Labels: draft, feel-free-to-add-opinions

#5173 feat(sidebar): copy id icon
  components/ui/Circle/Circle.less
  components/views/navigation/sidebar/status/Status.html
  components/views/navigation/sidebar/status/Status.less
  components/views/navigation/sidebar/status/Status.vue
Labels: Missing Dev Review, QA tested

#5166 refactor(sidebar): switch SidebarListItem to composition api, add new hooks
  components/compositions/conversations.ts
  components/compositions/webrtc.ts
  components/views/chat/conversation/Conversation.vue
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.vue
  plugins/local/dayjs.ts
  store/settings/getters.ts
  utilities/timestamp.ts
Labels: Missing Dev Review

#5150 refactor(files): use UiModal with files fullscreen preview
  components/ui/Global/Global.html
  components/ui/Modal/Modal.html
  components/ui/Modal/Modal.less
  components/ui/Modal/Modal.vue
  components/views/files/view/View.html
  components/views/files/view/View.less
  components/views/files/view/View.vue
Labels: Ready for QA

#5190 chore(android): android build
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/getcapacitor/myapp/ExampleInstrumentedTest.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/im/satellite/core/MainActivity.java
  android/app/src/main/res/drawable-land-hdpi/splash.png
  android/app/src/main/res/drawable-land-mdpi/splash.png
  android/app/src/main/res/drawable-land-xhdpi/splash.png
  android/app/src/main/res/drawable-land-xxhdpi/splash.png
  android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  android/app/src/main/res/drawable-port-hdpi/splash.png
  android/app/src/main/res/drawable-port-mdpi/splash.png
  android/app/src/main/res/drawable-port-xhdpi/splash.png
  android/app/src/main/res/drawable-port-xxhdpi/splash.png
  android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/splash.png
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/ic_launcher_background.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/xml/file_paths.xml
  android/app/src/test/java/com/getcapacitor/myapp/ExampleUnitTest.java
  android/app:src:main:res:mipmap-hdpi:ic_launcher.png
  android/build.gradle
  android/capacitor.settings.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/readme.md
  android/settings.gradle
  android/variables.gradle
  capacitor.config.ts
  package.json
Labels: Missing Dev Review

#5209 chore(typo): fix typo
  android/readme.md
Labels: Missing Dev Review

#5214 fix(mobile): files layout width overflow
  pages/files/Files.less
Labels: Missing Dev Review

#5216 feat(editable): enterkeyhint attr
  components/interactables/Editable/Editable.vue
  components/views/chat/chatbar/Chatbar.html
Labels: Missing Dev Review

#5219 fix(permissions): add modify_audio_settings to android manifest
  android/app/src/main/AndroidManifest.xml
Labels: Missing Dev Review

#5221 fix(modal): z-index
  components/ui/Modal/Modal.less
Labels: Missing Dev Review

#5218 fix(native-mobile): remove prototype.at functions for compatibility
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/conversation/Conversation.vue
  components/views/files/controls/Controls.vue
  components/views/navigation/sidebar/list/item/Item.vue
  libraries/Iridium/chat/ChatManager.ts
  store/files/getters.ts
Labels: Missing Dev Review, bug

#5225 test(test): test
  .github/workflows/cypress-tests.yml
Labels: Ready for QA

#5223 chore(linkscript): update linkscript
  linkscript.sh
Labels: Ready for QA

#5222 feat(meta): add notification count to browser tab name
  components/compositions/friends.ts
  components/compositions/useMeta.test.disabled.ts
  components/compositions/useMeta.ts
Labels: Missing Dev Review, QA tested

#5211 chore(ci): generate android apk
  .github/workflows/android-apk.yml
  .github/workflows/comment-PR-apk.yml
Labels: Ready for QA, draft, feel-free-to-add-opinions

#5128 refactor(user-profile): card style rework
  components/interactables/Tabs/Tabs.less
  components/ui/Global/Global.html
  components/views/user/profile/About.vue
  components/views/user/profile/Profile.html
  components/views/user/profile/Profile.less
  components/views/user/profile/Profile.vue
  libraries/Iridium/users/types.ts
  locales/en-US.js
  pages/friends/Friends.less
  plugins/thirdparty/persist.ts
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: merge-or-not-merge

#5227 fix(android): overscroll bounce on webview
  assets/styles/base.less
Labels: Missing Dev Review

#5231 fix(modals): fix focus trap for welcome modal
  components/ui/Modal/Modal.vue
Labels: Ready for QA

#5178 chore(scroll): better loader ux and logic
  components/ui/Chat/InfiniteScroll/InfiniteScroll.html
  components/ui/Chat/InfiniteScroll/InfiniteScroll.less
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/ui/Loaders/Message/Message.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
Labels: merge-or-not-merge

#5238 test(cypress): fixes for chat toolbar and text tests
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/footer/Footer.html
  cypress/e2e/chat-glyphs-validations.js
  cypress/e2e/chat-search.js
  cypress/e2e/chat-text-validations.js
  cypress/e2e/chat-top-toolbar.js
  cypress/support/commands.js
Labels: Missing Dev Review

#5243 refactor(notifications): move all notification logic to global component
  components/compositions/listenToNotifications.ts
  components/interactables/TextButton/TextButton.vue
  components/ui/Global/Global.vue
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/notifications/__snapshots__/types.test.ts.snap
  libraries/Iridium/notifications/types.ts
Labels: Missing Dev Review

#5233 feat(native-android): clipboard improvement
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  components/compositions/capacitor.ts
  components/views/chat/message/Message.vue
  components/views/friends/search/Search.vue
  components/views/navigation/sidebar/status/Status.vue
  components/views/settings/pages/accounts/Accounts.html
  components/views/settings/pages/accounts/index.vue
  package.json
  pages/setup/phrase/Phrase.html
  pages/setup/phrase/index.vue
Labels: Ready for QA

#5244 fix(enhancers): remove z index
  components/views/chat/enhancers/Enhancers.less
Labels: Ready for QA

#5245 fix(chat-manager): don't display notifications for messages that were…
  components/compositions/listenToNotifications.ts
  components/ui/Global/Global.vue
  libraries/Iridium/chat/ChatManager.ts
Labels: Ready for QA, bug

#5212 refactor(chat): wrap image preview overlay in Modal component
  components/ui/Chat/Image/Overlay/Overlay.html
  components/ui/Chat/Image/Overlay/Overlay.less
  components/ui/Global/Global.html
  components/ui/Modal/Modal.less
  components/views/ModalDialog/ModalDialog.less
  components/views/callToAction/CallToAction.less
  components/views/confirmation/Confirmation.vue
  components/views/files/view/View.html
  components/views/media/incomingCall/IncomingCall.less
Labels: Ready for QA

#5247 feat(quickProfile): add focus trap and upgrade to comp api
  components/compositions/events.ts
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.vue
  components/ui/Modal/Modal.vue
Labels: Ready for QA

#5256 chore(delete): delete empty file
  types/ui/query.d.ts
Labels: Missing Dev Review

#5257 chore(update): minor update
  .prettierignore
  PULL_REQUEST_TEMPLATE.md
Labels: Missing Dev Review

#5259 chore(remove): remove not needed script
  package.json
  solana.localnet.sh
Labels: Missing Dev Review

#5261 refactor(sidebar): improve overflow css rule
  components/views/navigation/sidebar/Sidebar.less
Labels: Missing Dev Review

#5263 feat(search): implement fuzzy search for sidebar and userpicker
  components/compositions/conversations.ts
  components/interactables/UserPicker/UserPicker.vue
  components/views/navigation/sidebar/list/List.html
  components/views/navigation/sidebar/list/List.less
  components/views/navigation/sidebar/list/List.vue
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review

#5267 refactor(mobile): improve mobile nav template
  components/compositions/conversations.ts
  components/compositions/useMeta.ts
  components/ui/DotBadge/DotBadge.less
  components/ui/DotBadge/DotBadge.vue
  components/views/friends/Item.vue
  components/views/navigation/mobile/nav/Nav.html
  components/views/navigation/mobile/nav/Nav.less
  components/views/navigation/mobile/nav/Nav.vue
  layouts/mobile.vue
  locales/en-US.js
Labels: Missing Dev Review

#5258 chore(cypress): update cypress github action
  .github/workflows/cypress-tests.yml
  cypress/scripts/sync-node-script.sh
  cypress/scripts/watch-script.sh
Labels: being-tested-by-the-bot

#5265 feat(ios): add ios platform
  .prettierignore
  android/app/capacitor.build.gradle
  android/capacitor.settings.gradle
  capacitor.config.ts
  components/views/navigation/mobile/nav/Nav.less
  components/views/navigation/mobile/nav/Nav.vue
  ios/.gitignore
  ios/App/App.xcodeproj/project.pbxproj
  ios/App/App.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/App/App.xcworkspace/contents.xcworkspacedata
  ios/App/App.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/App/App/AppDelegate.swift
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/App/App/Assets.xcassets/Contents.json
  ios/App/App/Assets.xcassets/Splash.imageset/Contents.json
  ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732-1.png
  ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732-2.png
  ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732.png
  ios/App/App/Base.lproj/LaunchScreen.storyboard
  ios/App/App/Base.lproj/Main.storyboard
  ios/App/App/Info.plist
  ios/App/App/ViewController.swift
  ios/App/Podfile
  ios/readme.md
  layouts/default.vue
  layouts/mobile.vue
  middleware/safearea.ts
  nuxt.config.js
  package.json
  pages/mobile/chat/_id.vue
  pages/mobile/friends/index.vue
  pages/mobile/settings/index.vue
Labels: Missing Dev Review

#5279 chore(assets): delete not needed iOS assets
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
Labels: Missing Dev Review

#5255 fix(status-change-ui): fixed status overflow and busy icon size
  components/interactables/QuickProfile/QuickProfile.html
  components/ui/DynamicIcon/DynamicIcon.vue
  components/ui/SvgDefs/SvgDefs.vue
Labels: Missing Dev Review

#5280 chore(icons): update icons and splash screen
  ios/App/App/Assets.xcassets/AppIcon.appiconset/1024.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/120-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/120.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/152.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/167.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/180.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/40-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/40.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/58-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/58.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/60.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/80-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/80.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/87.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x-1.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
  ios/App/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/App/App/Assets.xcassets/Splash.imageset/Contents.json
  ios/App/App/Assets.xcassets/Splash.imageset/iphoneplus_splash.png
  ios/App/App/Assets.xcassets/Splash.imageset/iphonexsmax_splash.png
  ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732-1.png
  ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732-2.png
  ios/App/App/Assets.xcassets/Splash.imageset/splash-2732x2732.png
Labels: Missing Dev Review

#5262 chore(store): remove unused store values and components
  components/ui/Global/Global.html
  components/ui/Popups/Error/Error.html
  components/ui/Popups/Error/Error.less
  components/ui/Popups/Error/Error.vue
  components/ui/Popups/ErrorNetwork.vue
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.vue
  components/views/wallet/mini/Mini.less
  components/views/wallet/mini/Mini.vue
  components/views/wallet/mini/body/Body.html
  components/views/wallet/mini/body/Body.less
  components/views/wallet/mini/body/Body.vue
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: Ready for QA

#5281 chore(read-me): update read me
  ios/readme.md
Labels: Ready for QA

#5273 refactor(modal): create focusTrap composable and implement in Modal
  components/compositions/events.ts
  components/ui/Modal/Modal.vue
Labels: Ready for QA

#5282 test(cypress): fixes for several tests
  components/views/files/controls/Controls.html
  components/views/navigation/slimbar/Slimbar.html
  components/views/settings/modal/Modal.html
  components/views/settings/page/Page.html
  components/views/settings/unit/Unit.html
  cypress/e2e/chat-images-validations.js
  cypress/e2e/create-account-negative-tests.js
  cypress/e2e/create-account.js
  cypress/e2e/files-features.js
  cypress/e2e/localstorage-validations.js
  cypress/e2e/mobiles-responsiveness.js
  cypress/e2e/pin-unlock-validations.js
  cypress/e2e/privacy-page-toggles.js
  cypress/e2e/settings-features.js
  cypress/e2e/settings-privacy-page.js
  cypress/e2e/snapshots-test.js
  cypress/support/commands.js
  pages/files/Files.html
Labels: draft

#5284 fix(files): close after successful rename
  components/interactables/Input/Input.vue
  components/ui/Global/Global.html
  components/views/files/rename/Rename.vue
Labels: Missing Dev Review

#5291 fix(login): removed log error while logging in with no account
  store/accounts/actions.ts
Labels: Missing Dev Review, QA tested

#5292 fix(searching): removed quotes from search text
  components/views/chat/chatbar/autocomplete/Autocomplete.html
  locales/en-US.js
Labels: QA tested

#5297 chore(xcode): address warnings
  ios/App/App.xcodeproj/project.pbxproj
Labels: Missing Dev Review, QA tested

#5276 chore(cypress): safari
  cypress.config.js
  package.json
Labels: Missing Dev Review, QA tested

#5290 chore(scroll): better loader ux and logic
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/replies/Replies.html
  plugins/thirdparty/tooltip.ts
  utilities/chat.ts
Labels: QA tested

#5286 refactor(quickProfile): refactor to composition api
  components/interactables/QuickProfile/QuickProfile.html
  components/interactables/QuickProfile/QuickProfile.vue
Labels: Ready for QA

#5285 refactor(sidebar): use Nuxt link instead of button
  assets/styles/base.less
  components/ui/Chat/Image/Overlay/Overlay.less
  components/ui/EarlyAccessBanner/EarlyAccessBanner.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/list/item/Item.html
  components/views/navigation/sidebar/list/item/Item.less
  components/views/navigation/sidebar/list/item/Item.vue
Labels: Ready for QA

#5295 fix(chatbar): fixed alignment with autocomplete tab
  components/views/chat/chatbar/autocomplete/Autocomplete.less
Labels: Missing Dev Review

#5288 feat(notifications): add new group and new group members notifications
  components/compositions/listenToNotifications.ts
  components/views/chat/message/notice/Notice.vue
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/notifications/types.ts
  locales/en-US.js
Labels: Changes Requested

#5303 feat(android): overlay status and notification bars
  android/app/src/main/java/im/satellite/core/MainActivity.java
  android/app/src/main/res/values/styles.xml
Labels: Missing Dev Review

#5298 test(cypress): add cypress videos for failed specs as artifacts on CI
  .github/workflows/cypress-tests.yml
  cypress.config.js
  cypress/e2e/files-features.js
  package.json
Labels: draft

#5312 chore(eslint): update
  .eslintrc
  .eslintrc.js
  android/readme.md
  cypress/.eslintrc.json
Labels: Missing Dev Review

#5305 refactor(button): upgrade to composition api
  components/interactables/Button/Button.html
  components/interactables/Button/Button.vue
  components/interactables/Button/types.d.ts
  components/interactables/Input/Input.vue
  components/views/chat/message/attachments/Item/Item.html
Labels: Missing Dev Review, QA tested

#5307 refactor(mobile): upgrade toolbar to comp api
  components/views/navigation/mobile/toolbar/Toolbar.html
  components/views/navigation/mobile/toolbar/Toolbar.vue
Labels: Missing Dev Review, QA tested

#5301 refactor(quick): upgrade to composition api
  components/views/navigation/sidebar/quick/Quick.html
  components/views/navigation/sidebar/quick/Quick.vue
  pages/message/NewMessage.html
  pages/message/NewMessage.less
  pages/message/index.vue
Labels: Missing Dev Review, QA tested

#5315 test(cypress): update random username to have 12 chars
  cypress/e2e/add-friends.js
  cypress/e2e/create-account-negative-tests.js
  cypress/e2e/create-account.js
  cypress/e2e/localstorage-validations.js
  cypress/e2e/mobiles-responsiveness.js
  cypress/e2e/pin-unlock-validations.js
  cypress/e2e/snapshots-test.js
Labels: Missing Dev Review

#5314 refactor(sidebar): upgrade to comp api and standardize search ellipsis
  components/views/friends/mobile/List.vue
  components/views/navigation/sidebar/Sidebar.html
  components/views/navigation/sidebar/Sidebar.vue
  locales/en-US.js
  pages/mobile/chat/_id.vue
Labels: Ready for QA

#5319 refactor(sidebarToggle): comp api upgrade plus a11y improvement
  components/interactables/SidebarToggle/SidebarToggle.vue
  locales/en-US.js
Labels: Ready for QA

#5317 refactor(cta): refactor cta modal, improve button component props
  components/interactables/Button/Button.vue
  components/ui/Global/Global.html
  components/views/callToAction/CallToAction.html
  components/views/callToAction/CallToAction.less
  components/views/callToAction/CallToAction.vue
  components/views/files/rename/Rename.less
Labels: Ready for QA

#5328 test(cypress): update to validate URL On Coming Soon
  components/views/callToAction/CallToAction.vue
  cypress/support/commands.js
Labels: Missing Dev Review, draft

#5325 chore(ci): update chrome version to latest
  .github/workflows/cypress-tests.yml
Labels: draft

#5332 chore(fix): fix format on read me
  ios/readme.md
Labels: Missing Dev Review

#5331 chore(cypress): minor update
  cypress/e2e/version-number.js
  cypress/e2e/version-release-notes.js
Labels: Missing Dev Review, QA tested

#5311 feat(notifications): configure notification for member leaving group
  components/compositions/listenToNotifications.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/chat/types.ts
  libraries/Iridium/notifications/types.ts
  locales/en-US.js
Labels: Changes Requested

#5324 feat(edit-message): added auto complete
  components/views/chat/message/edit/Edit.html
  components/views/chat/message/edit/Edit.vue
Labels: QA tested

#5344 refactor(dragbar): comp api upgrade
  components/interactables/DragBar/DragBar.html
  components/interactables/DragBar/DragBar.vue
Labels: Ready for QA

#5336 refactor(chip): comp api upgrade
  components/interactables/Chip/Chip.vue
  components/interactables/UserPicker/UserPicker.html
Labels: Ready for QA

#5334 refactor(checkbox): comp api upgrade
  components/interactables/Checkbox/Checkbox.html
  components/interactables/Checkbox/Checkbox.less
  components/interactables/Checkbox/Checkbox.vue
Labels: Ready for QA

#5346 refactor(chat): upgrade right user list to script setup
  components/views/chat/UserList.vue
Labels: QA tested

#5309 refactor(enhancers): cleanup enhancers js logic, resolve css bug
  components/interactables/ButtonGroup/ButtonGroup.html
  components/interactables/ButtonGroup/ButtonGroup.less
  components/interactables/ButtonGroup/ButtonGroup.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.less
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/Enhancers.vue
Labels: QA tested

#5350 feat(mobile): fix insets and handle software keyboard and back button
  android/app/capacitor.build.gradle
  android/app/src/main/java/im/satellite/core/MainActivity.java
  android/capacitor.settings.gradle
  assets/styles/base.less
  components/views/navigation/mobile/nav/Nav.less
  ios/App/App/ViewController.swift
  ios/App/Podfile
  layouts/default.vue
  layouts/mobile.vue
  middleware/safearea.ts
  package.json
  pages/mobile/chat/_id.vue
  pages/mobile/friends/index.vue
  pages/mobile/settings/index.vue
  utilities/swiper.ts
Labels: QA tested

#5327 chore(add): lock app button
  components/interactables/QuickProfile/QuickProfile.less
  components/interactables/QuickProfile/QuickProfile.vue
  components/views/navigation/sidebar/status/Status.vue
  locales/en-US.js
  store/ui/types.ts
Labels: Missing Dev Review

#5365 chore(ci): update env
  .github/workflows/cypress-tests.yml
Labels: Missing Dev Review

#5363 fix(files): hide files links until functionality is smoother
  components/views/navigation/mobile/nav/Nav.vue
  components/views/navigation/sidebar/Sidebar.vue
Labels: Missing Dev Review, QA tested

#5359 chore(cypress): asserting early access info on sidebar
  cypress/e2e/create-account.js
Labels: draft

#5362 refactor(enhancers): upgrade enhancers templates, move reaction store…
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/controls/Controls.html
  components/views/chat/chatbar/controls/Controls.less
  components/views/chat/chatbar/controls/Controls.vue
  components/views/chat/enhancers/Enhancers.html
  components/views/chat/enhancers/Enhancers.vue
  components/views/chat/enhancers/emoji/Emoji.vue
  components/views/chat/enhancers/glyphs/item/Item.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/actions/Actions.html
  components/views/chat/message/edit/Edit.vue
  components/views/chat/message/reactions/Reactions.vue
  plugins/thirdparty/persist.ts
  store/chat/__snapshots__/state.test.ts.snap
  store/chat/mutations.ts
  store/chat/state.ts
  store/chat/types.ts
  store/ui/__snapshots__/mutations.test.ts.snap
  store/ui/__snapshots__/state.test.ts.snap
  store/ui/getters.ts
  store/ui/mutations.test.ts
  store/ui/mutations.ts
  store/ui/state.ts
  store/ui/types.ts
Labels: QA feedback

#5369 refactor(scroll): remove unused scroll component
  components/ui/SimpleScroll/SimpleScroll.html
  components/ui/SimpleScroll/SimpleScroll.less
  components/ui/SimpleScroll/SimpleScroll.vue
  components/views/chat/chatbar/commands/preview/Preview.html
  components/views/chat/chatbar/commands/preview/Preview.less
  components/views/chat/search/result/Result.html
  components/views/chat/search/result/Result.less
  components/views/marketplace/Marketplace.html
  components/views/marketplace/Marketplace.less
Labels: Missing Dev Review

#5372 refactor(userpicker): list item comp api upgrade
  components/interactables/UserPicker/ListItem/ListItem.html
  components/interactables/UserPicker/ListItem/ListItem.vue
Labels: Missing Dev Review

#5376 fix(enhancers): improve clickoutside behavior
  components/views/chat/enhancers/Enhancers.vue
  package.json
Labels: Missing Dev Review

#5374 fix(notifications): update new friend request notification data
  libraries/Iridium/friends/FriendsManager.ts
  libraries/Iridium/notifications/types.ts
Labels: Missing Dev Review, bug

#5380 fix(notifications): update broken link to mobile friend requests
  components/compositions/listenToNotifications.ts
Labels: Missing Dev Review, bug

#5368 refactor(tabs): comp api upgrade
  components/interactables/Button/Button.vue
  components/interactables/Tabs/Tabs.html
  components/interactables/Tabs/Tabs.vue
Labels: Missing Dev Review

#5386 fix(build): fix issue in dependency
  package.json
Labels: Missing Dev Review

#5389 fix(notifications): send call notification only after a call is estab…
  components/compositions/webrtc.ts
Labels: Missing Dev Review, bug

#5351 feat(scroll): add leading loader in chat
  components/ui/Chat/InfiniteScroll/InfiniteScroll.vue
  components/views/chat/conversation/Conversation.html
  components/views/chat/conversation/Conversation.less
  components/views/chat/conversation/Conversation.vue
Labels: Missing Dev Review

#5323 fix(context-menu): fix action sheet styles
  components/ui/ActionSheet/ActionSheet.vue
  components/ui/ContextMenu/ContextMenu.vue
  components/views/navigation/mobile/nav/Nav.less
Labels: Missing Dev Review, bug

#5393 fix(mobile): fix username overflow issues
  components/ui/BackgroundCall/BackgroundCall.html
  components/ui/BackgroundCall/BackgroundCall.less
  components/ui/BackgroundCall/BackgroundCall.vue
  components/views/chat/message/call/Call.html
  components/views/chat/message/call/Call.less
  components/views/friends/Item.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
Labels: Missing Dev Review, bug

#5399 feat(desktop): ground work for desktop native builds
  .github/workflows/build-desktop.yml
  README.md
  components/compositions/useMeta.ts
  ios/App/Satellite Core.xcworkspace/contents.xcworkspacedata
  package.json
  src-tauri/.gitignore
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/Info.plist
  src-tauri/build.rs
  src-tauri/build/mac.entitlements
  src-tauri/icons/128x128.png
  src-tauri/icons/128x128@2x.png
  src-tauri/icons/32x32.png
  src-tauri/icons/Square107x107Logo.png
  src-tauri/icons/Square142x142Logo.png
  src-tauri/icons/Square150x150Logo.png
  src-tauri/icons/Square284x284Logo.png
  src-tauri/icons/Square30x30Logo.png
  src-tauri/icons/Square310x310Logo.png
  src-tauri/icons/Square44x44Logo.png
  src-tauri/icons/Square71x71Logo.png
  src-tauri/icons/Square89x89Logo.png
  src-tauri/icons/StoreLogo.png
  src-tauri/icons/icon.icns
  src-tauri/icons/icon.ico
  src-tauri/icons/icon.png
  src-tauri/src/handler.rs
  src-tauri/src/main.rs
  src-tauri/tauri.conf.json
Labels: ready to merge

#5402 feat(mobile): keyboard and safe area insets
  components/interactables/Editable/Editable.vue
  components/views/chat/chatbar/Chatbar.html
  components/views/chat/chatbar/Chatbar.vue
  components/views/chat/enhancers/Enhancers.less
  components/views/chat/enhancers/emoji/Emoji.less
  components/views/chat/enhancers/glyphs/Glyphs.less
  components/views/chat/enhancers/glyphs/item/info/Info.less
  components/views/navigation/mobile/nav/Nav.vue
  ios/App/App/ViewController.swift
  layouts/mobile.vue
  middleware/safearea.ts
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#5401 feat(notifications): configure notification for incoming calls
  components/compositions/listenToNotifications.ts
  libraries/Iridium/chat/ChatManager.ts
  libraries/Iridium/notifications/types.ts
  locales/en-US.js
Labels: Missing Dev Review

#5383 feat(releaseData): add new hook for release data
  compositions/release.ts
Labels: Question

#5395 refactor(quickProfile): use new clickoutside comp utility
  components/interactables/QuickProfile/QuickProfile.vue
  components/views/chat/UserList.vue
  components/views/chat/message/Message.vue
Labels: Ready for QA

#5397 refactor(modal): comp api and clickoutside upgrade
  components/ui/Global/Global.html
  components/ui/Modal/Modal.html
  components/ui/Modal/Modal.less
  components/ui/Modal/Modal.vue
Labels: Ready for QA

#5384 chore(timestamp): implement timestamp utility
  components/views/chat/conversation/Conversation.vue
  components/views/chat/message/Message.vue
  components/views/chat/message/call/Call.vue
  components/views/chat/search/result/item/Item.vue
  store/settings/__snapshots__/getters.test.ts.snap
  store/settings/getters.test.ts
  store/settings/getters.ts
  store/ui/mutations.test.ts
Labels: Missing Dev Review

#5405 fix(misc): miscellaneous fixes
  components/ui/Global/Global.html
  components/ui/ResultsMessage/ResultsMessage.vue
  components/views/chat/conversation/Conversation.vue
  components/views/friends/Item.vue
  components/views/navigation/sidebar/Sidebar.less
  components/views/settings/pages/profile/Profile.html
  components/views/settings/pages/profile/Profile.less
  components/views/settings/pages/profile/index.vue
  libraries/Iridium/NotificationManager.ts
  libraries/Iridium/chat/ChatManager.ts
Labels: Missing Dev Review, bug

#5410 fix(chat): close conversation after swiping to chat list on mobile
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review, bug

#5409 fix(chat): replace user's username with 'you' for member added message
  components/views/chat/message/notice/Notice.vue
  locales/en-US.js
Labels: Missing Dev Review

#5411 refactor(mobile): remove unused emit
  components/views/navigation/sidebar/list/List.vue
  components/views/navigation/sidebar/list/item/Item.html
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#5416 test(cypress): fixes for cypress call tests
  cypress/integration-pair-chat/chat-first-user.js
  cypress/integration-pair-chat/chat-second-user.js
Labels: Missing Dev Review, draft

#5414 chore(cypress): minor updates
  cypress/e2e/chat-top-toolbar.js
  cypress/e2e/mobiles-responsiveness.js
  cypress/e2e/snapshots-test.js
Labels: draft

#5417 feat(call): resolve duration timestamp issue
  README.md
  components/views/chat/message/call/Call.vue
  components/views/media/heading/Heading.html
  components/views/media/heading/Heading.vue
Labels: Missing Dev Review

#5421 chore(update): updates
  libraries/Iridium/IdentityManager.test.ts
  libraries/Phantom/PhantonManager.test.ts
  libraries/SatelliteDB/SearchIndex.test.ts
  libraries/SatelliteDB/__snapshots__/SearchIndex.test.ts.snap
  libraries/WebRTC/Call.ts
  libraries/WebRTC/bus/DirectWebRTCBus.test.ts
  libraries/WebRTC/bus/DirectWebRTCBus.ts
  libraries/ui/Alerts.ts
  locales/.gitignore
  store/ui/mutations.ts
  utilities/duration.test.ts
Labels: Missing Dev Review

#5419 chore(jest): minor updates
  store/accounts/__snapshots__/mutations.test.ts.snap
  store/accounts/mutations.test.ts
Labels: Missing Dev Review

#5420 chore(update): update eslint
  .eslintrc.js
Labels: Missing Dev Review

#5413 refactor(mobile): upgrade chat page to script setup
  components/compositions/webrtc.ts
  components/ui/ActionSheet/ActionSheet.vue
  components/views/chat/conversation/Conversation.vue
  pages/mobile/chat/_id.vue
Labels: Missing Dev Review

#5424 fix(tsconfig): fix extends issue for nuxt tsconfig
  components/compositions/capacitor.ts
  components/compositions/listenToNotifications.ts
  components/compositions/webrtc.ts
  components/interactables/QuickProfile/QuickProfile.vue
  components/interactables/SidebarToggle/SidebarToggle.vue
  components/views/chat/UserList.vue
  components/views/chat/chatbar/controls/Controls.vue
  components/views/chat/chatbar/footer/TypingIndicator/TypingIndicator.vue
  components/views/chat/enhancers/Enhancers.vue
  components/views/navigation/mobile/nav/Nav.vue
  components/views/navigation/mobile/toolbar/Toolbar.vue
  components/views/navigation/sidebar/list/item/Item.vue
  components/views/navigation/sidebar/quick/Quick.vue
  components/views/navigation/toolbar/Toolbar.vue
  pages/chat/_id.vue
  pages/mobile/chat/_id.vue
  tsconfig.json
Labels: Missing Dev Review

#5431 chore(Cypress): asserting modal in create account view
  components/ui/InfoButton/InfoButton.vue
  cypress/e2e/create-account.js
Labels: being-tested-by-the-bot

#5385 feat(files): encrypt files when added to ipfs
  libraries/Iridium/utils.ts
Labels: Missing Dev Review, depending on other PR

#5436 chore(ios): add camera/microphone usage descriptions
  ios/App/App/Info.plist
Labels: Missing Dev Review

#5426 fix(friends-item): re-enable and adjust quick profile
  components/compositions/webrtc.ts
  components/interactables/Input/Input.html
  components/interactables/Input/Input.less
  components/ui/ActionSheet/ActionSheet.vue
  components/views/friends/Item.vue
  components/views/friends/mobile/List.vue
  components/views/navigation/sidebar/Sidebar.less
  components/views/navigation/sidebar/list/item/Item.less
Labels: Missing Dev Review
